const __almd_float = {
  to_string(n) { const s = String(n); return s.includes('.') || s.includes('e') ? s : s + '.0'; },
  to_int(n) { return Math.trunc(n); },
  round(n) { return Math.round(n); },
  floor(n) { return Math.floor(n); },
  ceil(n) { return Math.ceil(n); },
  abs(n) { return Math.abs(n); },
  sqrt(n) { return Math.sqrt(n); },
  parse(s) { const n = parseFloat(s); if (isNaN(n)) throw new Error("invalid float: " + s); return n; },
  from_int(n) { return n; },
  min(a, b) { return Math.min(a, b); },
  max(a, b) { return Math.max(a, b); },
  clamp(n, lo, hi) { return Math.max(lo, Math.min(hi, n)); },
  to_fixed(n, decimals) { return n.toFixed(decimals); },
};
