const __almd_int = {
  to_hex(n) { return (typeof n === "bigint" ? (n >= 0n ? n : n + (1n << 64n)).toString(16) : n.toString(16)); },
  to_string(n) { return String(n); },
  band(a, b) { return (a & b) >>> 0; },
  bor(a, b) { return (a | b) >>> 0; },
  bxor(a, b) { return (a ^ b) >>> 0; },
  bshl(a, n) { return (a << n) >>> 0; },
  bshr(a, n) { return a >>> n; },
  bnot(a) { return ~a; },
  wrap_add(a, b, bits) { const mask = bits === 32 ? 0xFFFFFFFF : (1 << bits) - 1; return ((a + b) & mask) >>> 0; },
  wrap_mul(a, b, bits) { const mask = bits === 32 ? 0xFFFFFFFF : (1 << bits) - 1; return (Math.imul(a, b) & mask) >>> 0; },
  rotate_right(a, n, bits) { const mask = bits === 32 ? 0xFFFFFFFF : (1 << bits) - 1; const v = a & mask; n = n % bits; return (((v >>> n) | (v << (bits - n))) & mask) >>> 0; },
  rotate_left(a, n, bits) { const mask = bits === 32 ? 0xFFFFFFFF : (1 << bits) - 1; const v = a & mask; n = n % bits; return (((v << n) | (v >>> (bits - n))) & mask) >>> 0; },
  to_u32(a) { return a >>> 0; },
  to_u8(a) { return a & 0xFF; },
  clamp(n, lo, hi) { return Math.max(lo, Math.min(hi, n)); },
  parse(s) { var n = parseInt(s, 10); if (isNaN(n) || !/^-?\d+$/.test(s.trim())) throw new Error("invalid digit found in string"); return n; },
  parse_hex(s) { var h = s.startsWith("0x") || s.startsWith("0X") ? s.slice(2) : s; var n = parseInt(h, 16); if (isNaN(n)) throw new Error("invalid digit found in string"); return n; },
  abs(n) { return Math.abs(n); },
  min(a, b) { return Math.min(a, b); },
  max(a, b) { return Math.max(a, b); },
  to_float(n) { return n; },
};
