const __almd_list = {
  len(xs) { return xs.length; },
  get(xs, i) { return (i >= 0 && i < xs.length) ? xs[i] : null; },
  get_or(xs, i, d) { return (i >= 0 && i < xs.length) ? xs[i] : d; },
  set(xs, i, v) { const r = [...xs]; if (i >= 0 && i < r.length) r[i] = v; return r; },
  swap(xs, i, j) { const r = [...xs]; if (i >= 0 && i < r.length && j >= 0 && j < r.length) { const t = r[i]; r[i] = r[j]; r[j] = t; } return r; },
  sort(xs) { return [...xs].sort(); },
  reverse(xs) { return [...xs].reverse(); },
  any(xs, f) { return xs.some(f); },
  all(xs, f) { return xs.every(f); },
  contains(xs, x) { return xs.includes(x); },
  each(xs, f) { xs.forEach(f); },
  map(xs, f) { return xs.map(f); },
  filter(xs, f) { return xs.filter(f); },
  find(xs, f) { return xs.find(f) ?? null; },
  fold(xs, init, f) { return xs.reduce(f, init); },
  enumerate(xs) { return xs.map((x, i) => [i, x]); },
  zip(a, b) { return a.slice(0, Math.min(a.length, b.length)).map((x, i) => [x, b[i]]); },
  flatten(xss) { return xss.flat(); },
  take(xs, n) { return xs.slice(0, n); },
  drop(xs, n) { return xs.slice(n); },
  sort_by(xs, f) { return [...xs].sort((a, b) => { const ka = f(a), kb = f(b); return ka < kb ? -1 : ka > kb ? 1 : 0; }); },
  unique(xs) { const seen = []; return xs.filter(x => { if (seen.includes(x)) return false; seen.push(x); return true; }); },
  index_of(xs, x) { const i = xs.indexOf(x); return i >= 0 ? i : null; },
  chunk(xs, n) { const r = []; for (let i = 0; i < xs.length; i += n) r.push(xs.slice(i, i + n)); return r; },
  filter_map(xs, f) { const r = []; for (const x of xs) { const v = f(x); if (v !== null) r.push(v); } return r; },
  take_while(xs, f) { const r = []; for (const x of xs) { if (!f(x)) break; r.push(x); } return r; },
  drop_while(xs, f) { let dropping = true; const r = []; for (const x of xs) { if (dropping && f(x)) continue; dropping = false; r.push(x); } return r; },
  count(xs, f) { return xs.filter(f).length; },
  partition(xs, f) { const a = [], b = []; for (const x of xs) { if (f(x)) a.push(x); else b.push(x); } return [a, b]; },
  reduce(xs, f) { if (xs.length === 0) return null; return xs.reduce(f); },
  group_by(xs, f) { const m = new Map(); for (const x of xs) { const k = f(x); if (!m.has(k)) m.set(k, []); m.get(k).push(x); } return m; },
  last(xs) { return xs.length > 0 ? xs[xs.length - 1] : null; },
  first(xs) { return xs.length > 0 ? xs[0] : null; },
  sum(xs) { return xs.reduce((a, b) => a + b, 0); },
  product(xs) { return xs.reduce((a, b) => a * b, 1); },
  is_empty(xs) { return xs.length === 0; },
  flat_map(xs, f) { return xs.flatMap(f); },
  min(xs) { return xs.length === 0 ? null : xs.reduce((a, b) => a < b ? a : b); },
  max(xs) { return xs.length === 0 ? null : xs.reduce((a, b) => a > b ? a : b); },
  join(xs, sep) { return xs.join(sep); },
  range(start, end) { const r = []; for (let i = start; i < end; i++) r.push(i); return r; },
  slice(xs, start, end) { return xs.slice(start, end); },
  insert(xs, i, v) { const r = [...xs]; r.splice(i, 0, v); return r; },
  remove_at(xs, i) { const r = [...xs]; if (i >= 0 && i < r.length) r.splice(i, 1); return r; },
  find_index(xs, f) { const i = xs.findIndex(f); return i >= 0 ? i : null; },
  update(xs, i, f) { const r = [...xs]; if (i >= 0 && i < r.length) r[i] = f(r[i]); return r; },
  repeat(v, n) { return Array(Math.max(0, n)).fill(v); },
  scan(xs, init, f) { let acc = init; return xs.map(x => { acc = f(acc, x); return acc; }); },
  intersperse(xs, sep) { const r = []; xs.forEach((x, i) => { if (i > 0) r.push(sep); r.push(x); }); return r; },
  windows(xs, n) { if (n <= 0 || n > xs.length) return []; const r = []; for (let i = 0; i <= xs.length - n; i++) r.push(xs.slice(i, i + n)); return r; },
  dedup(xs) { const r = []; for (const x of xs) { if (r.length === 0 || r[r.length - 1] !== x) r.push(x); } return r; },
  zip_with(a, b, f) { return a.slice(0, Math.min(a.length, b.length)).map((x, i) => f(x, b[i])); },
  sum_float(xs) { return xs.reduce((a, b) => a + b, 0); },
  product_float(xs) { return xs.reduce((a, b) => a * b, 1); },
};
