const __almd_set = {
  insert(s, v) { const r = new Set(s); r.add(v); return r; },
  remove(s, v) { const r = new Set(s); r.delete(v); return r; },
  union(a, b) { const r = new Set(a); for (const v of b) r.add(v); return r; },
  intersection(a, b) { const r = new Set(); for (const v of a) { if (b.has(v)) r.add(v); } return r; },
  difference(a, b) { const r = new Set(); for (const v of a) { if (!b.has(v)) r.add(v); } return r; },
  symmetric_difference(a, b) { const r = new Set(); for (const v of a) { if (!b.has(v)) r.add(v); } for (const v of b) { if (!a.has(v)) r.add(v); } return r; },
  is_subset(a, b) { for (const v of a) { if (!b.has(v)) return false; } return true; },
  is_disjoint(a, b) { for (const v of a) { if (b.has(v)) return false; } return true; },
  filter(s, f) { const r = new Set(); for (const v of s) { if (f(v)) r.add(v); } return r; },
  map(s, f) { const r = new Set(); for (const v of s) r.add(f(v)); return r; },
  fold(s, init, f) { let acc = init; for (const v of s) acc = f(acc, v); return acc; },
  each(s, f) { for (const v of s) f(v); },
  any(s, f) { for (const v of s) { if (f(v)) return true; } return false; },
  all(s, f) { for (const v of s) { if (!f(v)) return false; } return true; },
};
