const __almd_string = {
  trim(s) { return s.trim(); },
  split(s, sep) { return s.split(sep); },
  join(arr, sep) { return arr.join(sep); },
  len(s) { return s.length; },
  pad_left(s, n, ch) { return s.padStart(n, ch); },
  starts_with(s, prefix) { return s.startsWith(prefix); },
  slice(s, start, end) { return end !== undefined ? s.slice(start, end) : s.slice(start); },
  to_bytes(s) { return Array.from(new TextEncoder().encode(s)); },
  contains(s, sub) { return s.includes(sub); },
  capitalize(s) { return s.length === 0 ? "" : s[0].toUpperCase() + s.slice(1); },
  to_upper(s) { return s.toUpperCase(); },
  to_lower(s) { return s.toLowerCase(); },
  to_int(s) { const n = parseInt(s, 10); if (isNaN(n)) throw new Error("invalid integer: " + s); return n; },
  replace(s, from, to) { return s.split(from).join(to); },
  char_at(s, i) { return i < s.length ? s[i] : null; },
  lines(s) { return s.split("\n").filter(l => l.length > 0); },
  chars(s) { return [...s]; },
  index_of(s, needle) { const i = s.indexOf(needle); return i >= 0 ? i : null; },
  repeat(s, n) { return s.repeat(n); },
  from_bytes(bytes) { return new TextDecoder().decode(new Uint8Array(bytes)); },
  is_digit(s) { return s.length > 0 && /^[0-9]+$/.test(s); },
  is_alpha(s) { return s.length > 0 && /^[a-zA-Z]+$/.test(s); },
  is_alphanumeric(s) { return s.length > 0 && /^[a-zA-Z0-9]+$/.test(s); },
  is_whitespace(s) { return s.length > 0 && /^\s+$/.test(s); },
  replace_first(s, from, to) { const i = s.indexOf(from); return i < 0 ? s : s.slice(0, i) + to + s.slice(i + from.length); },
  last_index_of(s, needle) { const i = s.lastIndexOf(needle); return i >= 0 ? i : null; },
  to_float(s) { const n = parseFloat(s); if (isNaN(n)) throw new Error("invalid float number: " + s); return n; },
  pad_right(s, n, ch) { return s.padEnd(n, ch); },
  trim_start(s) { return s.trimStart(); },
  trim_end(s) { return s.trimEnd(); },
  count(s, sub) { if (!sub) return 0; let c = 0, i = 0; while ((i = s.indexOf(sub, i)) >= 0) { c++; i += sub.length; } return c; },
  is_empty(s) { return s.length === 0; },
  reverse(s) { return [...s].reverse().join(""); },
  strip_prefix(s, prefix) { return s.startsWith(prefix) ? s.slice(prefix.length) : null; },
  strip_suffix(s, suffix) { return s.endsWith(suffix) ? s.slice(0, -suffix.length) : null; },
  ends_with(s, suffix) { return s.endsWith(suffix); },
  is_upper(s) { return s.length > 0 && s === s.toUpperCase() && s !== s.toLowerCase(); },
  is_lower(s) { return s.length > 0 && s === s.toLowerCase() && s !== s.toUpperCase(); },
};
