use std::fs;
use std::path::Path;

/// Scan runtime directories and generate registry files.
pub fn generate_runtime_registry(out_dir: &Path) {
    // ── Rust runtime ──
    let rust_dir = Path::new("runtime/rs/src");
    if rust_dir.exists() {
        let mut rust_entries: Vec<_> = fs::read_dir(rust_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map_or(false, |ext| ext == "rs"))
            .filter(|e| e.file_name() != "lib.rs")
            .collect();
        rust_entries.sort_by_key(|e| e.file_name());

        let mut rust_out = String::new();
        rust_out.push_str("// AUTO-GENERATED by build.rs from runtime/rs/src/ — DO NOT EDIT\n\n");
        rust_out.push_str("pub const RUST_RUNTIME_MODULES: &[(&str, &str)] = &[\n");
        for entry in &rust_entries {
            let stem = entry.path().file_stem().unwrap().to_str().unwrap().to_string();
            let rel = format!("../../runtime/rs/src/{}.rs", stem);
            rust_out.push_str(&format!(
                "    (\"{stem}\", include_str!(\"{rel}\")),\n"
            ));
        }
        rust_out.push_str("];\n");

        fs::write(out_dir.join("rust_runtime.rs"), &rust_out).unwrap();
    }

    // Rerun if runtime files change
    println!("cargo:rerun-if-changed=runtime/rs/src");
}
