use std::fs;
use std::path::Path;

/// Scan runtime/ts/ and runtime/rs/ directories and generate registry files.
pub fn generate_runtime_registry(out_dir: &Path) {
    // ── TS runtime ──
    let ts_dir = Path::new("runtime/ts");
    if !ts_dir.exists() {
        return;
    }

    // Collect .ts files (excluding helpers which is special)
    let mut modules: Vec<String> = Vec::new();
    let mut entries: Vec<_> = fs::read_dir(ts_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "ts"))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in &entries {
        let stem = entry.path().file_stem().unwrap().to_str().unwrap().to_string();
        if stem != "helpers" {
            modules.push(stem);
        }
    }

    // Generate ts_runtime.rs (TS only — JS target removed)
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs from runtime/ts/ — DO NOT EDIT\n\n");

    for m in &modules {
        let upper = m.to_uppercase();
        out.push_str(&format!(
            "const MOD_{upper}: &str = include_str!(\"../../runtime/ts/{m}.ts\");\n"
        ));
    }
    out.push_str("const HELPERS: &str = include_str!(\"../../runtime/ts/helpers.ts\");\n");
    out.push('\n');

    out.push_str("const PREAMBLE: &str = \"// ---- Almide Runtime ----\\n\";\n");
    out.push_str("const EPILOGUE: &str = \"// ---- End Runtime ----\\n\";\n\n");

    out.push_str("pub struct RuntimeModule {\n    pub name: &'static str,\n    pub source: &'static str,\n}\n\n");
    out.push_str("pub static ALL_MODULES: &[RuntimeModule] = &[\n");
    for m in &modules {
        let upper = m.to_uppercase();
        out.push_str(&format!(
            "    RuntimeModule {{ name: \"{m}\", source: MOD_{upper} }},\n"
        ));
    }
    out.push_str("];\n\n");

    out.push_str(r#"pub fn full_runtime() -> String {
    let mut out = String::with_capacity(20480);
    out.push_str(PREAMBLE);
    for m in ALL_MODULES {
        out.push_str(m.source);
    }
    out.push_str(HELPERS);
    out.push_str(EPILOGUE);
    out
}
"#);

    fs::write(out_dir.join("ts_runtime.rs"), &out).unwrap();

    // ── Rust runtime ──
    let rust_dir = Path::new("runtime/rs/src");
    if rust_dir.exists() {
        let mut rust_entries: Vec<_> = fs::read_dir(rust_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map_or(false, |ext| ext == "rs"))
            .filter(|e| e.file_name() != "lib.rs")
            .collect();
        rust_entries.sort_by_key(|e| e.file_name());

        let mut rust_out = String::new();
        rust_out.push_str("// AUTO-GENERATED by build.rs from runtime/rs/src/ — DO NOT EDIT\n\n");
        rust_out.push_str("pub const RUST_RUNTIME_MODULES: &[(&str, &str)] = &[\n");
        for entry in &rust_entries {
            let stem = entry.path().file_stem().unwrap().to_str().unwrap().to_string();
            let rel = format!("../../runtime/rs/src/{}.rs", stem);
            rust_out.push_str(&format!(
                "    (\"{stem}\", include_str!(\"{rel}\")),\n"
            ));
        }
        rust_out.push_str("];\n");

        fs::write(out_dir.join("rust_runtime.rs"), &rust_out).unwrap();
    }

    // Rerun if runtime files change
    println!("cargo:rerun-if-changed=runtime/ts");
    println!("cargo:rerun-if-changed=runtime/js");
    println!("cargo:rerun-if-changed=runtime/rs/src");
}
