// The biggest per-source fn tables of the self-host registry, moved out of
// registry.rs (max-lines, #852): same entries, same order — the registry entry
// references the const instead of carrying the slice inline.

pub(crate) const BYTES_CORE_FNS: &[(&str, &str)] = &[("bytes_to_string", "bytes.to_string"), ("bytes_map_each", "bytes.map_each"),
                ("bytes_from_string", "bytes.from_string"),
                ("bytes_heap_save", "bytes.heap_save"),
                ("bytes_heap_restore", "bytes.heap_restore"),
                ("bytes_len", "bytes.len"),
                ("bytes_data_ptr", "bytes.data_ptr"),
                ("bytes_is_empty", "bytes.is_empty"),
                ("bytes_get_or", "bytes.get_or"),
                ("bytes_new", "bytes.new"),
                ("bytes_concat", "bytes.concat"),
                ("bytes_reverse", "bytes.reverse"),
                ("bytes_repeat", "bytes.repeat"),
                ("bytes_starts_with", "bytes.starts_with"),
                ("bytes_ends_with", "bytes.ends_with"),
                ("bytes_slice", "bytes.slice"),
                ("bytes_cmp", "bytes.cmp"),
                ("bytes_set", "bytes.set"),
                ("bytes_append", "bytes.append"),
                ("bytes_pad_left", "bytes.pad_left"),
                ("bytes_pad_right", "bytes.pad_right"),
                ("bytes_from_list", "bytes.from_list"),
                ("bytes_to_list", "bytes.to_list"),
                ("bytes_skip", "bytes.skip"),
                ("bytes_contains", "bytes.contains"),
                ("bytes_xor", "bytes.xor"),
                ("bytes_insert", "bytes.insert"),
                ("bytes_remove_at", "bytes.remove_at"),
                ("bytes_read_u16_be", "bytes.read_u16_be"),
                ("bytes_read_i16_be", "bytes.read_i16_be"),
                ("bytes_read_i16_le", "bytes.read_i16_le"),
                ("bytes_read_i32_be", "bytes.read_i32_be"),
                ("bytes_read_u8", "bytes.read_u8"),
                ("bytes_index", "bytes.index"),
                ("bytes_read_bool", "bytes.read_bool"),
                ("bytes_read_u16_le", "bytes.read_u16_le"),
                ("bytes_read_u32_be", "bytes.read_u32_be"),
                ("bytes_read_u32_le", "bytes.read_u32_le"),
                ("bytes_read_i32_le", "bytes.read_i32_le"),
                ("bytes_read_i64_be", "bytes.read_i64_be"),
                ("bytes_read_i64_le", "bytes.read_i64_le"),
                ("bytes_read_f64_be", "bytes.read_f64_be"),
                ("bytes_read_f64_le", "bytes.read_f64_le"),
                ("bytes_read_f32_be", "bytes.read_f32_be"),
                ("bytes_read_f32_le", "bytes.read_f32_le"),
                ("bytes_get", "bytes.get"),
                ("bytes_index_of", "bytes.index_of"),
                ("bytes_eof", "bytes.eof"),
                ("bytes_is_valid_utf8", "bytes.is_valid_utf8"),
];

pub(crate) const BYTES_MUTATE_FNS: &[(&str, &str)] = &[
                ("bytes_set_u8", "bytes.set_u8"),
                ("bytes_set_at", "bytes.set_at"),
                ("bytes_set_u16_be", "bytes.set_u16_be"),
                ("bytes_set_u16_le", "bytes.set_u16_le"),
                ("bytes_set_i16_be", "bytes.set_i16_be"),
                ("bytes_set_i16_le", "bytes.set_i16_le"),
                ("bytes_set_u32_be", "bytes.set_u32_be"),
                ("bytes_set_u32_le", "bytes.set_u32_le"),
                ("bytes_set_i32_be", "bytes.set_i32_be"),
                ("bytes_set_i32_le", "bytes.set_i32_le"),
                ("bytes_set_i64_be", "bytes.set_i64_be"),
                ("bytes_set_i64_le", "bytes.set_i64_le"),
                ("bytes_fill", "bytes.fill"),
                ("bytes_clear", "bytes.clear"),
                ("bytes_set_f64_be", "bytes.set_f64_be"),
                ("bytes_set_f64_le", "bytes.set_f64_le"),
                ("bytes_set_f32_be", "bytes.set_f32_be"),
                ("bytes_set_f32_le", "bytes.set_f32_le"),
                ("bytes_copy_within", "bytes.copy_within"),
                ("bytes_copy_from", "bytes.copy_from"),
];

pub(crate) const INT_SIZED_FNS: &[(&str, &str)] = &[
                ("int_to_int8", "int.to_int8"),
                ("int_to_int16", "int.to_int16"),
                ("int_to_int32", "int.to_int32"),
                ("int_to_int64", "int.to_int64"),
                ("int_to_int8_saturating", "int.to_int8_saturating"),
                ("int_to_int16_saturating", "int.to_int16_saturating"),
                ("int_to_int32_saturating", "int.to_int32_saturating"),
                ("int_to_uint64", "int.to_uint64"),
                ("int_from_int64", "int.from_int64"),
                ("int_from_uint64", "int.from_uint64"),
                ("int_to_uint8", "int.to_uint8"),
                ("int_to_uint16", "int.to_uint16"),
                ("int_to_uint32", "int.to_uint32"),
                ("int_from_int8", "int.from_int8"),
                ("int_from_int16", "int.from_int16"),
                ("int_from_int32", "int.from_int32"),
                ("int_from_uint8", "int.from_uint8"),
                ("int_from_uint16", "int.from_uint16"),
                ("int_from_uint32", "int.from_uint32"),
                ("int_to_uint8_saturating", "int.to_uint8_saturating"),
                ("int_to_uint16_saturating", "int.to_uint16_saturating"),
                ("int_to_uint32_saturating", "int.to_uint32_saturating"),
                ("int_to_uint64_saturating", "int.to_uint64_saturating"),
];
