//! The self-hosted stdlib runtime registry: (source, &[(impl_fn, call_name)]) tuples.
//! Extracted from render_wasm.rs to keep that file under the 1000-line limit. Paths are
//! one level deeper here, so include_str! uses ../../../../stdlib (vs ../../../ before).

pub fn self_host_runtime() -> &'static [(&'static str, &'static [(&'static str, &'static str)])] {
    &[
        (include_str!("../../../../stdlib/int_to_string.almd"), &[("int_to_string", "int.to_string")]),
        (include_str!("../../../../stdlib/random_int.almd"), &[("random_int", "random.int")]),
        (include_str!("../../../../stdlib/random_float.almd"), &[("random_float", "random.float")]),
        (include_str!("../../../../stdlib/random_choice.almd"), &[("random_choice", "random.choice"), ("random_choice_str", "random.choice_str")]),
        (include_str!("../../../../stdlib/random_shuffle.almd"), &[("random_shuffle", "random.shuffle"), ("random_shuffle_str", "random.shuffle_str")]),
        (include_str!("../../../../stdlib/env_args.almd"), &[("env_args", "env.args")]),
        (include_str!("../../../../stdlib/env_get.almd"), &[("env_get", "env.get")]),
        (include_str!("../../../../stdlib/process_args.almd"), &[("process_args", "process.args")]),
        (include_str!("../../../../stdlib/env_os.almd"), &[("env_os", "env.os")]),
        (include_str!("../../../../stdlib/env_temp_dir.almd"), &[("env_temp_dir", "env.temp_dir")]),
        (include_str!("../../../../stdlib/env_unix_timestamp.almd"), &[("env_unix_timestamp", "env.unix_timestamp")]),
        (include_str!("../../../../stdlib/clock_now.almd"), &[("datetime_now", "datetime.now"), ("env_millis", "env.millis")]),
        (include_str!("../../../../stdlib/fs_read_text.almd"), &[("fs_read_text", "fs.read_text")]),
        (include_str!("../../../../stdlib/fs_stat.almd"), &[("fs_stat", "fs.stat")]),
        (include_str!("../../../../stdlib/fs_read_bytes_raw.almd"), &[("fs_read_bytes_raw", "fs.read_bytes_raw")]),
        (include_str!("../../../../stdlib/fs_read_bytes.almd"), &[("fs_read_bytes", "fs.read_bytes")]),
        (include_str!("../../../../stdlib/fs_list_dir.almd"), &[("fs_list_dir", "fs.list_dir")]),
        (include_str!("../../../../stdlib/fs_write.almd"), &[("fs_write", "fs.write")]),
        (include_str!("../../../../stdlib/fs_mkdir_p.almd"), &[("fs_mkdir_p", "fs.mkdir_p")]),
        (include_str!("../../../../stdlib/fs_remove_all.almd"), &[("fs_remove_all", "fs.remove_all")]),
        (include_str!("../../../../stdlib/fs_exists.almd"), &[("fs_exists", "fs.exists")]),
        (include_str!("../../../../stdlib/io_print.almd"), &[("io_print", "io.print")]),
        (include_str!("../../../../stdlib/io_read_line.almd"), &[("io_read_line", "io.read_line")]),
        (include_str!("../../../../stdlib/io_read_n_bytes.almd"), &[("io_read_n_bytes", "io.read_n_bytes")]),
        (include_str!("../../../../stdlib/json_get.almd"), &[("json_get", "json.get")]),
        (include_str!("../../../../stdlib/json_as_array.almd"), &[("json_as_array", "json.as_array")]),
        (include_str!("../../../../stdlib/json_get_typed.almd"), &[("json_get_string", "json.get_string"), ("json_get_int", "json.get_int"), ("json_get_float", "json.get_float"), ("json_get_bool", "json.get_bool"), ("json_get_array", "json.get_array")]),
        (include_str!("../../../../stdlib/float_to_string.almd"), &[("float_to_string", "float.to_string"), ("float_to_fixed", "float.to_fixed")]),
        (include_str!("../../../../stdlib/bool.almd"), &[("bool_to_string", "bool.to_string")]),
        (include_str!("../../../../stdlib/error_chain.almd"), &[("error_chain", "error.chain"), ("error_context", "error.context")]),
        (include_str!("../../../../stdlib/error_message.almd"), &[("error_message", "error.message")]),
        (include_str!("../../../../stdlib/string_len.almd"), &[("string_len", "string.len"), ("string_length", "string.length")]),
        (include_str!("../../../../stdlib/string_repeat.almd"), &[("string_repeat", "string.repeat")]),
        (include_str!("../../../../stdlib/string_rle.almd"), &[("string_run_length_encode", "string.run_length_encode")]),
        (include_str!("../../../../stdlib/list_to_string_lsi.almd"), &[("list_to_string_lsi", "list.to_string_lsi")]),
        (include_str!("../../../../stdlib/string_is_empty.almd"), &[("string_is_empty", "string.is_empty")]),
        (include_str!("../../../../stdlib/string_eq.almd"), &[("string_eq", "string.eq")]),
        (include_str!("../../../../stdlib/string_class.almd"), &[("string_is_alpha", "string.is_alpha"), ("string_is_upper", "string.is_upper"), ("string_is_lower", "string.is_lower"), ("string_is_alphanumeric_uni", "string.is_alphanumeric")]),
        (include_str!("../../../../stdlib/string_cmp.almd"), &[("string_cmp", "string.cmp")]),
        (
            include_str!("../../../../stdlib/math_int.almd"),
            &[
                ("math_abs", "math.abs"),
                ("math_max", "math.max"),
                ("math_min", "math.min"),
                ("math_sign", "math.sign"),
                ("math_pow", "math.pow"),
                ("math_factorial", "math.factorial"),
                ("math_choose", "math.choose"),
            ],
        ),
        (
            include_str!("../../../../stdlib/option_pred.almd"),
            &[
                ("option_is_some", "option.is_some"),
                ("option_is_none", "option.is_none"),
                ("option_unwrap_or", "option.unwrap_or"),
                ("option_to_list", "option.to_list"),
                ("option_to_list_rc", "option.to_list_rc"),
            ],
        ),
        (
            include_str!("../../../../stdlib/option_unwrap_or_str.almd"),
            &[("option_unwrap_or_str", "option.unwrap_or_str")],
        ),
        (
            include_str!("../../../../stdlib/list_modify.almd"),
            &[
                ("list_set", "list.set"),
                ("list_set_str", "list.set_str"),
                ("list_insert_str", "list.insert_str"),
                ("list_remove_at_str", "list.remove_at_str"),
                ("list_swap_str", "list.swap_str"),
                ("list_update_str", "list.update_str"),
                ("list_update_value", "list.update_value"),
                ("list_swap", "list.swap"),
                ("list_insert", "list.insert"),
                ("list_remove_at", "list.remove_at"),
                ("list_tail", "list.tail"),
                ("list_take_end", "list.take_end"),
                ("list_drop_end", "list.drop_end"),
                ("list_drop_end_str", "list.drop_end_str"),
                ("list_update", "list.update"),
            ],
        ),
        (include_str!("../../../../stdlib/list_map.almd"), &[("list_map", "list.map")]),
        (include_str!("../../../../stdlib/list_partition.almd"), &[("list_partition", "list.partition"), ("list_partition_rc", "list.partition_rc")]),
        (include_str!("../../../../stdlib/list_pairs.almd"), &[("list_enumerate", "list.enumerate"), ("list_enumerate_str", "list.enumerate_str"), ("list_zip", "list.zip"), ("list_zip_rc", "list.zip_rc"), ("list_zip_sh", "list.zip_sh"), ("list_zip_hs", "list.zip_hs")]),
        (include_str!("../../../../stdlib/list_hshare.almd"), &[("list_get_or_hshare", "list.get_or_hshare"), ("list_get_hshare", "list.get_hshare"), ("list_first_hshare", "list.first_hshare"), ("list_last_hshare", "list.last_hshare"), ("list_take_hshare", "list.take_hshare"), ("list_unique_hshare", "list.unique_hshare"), ("list_dedup_hshare", "list.dedup_hshare"), ("list_contains_hshare", "list.contains_hshare"), ("list_index_of_hshare", "list.index_of_hshare")]),
        (include_str!("../../../../stdlib/list_map_str.almd"), &[("list_map_str", "list.map_str")]),
        (include_str!("../../../../stdlib/list_map_s2h.almd"), &[("list_map_s2h", "list.map_s2h")]),
        (include_str!("../../../../stdlib/list_filter_str.almd"), &[("list_filter_str", "list.filter_str")]),
        (include_str!("../../../../stdlib/list_reverse_str.almd"), &[("list_reverse_str", "list.reverse_str")]),
        (include_str!("../../../../stdlib/list_takedrop_str.almd"), &[("list_take_str", "list.take_str"), ("list_drop_str", "list.drop_str")]),
        (include_str!("../../../../stdlib/list_get_str.almd"), &[("list_get_str", "list.get_str"), ("list_first_str", "list.first_str"), ("list_last_str", "list.last_str")]),
        (include_str!("../../../../stdlib/bytes_array.almd"), &[("bytes_read_u16_le_array", "bytes.read_u16_le_array"), ("bytes_read_u32_le_array", "bytes.read_u32_le_array"), ("bytes_read_i32_le_array", "bytes.read_i32_le_array"), ("bytes_read_u16_be_array", "bytes.read_u16_be_array"), ("bytes_read_u32_be_array", "bytes.read_u32_be_array"), ("bytes_read_i16_le_array", "bytes.read_i16_le_array"), ("bytes_read_i16_be_array", "bytes.read_i16_be_array"), ("bytes_read_i32_be_array", "bytes.read_i32_be_array"), ("bytes_read_i64_le_array", "bytes.read_i64_le_array"), ("bytes_read_i64_be_array", "bytes.read_i64_be_array"), ("bytes_read_f64_le_array", "bytes.read_f64_le_array"), ("bytes_read_f64_be_array", "bytes.read_f64_be_array"), ("bytes_read_f32_le_array", "bytes.read_f32_le_array"), ("bytes_read_f32_be_array", "bytes.read_f32_be_array")]),
        (include_str!("../../../../stdlib/set_core.almd"), &[("set_from_list", "set.from_list"), ("set_len", "set.len"), ("set_is_empty", "set.is_empty"), ("set_contains", "set.contains"), ("set_to_list", "set.to_list"), ("set_union", "set.union"), ("set_intersection", "set.intersection"), ("set_difference", "set.difference"), ("set_is_subset", "set.is_subset"), ("set_is_disjoint", "set.is_disjoint"), ("set_new", "set.new"), ("set_insert", "set.insert"), ("set_remove", "set.remove"), ("set_symmetric_difference", "set.symmetric_difference"), ("set_filter", "set.filter"), ("set_all", "set.all"), ("set_any", "set.any"), ("set_map", "set.map"), ("set_fold", "set.fold")]),
        (include_str!("../../../../stdlib/list_str.almd"), &[("list_contains_str", "list.contains_str"), ("list_index_of_str", "list.index_of_str"), ("list_any_str", "list.any_str"), ("list_all_str", "list.all_str"), ("list_count_str", "list.count_str"), ("list_fold_str", "list.fold_str"), ("list_find_str", "list.find_str"), ("list_unique_str", "list.unique_str"), ("list_dedup_str", "list.dedup_str"), ("list_intersperse_str", "list.intersperse_str")]),
        (include_str!("../../../../stdlib/list_fold_ols.almd"), &[("list_fold_ols", "list.fold_ols")]),
        (include_str!("../../../../stdlib/list_fold_hrec.almd"), &[("list_fold_hrec", "list.fold_hrec")]),
        (include_str!("../../../../stdlib/list_sort_by_keys.almd"), &[("list_sort_by_keys", "list.sort_by_keys")]),
        (include_str!("../../../../stdlib/map_hobj.almd"), &[("map_from_list_hobj", "map.from_list_hobj")]),
        (include_str!("../../../../stdlib/set_str.almd"), &[("set_from_list_str", "set.from_list_str"), ("set_contains_str", "set.contains_str"), ("set_to_list_str", "set.to_list_str"), ("set_union_str", "set.union_str"), ("set_intersection_str", "set.intersection_str"), ("set_difference_str", "set.difference_str"), ("set_is_subset_str", "set.is_subset_str"), ("set_is_disjoint_str", "set.is_disjoint_str"), ("set_new_str", "set.new_str"), ("set_insert_str", "set.insert_str"), ("set_remove_str", "set.remove_str"), ("set_symmetric_difference_str", "set.symmetric_difference_str"), ("set_filter_str", "set.filter_str"), ("set_all_str", "set.all_str"), ("set_any_str", "set.any_str"), ("set_fold_str", "set.fold_str"), ("set_eq_str", "set.eq_str")]),
        (include_str!("../../../../stdlib/map_str.almd"), &[("map_new_str", "map.new_str"), ("map_from_list_str", "map.from_list_str"), ("map_len_str", "map.len_str"), ("map_is_empty_str", "map.is_empty_str"), ("map_contains_str", "map.contains_str"), ("map_get_str", "map.get_str"), ("map_set_str", "map.set_str"), ("map_keys_str", "map.keys_str"), ("map_values_str", "map.values_str"), ("map_remove_str", "map.remove_str"), ("map_merge_str", "map.merge_str"), ("map_update_str", "map.update_str"), ("map_filter_str", "map.filter_str"), ("map_all_str", "map.all_str"), ("map_any_str", "map.any_str"), ("map_count_str", "map.count_str"), ("map_fold_str", "map.fold_str")]),
        (include_str!("../../../../stdlib/map_fold_hacc.almd"), &[("map_fold_str_msi", "map.fold_str_msi"), ("map_fold_skv_msi", "map.fold_skv_msi"), ("list_fold_str_msi", "list.fold_str_msi")]),
        (include_str!("../../../../stdlib/map_msv.almd"), &[("map_new_msv", "map.new_msv"), ("map_set_msv", "map.set_msv"), ("map_from_list_msv", "map.from_list_msv"), ("map_get_or_msv", "map.get_or_msv")]),
        (include_str!("../../../../stdlib/map_mlo.almd"), &[("map_new_mlo", "map.new_mlo"), ("map_set_mlo", "map.set_mlo"), ("map_from_list_mlo", "map.from_list_mlo"), ("map_to_string_mlo", "map.to_string_mlo"), ("list_to_string_lmlo", "list.to_string_lmlo")]),
        (include_str!("../../../../stdlib/map_core.almd"), &[("map_new", "map.new"), ("map_len", "map.len"), ("map_is_empty", "map.is_empty"), ("map_contains", "map.contains"), ("map_get_or", "map.get_or"), ("map_set", "map.set"), ("map_remove", "map.remove"), ("map_keys", "map.keys"), ("map_values", "map.values"), ("map_get", "map.get"), ("map_merge", "map.merge"), ("map_update", "map.update"), ("map_filter", "map.filter"), ("map_all", "map.all"), ("map_any", "map.any"), ("map_count", "map.count"), ("map_fold", "map.fold")]),
        (include_str!("../../../../stdlib/map_skv.almd"), &[("map_new_skv", "map.new_skv"), ("map_len_skv", "map.len_skv"), ("map_is_empty_skv", "map.is_empty_skv"), ("map_contains_skv", "map.contains_skv"), ("map_get_or_skv", "map.get_or_skv"), ("map_get_skv", "map.get_skv"), ("map_set_skv", "map.set_skv"), ("map_remove_skv", "map.remove_skv"), ("map_keys_skv", "map.keys_skv"), ("map_values_skv", "map.values_skv"), ("map_filter_skv", "map.filter_skv"), ("map_all_skv", "map.all_skv"), ("map_any_skv", "map.any_skv"), ("map_count_skv", "map.count_skv"), ("map_fold_skv", "map.fold_skv"), ("map_eq_skv", "map.eq_skv"), ("map_entries_skv", "map.entries_skv"), ("map_from_list_skv", "map.from_list_skv"), ("map_find_skv", "map.find_skv"), ("map_update_skv", "map.update_skv"), ("map_map_skv", "map.map_skv"), ("map_merge_skv", "map.merge_skv")]),
                        (include_str!("../../../../stdlib/codec_encode.almd"), &[
            ("__encode_list_int", "__encode_list_int"), ("__encode_list_float", "__encode_list_float"),
            ("__encode_list_bool", "__encode_list_bool"), ("__encode_list_string", "__encode_list_string"),
            ("__encode_option_int", "__encode_option_int"), ("__encode_option_float", "__encode_option_float"),
            ("__encode_option_bool", "__encode_option_bool"), ("__encode_option_string", "__encode_option_string")]),
        (include_str!("../../../../stdlib/codec_decode.almd"), &[
            ("__decode_list_int", "__decode_list_int"), ("__decode_list_float", "__decode_list_float"),
            ("__decode_list_bool", "__decode_list_bool"), ("__decode_list_string", "__decode_list_string"),
            ("__decode_option_int", "__decode_option_int"), ("__decode_option_float", "__decode_option_float"),
            ("__decode_option_bool", "__decode_option_bool"), ("__decode_option_string", "__decode_option_string"),
            ("__decode_default_int", "__decode_default_int"), ("__decode_default_float", "__decode_default_float"),
            ("__decode_default_bool", "__decode_default_bool"), ("__decode_default_string", "__decode_default_string")]),
        (include_str!("../../../../stdlib/value_core.almd"), &[("value_null", "value.null"), ("value_int", "value.int"), ("value_bool", "value.bool"), ("value_float", "value.float"), ("value_as_int", "value.as_int"), ("value_as_bool", "value.as_bool"), ("value_as_float", "value.as_float"), ("value_str", "value.str"), ("value_as_string", "value.as_string"), ("value_array", "value.array"), ("value_as_array", "value.as_array"), ("value_object", "value.object"), ("value_eq", "value.eq"), ("list_eq_int", "list.eq_int"), ("list_eq_str", "list.eq_str"), ("list_eq_value", "list.eq_value"), ("list_eq_float", "list.eq_float"), ("list_eq_bool", "list.eq_bool"), ("list_eq_list_int", "list.eq_list_int"), ("list_eq_list_float", "list.eq_list_float"), ("list_eq_list_str", "list.eq_list_str"), ("list_eq_opt_int", "list.eq_opt_int"), ("list_set_value", "list.set_value"), ("list_insert_value", "list.insert_value"), ("list_remove_at_value", "list.remove_at_value"), ("list_swap_value", "list.swap_value"), ("value_merge", "value.merge"), ("json_keys", "json.keys"), ("value_stringify", "value.stringify"), ("json_stringify_pretty", "json.stringify_pretty"), ("value_get", "value.get"), ("value_field", "value.field"), ("result_value_unwrap_or", "result.value_unwrap_or"), ("result_list_value_unwrap_or", "result.list_value_unwrap_or"), ("result_str_unwrap_or", "result.str_unwrap_or"), ("result_flat_unwrap_or", "result.flat_unwrap_or"), ("option_value_unwrap_or", "option.value_unwrap_or"), ("option_liststr_unwrap_or", "option.liststr_unwrap_or"), ("option_listint_unwrap_or", "option.listint_unwrap_or"), ("option_listvalue_unwrap_or", "option.listvalue_unwrap_or"), ("list_get_value", "list.get_value"), ("list_get_or_value", "list.get_or_value"), ("list_first_value", "list.first_value"), ("list_last_value", "list.last_value"), ("list_get_liststr", "list.get_liststr"), ("list_first_liststr", "list.first_liststr"), ("list_last_liststr", "list.last_liststr"), ("map_entries_str", "map.entries_str"), ("list_take_liststr", "list.take_liststr"), ("list_drop_liststr", "list.drop_liststr")]),
        (include_str!("../../../../stdlib/list_filter.almd"), &[("list_filter", "list.filter")]),
        (include_str!("../../../../stdlib/list_filter_rc.almd"), &[("list_filter_rc", "list.filter_rc")]),
        (
            include_str!("../../../../stdlib/list_anyall.almd"),
            &[("list_any", "list.any"), ("list_all", "list.all"), ("list_count", "list.count")],
        ),
        (
            include_str!("../../../../stdlib/list_whilep.almd"),
            &[("list_take_while", "list.take_while"), ("list_drop_while", "list.drop_while"), ("list_take_while_str", "list.take_while_str"), ("list_drop_while_str", "list.drop_while_str")],
        ),
        (include_str!("../../../../stdlib/list_foldf.almd"), &[("list_fold", "list.fold")]),
        (
            include_str!("../../../../stdlib/list_find.almd"),
            &[("list_find", "list.find"), ("list_find_index", "list.find_index")],
        ),
        (include_str!("../../../../stdlib/list_reduce.almd"), &[("list_reduce", "list.reduce"), ("list_reduce_str", "list.reduce_str")]),
        (include_str!("../../../../stdlib/list_scan.almd"), &[("list_scan", "list.scan")]),
        (include_str!("../../../../stdlib/list_zipwith.almd"), &[("list_zip_with", "list.zip_with")]),
        (include_str!("../../../../stdlib/list_sortby.almd"), &[("list_sort_by", "list.sort_by"), ("list_sort_by_rc", "list.sort_by_rc")]),
        (include_str!("../../../../stdlib/list_uniqueby.almd"), &[("list_unique_by", "list.unique_by")]),
        (include_str!("../../../../stdlib/list_filtermap.almd"), &[("list_filter_map", "list.filter_map")]),
        (include_str!("../../../../stdlib/list_flatmap.almd"), &[("list_flat_map", "list.flat_map")]),
        (
            include_str!("../../../../stdlib/float_core.almd"),
            &[
                ("float_abs", "float.abs"),
                ("float_sqrt", "float.sqrt"),
                ("float_floor", "float.floor"),
                ("float_ceil", "float.ceil"),
                ("float_min", "float.min"),
                ("float_max", "float.max"),
                ("float_to_int", "float.to_int"),
                ("float_from_int", "float.from_int"),
                ("float_to_float64", "float.to_float64"),
                ("float_from_float64", "float.from_float64"),
            ],
        ),
        (
            include_str!("../../../../stdlib/float_extra.almd"),
            &[
                ("float_clamp", "float.clamp"),
                ("float_is_nan", "float.is_nan"),
                ("float_sign", "float.sign"),
                ("float_is_infinite", "float.is_infinite"),
            ],
        ),
        (include_str!("../../../../stdlib/float_round.almd"), &[("float_round", "float.round")]),
        (
            include_str!("../../../../stdlib/math_float.almd"),
            &[
                ("math_sqrt", "math.sqrt"), ("math_fmin", "math.fmin"), ("math_fmax", "math.fmax"),
                ("math_pi", "math.pi"), ("math_e", "math.e"),
            ],
        ),
        (include_str!("../../../../stdlib/math_log.almd"), &[("math_log", "math.log"), ("math_log2", "math.log2"), ("math_log10", "math.log10")]),
        (include_str!("../../../../stdlib/math_exp.almd"), &[("math_exp", "math.exp")]),
        (include_str!("../../../../stdlib/math_trig.almd"), &[("math_sin", "math.sin"), ("math_cos", "math.cos"), ("math_tan", "math.tan")]),
        (include_str!("../../../../stdlib/math_atan.almd"), &[("math_atan", "math.atan")]),
        (include_str!("../../../../stdlib/math_tanh.almd"), &[("math_tanh", "math.tanh")]),
        (include_str!("../../../../stdlib/math_fpow.almd"), &[("math_fpow", "math.fpow")]),
        (include_str!("../../../../stdlib/math_lgamma.almd"), &[("math_log_gamma", "math.log_gamma")]),
        (include_str!("../../../../stdlib/bytes_append_multi.almd"), &[("bytes_append_u16_le", "bytes.append_u16_le"), ("bytes_append_u16_be", "bytes.append_u16_be"), ("bytes_append_i16_le", "bytes.append_i16_le"), ("bytes_append_i16_be", "bytes.append_i16_be"), ("bytes_append_u32_le", "bytes.append_u32_le"), ("bytes_append_u32_be", "bytes.append_u32_be"), ("bytes_append_i32_le", "bytes.append_i32_le"), ("bytes_append_i32_be", "bytes.append_i32_be"), ("bytes_append_i64_le", "bytes.append_i64_le"), ("bytes_append_i64_be", "bytes.append_i64_be"), ("bytes_append_f32_le", "bytes.append_f32_le"), ("bytes_append_f32_be", "bytes.append_f32_be"), ("bytes_append_f64_le", "bytes.append_f64_le"), ("bytes_append_f64_be", "bytes.append_f64_be")]),
        (include_str!("../../../../stdlib/bytes_typed.almd"), &[("bytes_endian_le", "LittleEndian"), ("bytes_endian_be", "BigEndian"), ("bytes_read_uint16", "bytes.read_uint16"), ("bytes_read_uint32", "bytes.read_uint32"), ("bytes_read_int32", "bytes.read_int32"), ("bytes_read_float32", "bytes.read_float32"), ("bytes_write_uint16", "bytes.write_uint16"), ("bytes_write_uint32", "bytes.write_uint32"), ("bytes_write_int32", "bytes.write_int32"), ("bytes_write_float32", "bytes.write_float32"), ("bytes_set_uint16", "bytes.set_uint16"), ("bytes_set_uint32", "bytes.set_uint32"), ("bytes_set_int32", "bytes.set_int32"), ("bytes_set_float32", "bytes.set_float32")]),
        (include_str!("../../../../stdlib/bytes_cursor.almd"), &[("bytes_read_u8_at", "bytes.read_u8_at"), ("bytes_read_bool_at", "bytes.read_bool_at"), ("bytes_read_u16_le_at", "bytes.read_u16_le_at"), ("bytes_read_u16_be_at", "bytes.read_u16_be_at"), ("bytes_read_i16_le_at", "bytes.read_i16_le_at"), ("bytes_read_i16_be_at", "bytes.read_i16_be_at"), ("bytes_read_u32_le_at", "bytes.read_u32_le_at"), ("bytes_read_u32_be_at", "bytes.read_u32_be_at"), ("bytes_read_i32_le_at", "bytes.read_i32_le_at"), ("bytes_read_i32_be_at", "bytes.read_i32_be_at"), ("bytes_read_i64_le_at", "bytes.read_i64_le_at"), ("bytes_read_i64_be_at", "bytes.read_i64_be_at"), ("bytes_read_f16_le_at", "bytes.read_f16_le_at"), ("bytes_read_f32_le_at", "bytes.read_f32_le_at"), ("bytes_read_f32_be_at", "bytes.read_f32_be_at"), ("bytes_read_f64_le_at", "bytes.read_f64_le_at"), ("bytes_read_f64_be_at", "bytes.read_f64_be_at"), ("bytes_take_at", "bytes.take_at"), ("bytes_read_string_be_at", "bytes.read_string_be_at")]),
        (include_str!("../../../../stdlib/bytes_f16.almd"), &[("bytes_read_f16_le", "bytes.read_f16_le"), ("bytes_read_f16_le_array", "bytes.read_f16_le_array")]),
        (
            include_str!("../../../../stdlib/matrix_activations.almd"),
            &[("matrix_softmax_rows", "matrix.softmax_rows"), ("matrix_gelu", "matrix.gelu"), ("matrix_swiglu_gate", "matrix.swiglu_gate"), ("matrix_rope_rotate", "matrix.rope_rotate"), ("matrix_multi_head_attention", "matrix.multi_head_attention"), ("matrix_masked_multi_head_attention", "matrix.masked_multi_head_attention"), ("matrix_from_q1_0_bytes", "matrix.from_q1_0_bytes")],
        ),
        (
            include_str!("../../../../stdlib/matrix_shape.almd"),
            &[("matrix_shape", "matrix.shape")],
        ),
        (
            include_str!("../../../../stdlib/matrix_fused.almd"),
            &[("matrix_mul_scaled", "matrix.mul_scaled"), ("matrix_mul_f32", "matrix.mul_f32"), ("matrix_mul_f32_scaled", "matrix.mul_f32_scaled"), ("matrix_mul_f32_t", "matrix.mul_f32_t"), ("matrix_mul_f32_t_scaled", "matrix.mul_f32_t_scaled"), ("matrix_zeros_f32", "matrix.zeros_f32"), ("matrix_ones_f32", "matrix.ones_f32"), ("matrix_attention_weights", "matrix.attention_weights"), ("matrix_scaled_dot_product_attention", "matrix.scaled_dot_product_attention")],
        ),
        (
            include_str!("../../../../stdlib/matrix_ext.almd"),
            &[("matrix_silu_mul", "matrix.silu_mul"), ("matrix_broadcast_add_row", "matrix.broadcast_add_row"), ("matrix_row_dot", "matrix.row_dot"), ("matrix_conv1d", "matrix.conv1d"), ("matrix_to_bytes_f64_le", "matrix.to_bytes_f64_le"), ("matrix_to_bytes_f32_le", "matrix.to_bytes_f32_le"), ("matrix_from_bytes_f64_le", "matrix.from_bytes_f64_le")],
        ),
        (
            include_str!("../../../../stdlib/matrix_arith.almd"),
            &[("matrix_sub", "matrix.sub"), ("matrix_div", "matrix.div"), ("matrix_neg", "matrix.neg"), ("matrix_pow", "matrix.pow")],
        ),
        (
            include_str!("../../../../stdlib/matrix_core.almd"),
            &[
                ("matrix_from_lists", "matrix.from_lists"),
                ("matrix_to_lists", "matrix.to_lists"),
                ("matrix_zeros", "matrix.zeros"),
                ("matrix_ones", "matrix.ones"),
                ("matrix_rows", "matrix.rows"),
                ("matrix_cols", "matrix.cols"),
                ("matrix_get", "matrix.get"),
                ("matrix_add", "matrix.add"),
                ("matrix_scale", "matrix.scale"),
                ("matrix_map", "matrix.map"),
                ("matrix_transpose", "matrix.transpose"),
                ("matrix_slice_rows", "matrix.slice_rows"),
                ("matrix_gather_rows", "matrix.gather_rows"),
                ("matrix_causal_mask_add", "matrix.causal_mask_add"),
                ("matrix_dot_row", "matrix.dot_row"),
                ("matrix_mul", "matrix.mul"),
                ("matrix_linear_row", "matrix.linear_row"),
                ("matrix_linear_row_no_bias", "matrix.linear_row_no_bias"),
                ("matrix_rms_norm_rows", "matrix.rms_norm_rows"),
                ("matrix_layer_norm_rows", "matrix.layer_norm_rows"),
                ("matrix_from_bytes_f32_le", "matrix.from_bytes_f32_le"),
                ("matrix_from_bytes_f16_le", "matrix.from_bytes_f16_le"),
                ("matrix_split_cols_even", "matrix.split_cols_even"),
                ("matrix_concat_cols", "matrix.concat_cols"),
                ("matrix_concat_cols_many", "matrix.concat_cols_many"),
            ],
        ),
        (include_str!("../../../../stdlib/string_concat.almd"), &[("__str_concat", "__str_concat")]),
        (include_str!("../../../../stdlib/list_concat.almd"), &[("__list_concat", "__list_concat"), ("__list_concat_rc", "__list_concat_rc")]),
        (include_str!("../../../../stdlib/bytes_skip.almd"), &[("bytes_skip_length_prefixed_le", "bytes.skip_length_prefixed_le")]),
        (include_str!("../../../../stdlib/bytes_lenprefix.almd"), &[("bytes_read_length_prefixed_strings_le", "bytes.read_length_prefixed_strings_le")]),
        (include_str!("../../../../stdlib/bytes_string.almd"), &[("bytes_to_string_lossy", "bytes.to_string_lossy"), ("bytes_read_string_at", "bytes.read_string_at"), ("bytes_read_string_be", "bytes.read_string_be")]),
        (include_str!("../../../../stdlib/json_scalar.almd"), &[("json_null", "json.null"), ("json_from_int", "json.from_int"), ("json_from_bool", "json.from_bool"), ("json_from_float", "json.from_float"), ("json_as_int", "json.as_int"), ("json_as_float", "json.as_float"), ("json_as_bool", "json.as_bool")]),
        (include_str!("../../../../stdlib/json_string.almd"), &[("json_from_string", "json.from_string"), ("json_as_string", "json.as_string")]),
        (include_str!("../../../../stdlib/json_parse.almd"), &[("json_parse", "json.parse")]),
        (include_str!("../../../../stdlib/json_ctor.almd"), &[("json_object", "json.object"), ("json_array", "json.array"), ("json_stringify", "json.stringify")]),
        (include_str!("../../../../stdlib/json_path.almd"), &[("json_path_root", "json.root"), ("json_path_field", "json.field"), ("json_path_index", "json.index"), ("json_path_get", "json.get_path"), ("json_path_set", "json.set_path"), ("json_path_remove", "json.remove_path")]),
        (include_str!("../../../../stdlib/result_collect.almd"), &[("result_collect", "result.collect"), ("result_partition", "result.partition"), ("result_collect_map", "result.collect_map")]),
        (include_str!("../../../../stdlib/value_utils.almd"), &[("value_pick", "value.pick"), ("value_omit", "value.omit"), ("value_to_camel_case", "value.to_camel_case"), ("value_to_snake_case", "value.to_snake_case")]),
        (include_str!("../../../../stdlib/http_url_decode.almd"), &[("http_url_decode", "http.url_decode")]),
        (include_str!("../../../../stdlib/datetime_parse_iso.almd"), &[("datetime_parse_iso", "datetime.parse_iso")]),
        (include_str!("../../../../stdlib/http_response.almd"), &[("http_response", "http.response"), ("http_json", "http.json"), ("http_redirect", "http.redirect"), ("http_with_headers", "http.with_headers"), ("http_status", "http.status"), ("http_body", "http.body"), ("http_set_header", "http.set_header"), ("http_get_header", "http.get_header")]),
        (include_str!("../../../../stdlib/string_capitalize.almd"), &[("string_capitalize", "string.capitalize")]),
        (include_str!("../../../../stdlib/uint8_convert.almd"), &[("uint8_to_int8", "uint8.to_int8"), ("uint8_to_int16", "uint8.to_int16"), ("uint8_to_int32", "uint8.to_int32"), ("uint8_to_int64", "uint8.to_int64"), ("uint8_to_uint16", "uint8.to_uint16"), ("uint8_to_uint32", "uint8.to_uint32"), ("uint8_to_uint64", "uint8.to_uint64"), ("uint8_to_float32", "uint8.to_float32"), ("uint8_to_float64", "uint8.to_float64"), ("uint8_to_string", "uint8.to_string")]),
        (include_str!("../../../../stdlib/uint16_convert.almd"), &[("uint16_to_int8", "uint16.to_int8"), ("uint16_to_int16", "uint16.to_int16"), ("uint16_to_int32", "uint16.to_int32"), ("uint16_to_int64", "uint16.to_int64"), ("uint16_to_uint8", "uint16.to_uint8"), ("uint16_to_uint32", "uint16.to_uint32"), ("uint16_to_uint64", "uint16.to_uint64"), ("uint16_to_float32", "uint16.to_float32"), ("uint16_to_float64", "uint16.to_float64"), ("uint16_to_string", "uint16.to_string")]),
        (include_str!("../../../../stdlib/uint32_convert.almd"), &[("uint32_to_int8", "uint32.to_int8"), ("uint32_to_int16", "uint32.to_int16"), ("uint32_to_int32", "uint32.to_int32"), ("uint32_to_int64", "uint32.to_int64"), ("uint32_to_uint8", "uint32.to_uint8"), ("uint32_to_uint16", "uint32.to_uint16"), ("uint32_to_uint64", "uint32.to_uint64"), ("uint32_to_float32", "uint32.to_float32"), ("uint32_to_float64", "uint32.to_float64"), ("uint32_to_string", "uint32.to_string")]),
        (include_str!("../../../../stdlib/uint64_convert.almd"), &[("uint64_to_int8", "uint64.to_int8"), ("uint64_to_int16", "uint64.to_int16"), ("uint64_to_int32", "uint64.to_int32"), ("uint64_to_int64", "uint64.to_int64"), ("uint64_to_uint8", "uint64.to_uint8"), ("uint64_to_uint16", "uint64.to_uint16"), ("uint64_to_uint32", "uint64.to_uint32"), ("uint64_to_float32", "uint64.to_float32"), ("uint64_to_float64", "uint64.to_float64"), ("uint64_to_string", "uint64.to_string")]),
        (include_str!("../../../../stdlib/string_split.almd"), &[("string_split", "string.split")]),
        (include_str!("../../../../stdlib/string_chars.almd"), &[("string_chars", "string.chars")]),
        (include_str!("../../../../stdlib/string_lines.almd"), &[("string_lines", "string.lines")]),
        (include_str!("../../../../stdlib/string_join.almd"), &[("string_join", "string.join"), ("list_join", "list.join")]),
        (
            include_str!("../../../../stdlib/bytes_core.almd"),
            &[("bytes_to_string", "bytes.to_string"), ("bytes_map_each", "bytes.map_each"), 
                ("bytes_from_string", "bytes.from_string"),
                ("bytes_len", "bytes.len"),
                ("bytes_is_empty", "bytes.is_empty"),
                ("bytes_get_or", "bytes.get_or"),
                ("bytes_new", "bytes.new"),
                ("bytes_concat", "bytes.concat"),
                ("bytes_reverse", "bytes.reverse"),
                ("bytes_repeat", "bytes.repeat"),
                ("bytes_starts_with", "bytes.starts_with"),
                ("bytes_ends_with", "bytes.ends_with"),
                ("bytes_slice", "bytes.slice"),
                ("bytes_cmp", "bytes.cmp"),
                ("bytes_set", "bytes.set"),
                ("bytes_append", "bytes.append"),
                ("bytes_pad_left", "bytes.pad_left"),
                ("bytes_pad_right", "bytes.pad_right"),
                ("bytes_from_list", "bytes.from_list"),
                ("bytes_to_list", "bytes.to_list"),
                ("bytes_skip", "bytes.skip"),
                ("bytes_contains", "bytes.contains"),
                ("bytes_xor", "bytes.xor"),
                ("bytes_insert", "bytes.insert"),
                ("bytes_remove_at", "bytes.remove_at"),
                ("bytes_read_u16_be", "bytes.read_u16_be"),
                ("bytes_read_i16_be", "bytes.read_i16_be"),
                ("bytes_read_i16_le", "bytes.read_i16_le"),
                ("bytes_read_i32_be", "bytes.read_i32_be"),
                ("bytes_read_u8", "bytes.read_u8"),
                ("bytes_index", "bytes.index"),
                ("bytes_read_bool", "bytes.read_bool"),
                ("bytes_read_u16_le", "bytes.read_u16_le"),
                ("bytes_read_u32_be", "bytes.read_u32_be"),
                ("bytes_read_u32_le", "bytes.read_u32_le"),
                ("bytes_read_i32_le", "bytes.read_i32_le"),
                ("bytes_read_i64_be", "bytes.read_i64_be"),
                ("bytes_read_i64_le", "bytes.read_i64_le"),
                ("bytes_read_f64_be", "bytes.read_f64_be"),
                ("bytes_read_f64_le", "bytes.read_f64_le"),
                ("bytes_read_f32_be", "bytes.read_f32_be"),
                ("bytes_read_f32_le", "bytes.read_f32_le"),
                ("bytes_get", "bytes.get"),
                ("bytes_index_of", "bytes.index_of"),
                ("bytes_eof", "bytes.eof"),
                ("bytes_is_valid_utf8", "bytes.is_valid_utf8"),
            ],
        ),
        (
            include_str!("../../../../stdlib/int_to_float.almd"),
            &[
                ("int_to_float", "int.to_float"),
                ("int_to_float64", "int.to_float64"),
                ("int_to_float32", "int.to_float32"),
            ],
        ),
        (
            include_str!("../../../../stdlib/float_convert.almd"),
            &[
                ("float_to_int8", "float.to_int8"),
                ("float_to_int16", "float.to_int16"),
                ("float_to_int32", "float.to_int32"),
                ("float_to_uint8", "float.to_uint8"),
                ("float_to_uint16", "float.to_uint16"),
                ("float_to_uint32", "float.to_uint32"),
                ("float_to_int64", "float.to_int64"),
                ("float_to_uint64", "float.to_uint64"),
                ("float_to_float32", "float.to_float32"),
                ("float_from_float32", "float.from_float32"),
                ("float_to_float32_checked", "float.to_float32_checked"),
            ],
        ),
        (
            include_str!("../../../../stdlib/float_checked.almd"),
            &[
                ("float_to_int8_checked", "float.to_int8_checked"),
                ("float_to_int16_checked", "float.to_int16_checked"),
                ("float_to_int32_checked", "float.to_int32_checked"),
                ("float_to_uint8_checked", "float.to_uint8_checked"),
                ("float_to_uint16_checked", "float.to_uint16_checked"),
                ("float_to_uint32_checked", "float.to_uint32_checked"),
                ("float_to_int64_checked", "float.to_int64_checked"),
                ("float_to_uint64_checked", "float.to_uint64_checked"),
            ],
        ),
        (
            include_str!("../../../../stdlib/bytes_split.almd"),
            &[
                ("bytes_split", "bytes.split"),
                ("bytes_lines", "bytes.lines"),
                ("bytes_chunks", "bytes.chunks"),
            ],
        ),
        (
            include_str!("../../../../stdlib/bytes_mutate.almd"),
            &[
                ("bytes_set_u8", "bytes.set_u8"),
                ("bytes_set_at", "bytes.set_at"),
                ("bytes_set_u16_be", "bytes.set_u16_be"),
                ("bytes_set_u16_le", "bytes.set_u16_le"),
                ("bytes_set_i16_be", "bytes.set_i16_be"),
                ("bytes_set_i16_le", "bytes.set_i16_le"),
                ("bytes_set_u32_be", "bytes.set_u32_be"),
                ("bytes_set_u32_le", "bytes.set_u32_le"),
                ("bytes_set_i32_be", "bytes.set_i32_be"),
                ("bytes_set_i32_le", "bytes.set_i32_le"),
                ("bytes_set_i64_be", "bytes.set_i64_be"),
                ("bytes_set_i64_le", "bytes.set_i64_le"),
                ("bytes_fill", "bytes.fill"),
                ("bytes_clear", "bytes.clear"),
                ("bytes_set_f64_be", "bytes.set_f64_be"),
                ("bytes_set_f64_le", "bytes.set_f64_le"),
                ("bytes_set_f32_be", "bytes.set_f32_be"),
                ("bytes_set_f32_le", "bytes.set_f32_le"),
                ("bytes_copy_within", "bytes.copy_within"),
                ("bytes_copy_from", "bytes.copy_from"),
            ],
        ),
        (
            include_str!("../../../../stdlib/datetime_format.almd"),
            &[("datetime_to_iso", "datetime.to_iso"), ("datetime_format", "datetime.format")],
        ),
        (
            include_str!("../../../../stdlib/datetime_calendar.almd"),
            &[
                ("datetime_year", "datetime.year"),
                ("datetime_month", "datetime.month"),
                ("datetime_day", "datetime.day"),
                ("datetime_weekday", "datetime.weekday"),
                ("datetime_from_parts", "datetime.from_parts"),
            ],
        ),
        (
            include_str!("../../../../stdlib/datetime_arith.almd"),
            &[
                ("datetime_add_days", "datetime.add_days"),
                ("datetime_add_hours", "datetime.add_hours"),
                ("datetime_add_minutes", "datetime.add_minutes"),
                ("datetime_add_seconds", "datetime.add_seconds"),
                ("datetime_diff_seconds", "datetime.diff_seconds"),
                ("datetime_from_unix", "datetime.from_unix"),
                ("datetime_to_unix", "datetime.to_unix"),
                ("datetime_hour", "datetime.hour"),
                ("datetime_minute", "datetime.minute"),
                ("datetime_second", "datetime.second"),
                ("datetime_is_before", "datetime.is_before"),
                ("datetime_is_after", "datetime.is_after"),
            ],
        ),
        (
            include_str!("../../../../stdlib/float32_convert.almd"),
            &[
                ("float32_to_int8", "float32.to_int8"),
                ("float32_to_int16", "float32.to_int16"),
                ("float32_to_int32", "float32.to_int32"),
                ("float32_to_int64", "float32.to_int64"),
                ("float32_to_uint8", "float32.to_uint8"),
                ("float32_to_uint16", "float32.to_uint16"),
                ("float32_to_uint32", "float32.to_uint32"),
                ("float32_to_uint64", "float32.to_uint64"),
                ("float32_to_float64", "float32.to_float64"),
            ],
        ),
        (
            include_str!("../../../../stdlib/int8_convert.almd"),
            &[
                ("int8_to_int16", "int8.to_int16"),
                ("int8_to_int32", "int8.to_int32"),
                ("int8_to_int64", "int8.to_int64"),
                ("int8_to_uint8", "int8.to_uint8"),
                ("int8_to_uint16", "int8.to_uint16"),
                ("int8_to_uint32", "int8.to_uint32"),
                ("int8_to_uint64", "int8.to_uint64"),
                ("int8_to_float32", "int8.to_float32"),
                ("int8_to_float64", "int8.to_float64"),
                ("int8_to_string", "int8.to_string"),
            ],
        ),
        (
            include_str!("../../../../stdlib/int16_convert.almd"),
            &[
                ("int16_to_int8", "int16.to_int8"),
                ("int16_to_int32", "int16.to_int32"),
                ("int16_to_int64", "int16.to_int64"),
                ("int16_to_uint8", "int16.to_uint8"),
                ("int16_to_uint16", "int16.to_uint16"),
                ("int16_to_uint32", "int16.to_uint32"),
                ("int16_to_uint64", "int16.to_uint64"),
                ("int16_to_float32", "int16.to_float32"),
                ("int16_to_float64", "int16.to_float64"),
                ("int16_to_string", "int16.to_string"),
            ],
        ),
        (
            include_str!("../../../../stdlib/int32_convert.almd"),
            &[
                ("int32_to_int8", "int32.to_int8"),
                ("int32_to_int16", "int32.to_int16"),
                ("int32_to_int64", "int32.to_int64"),
                ("int32_to_uint8", "int32.to_uint8"),
                ("int32_to_uint16", "int32.to_uint16"),
                ("int32_to_uint32", "int32.to_uint32"),
                ("int32_to_uint64", "int32.to_uint64"),
                ("int32_to_float32", "int32.to_float32"),
                ("int32_to_float64", "int32.to_float64"),
                ("int32_to_string", "int32.to_string"),
            ],
        ),
        (
            include_str!("../../../../stdlib/hex_encode.almd"),
            &[("hex_encode", "hex.encode"), ("hex_encode_upper", "hex.encode_upper"), ("hex_decode", "hex.decode")],
        ),
        (
            include_str!("../../../../stdlib/base64_encode.almd"),
            &[("base64_encode", "base64.encode"), ("base64_encode_url", "base64.encode_url"), ("base64_decode", "base64.decode"), ("base64_decode_url", "base64.decode_url")],
        ),
        (
            include_str!("../../../../stdlib/int_rotate.almd"),
            &[("int_rotate_left", "int.rotate_left"), ("int_rotate_right", "int.rotate_right")],
        ),
        (
            include_str!("../../../../stdlib/float_bits.almd"),
            &[
                ("float_to_bits", "float.to_bits"),
                ("int_bits_to_float", "int.bits_to_float"),
                ("int_bits_to_f32", "int.bits_to_f32"),
            ],
        ),
        (include_str!("../../../../stdlib/fan_map.almd"), &[("fan_map", "fan.map"), ("fan_map_is", "fan.map_is"), ("fan_map_ss", "fan.map_ss"), ("fan_map_si", "fan.map_si")]),
        // The self-hosted regex ENGINE (Stage 1: is_match/full_match — v0's
        // runtime regex ported quirk-for-quirk; see stdlib/regex_engine.almd).
        (include_str!("../../../../stdlib/regex_engine.almd"), &[("regex_is_match", "regex.is_match"), ("regex_full_match", "regex.full_match"), ("regex_find", "regex.find"), ("regex_find_all", "regex.find_all"), ("regex_replace", "regex.replace"), ("regex_replace_first", "regex.replace_first"), ("regex_split", "regex.split"), ("regex_captures", "regex.captures")]),
        (include_str!("../../../../stdlib/list_to_string.almd"), &[("list_to_string", "list.to_string")]),
        (include_str!("../../../../stdlib/list_to_string_ll.almd"), &[("list_to_string_ll", "list.to_string_ll"), ("list_to_string_llf", "list.to_string_llf")]),
        (include_str!("../../../../stdlib/list_to_string_b.almd"), &[("list_to_string_b", "list.to_string_b")]),
        (include_str!("../../../../stdlib/list_to_string_s.almd"), &[("list_to_string_s", "list.to_string_s")]),
        (include_str!("../../../../stdlib/list_to_string_f.almd"), &[("list_to_string_f", "list.to_string_f")]),
        // `${Option[T]}` → `some(<T>)` / `none`, per element type (mirrors the List family).
        (include_str!("../../../../stdlib/option_to_string.almd"), &[("option_to_string", "option.to_string")]),
        (include_str!("../../../../stdlib/option_to_string_s.almd"), &[("option_to_string_s", "option.to_string_s")]),
        (include_str!("../../../../stdlib/option_to_string_li.almd"), &[("option_to_string_li", "option.to_string_li")]),
        (include_str!("../../../../stdlib/option_to_string_oi.almd"), &[("option_to_string_oi", "option.to_string_oi")]),
        (include_str!("../../../../stdlib/option_to_string_ls.almd"), &[("option_to_string_ls", "option.to_string_ls")]),
        (include_str!("../../../../stdlib/option_to_string_msi.almd"), &[("option_to_string_msi", "option.to_string_msi")]),
        (include_str!("../../../../stdlib/option_to_string_lf.almd"), &[("option_to_string_lf", "option.to_string_lf")]),
        (include_str!("../../../../stdlib/option_to_string_nested.almd"), &[("option_to_string_ob", "option.to_string_ob"), ("option_to_string_os", "option.to_string_os"), ("option_to_string_ri", "option.to_string_ri"), ("option_to_string_rs", "option.to_string_rs"), ("option_to_string_lb", "option.to_string_lb"), ("option_to_string_ooi", "option.to_string_ooi"), ("option_to_string_ooli", "option.to_string_ooli"), ("option_to_string_rli", "option.to_string_rli")]),
        (include_str!("../../../../stdlib/option_to_string_f.almd"), &[("option_to_string_f", "option.to_string_f")]),
        (include_str!("../../../../stdlib/option_to_string_b.almd"), &[("option_to_string_b", "option.to_string_b")]),
        (include_str!("../../../../stdlib/result_to_string.almd"), &[("result_to_string", "result.to_string"), ("result_to_string_ss", "result.to_string_ss"), ("result_to_string_li", "result.to_string_li"), ("result_to_string_ls", "result.to_string_ls"), ("result_to_string_b", "result.to_string_b"), ("result_to_string_lb", "result.to_string_lb"), ("result_to_string_oi", "result.to_string_oi"), ("result_to_string_os", "result.to_string_os"), ("result_to_string_ri", "result.to_string_ri"), ("result_to_string_f", "result.to_string_f"), ("result_to_string_oli", "result.to_string_oli"), ("result_to_string_lf", "result.to_string_lf"), ("result_to_string_osl", "result.to_string_osl"), ("result_to_string_msi", "result.to_string_msi")]),
        (include_str!("../../../../stdlib/set_to_string.almd"), &[("set_to_string", "set.to_string")]),
        (include_str!("../../../../stdlib/set_to_string_s.almd"), &[("set_to_string_s", "set.to_string_s")]),
        (include_str!("../../../../stdlib/map_to_string.almd"), &[("map_to_string", "map.to_string"), ("map_to_string_ss", "map.to_string_ss")]),
        (include_str!("../../../../stdlib/bytes_rawptr.almd"), &[("bytes_as_ptr", "bytes.as_ptr"), ("bytes_as_mut_ptr", "bytes.as_mut_ptr"), ("bytes_from_raw_ptr", "bytes.from_raw_ptr"), ("bytes_copy_to_ptr", "bytes.copy_to_ptr")]),
        (include_str!("../../../../stdlib/list_to_string_lo.almd"), &[("list_to_string_lo", "list.to_string_lo")]),
        (include_str!("../../../../stdlib/list_to_string_lr.almd"), &[("list_to_string_lr", "list.to_string_lr")]),
        (include_str!("../../../../stdlib/map_if.almd"), &[("map_from_list_if", "map.from_list_if"), ("map_to_string_if", "map.to_string_if")]),
        // Single-value compound formatters for record/tuple Display (the `${record}`/`${tuple}`
        // form): a Float field drops the trailing ".0" like a List[Float] element, a String field
        // is quoted+escaped like a List[String] element. Both reuse the proven list-element logic.
        (include_str!("../../../../stdlib/float_to_string_compound.almd"), &[("float_to_string_compound", "float.to_string_compound")]),
        (include_str!("../../../../stdlib/string_quote.almd"), &[("string_quote", "string.quote")]),
        (include_str!("../../../../stdlib/list_len.almd"), &[("list_len", "list.len"), ("list_length", "list.length")]),
        (include_str!("../../../../stdlib/list_flatten.almd"), &[("list_flatten", "list.flatten"), ("list_flatten_rc", "list.flatten_rc")]),
        (include_str!("../../../../stdlib/list_chunk.almd"), &[("list_chunk", "list.chunk"), ("list_windows", "list.windows"), ("list_window", "list.window"), ("list_chunk_str", "list.chunk_str"), ("list_windows_str", "list.windows_str"), ("list_window_str", "list.window_str")]),
        (include_str!("../../../../stdlib/result_core.almd"), &[("result_is_ok", "result.is_ok"), ("result_is_err", "result.is_err"), ("result_unwrap_or", "result.unwrap_or"), ("result_to_option", "result.to_option"), ("result_to_list", "result.to_list"), ("result_zip", "result.zip"), ("result_is_ok_h", "result.is_ok_h"), ("result_is_err_h", "result.is_err_h")]),
        (include_str!("../../../../stdlib/option_collect.almd"), &[("option_collect", "option.collect")]),
        (include_str!("../../../../stdlib/option_collect_map.almd"), &[("option_collect_map", "option.collect_map")]),
        (include_str!("../../../../stdlib/testing_assert.almd"), &[("testing_assert_gt", "testing.assert_gt"), ("testing_assert_lt", "testing.assert_lt"), ("testing_assert_approx", "testing.assert_approx"), ("testing_assert_contains", "testing.assert_contains"), ("testing_assert_some", "testing.assert_some"), ("testing_assert_ok", "testing.assert_ok")]),
        (include_str!("../../../../stdlib/option_map.almd"), &[("option_map", "option.map"), ("option_map_h", "option.map_h"), ("option_filter_h", "option.filter_h"), ("option_flatten_h", "option.flatten_h"), ("option_unwrap_or_else_h", "option.unwrap_or_else_h"), ("option_filter", "option.filter"), ("option_flat_map", "option.flat_map"), ("option_unwrap_or_else", "option.unwrap_or_else"), ("option_or_else", "option.or_else"), ("option_to_result", "option.to_result"), ("option_to_result_h", "option.to_result_h"), ("option_flatten", "option.flatten"), ("option_zip", "option.zip")]),
        (include_str!("../../../../stdlib/result_map.almd"), &[("result_map", "result.map"), ("result_flat_map", "result.flat_map"), ("result_to_err_option", "result.to_err_option"), ("result_unwrap_or_else", "result.unwrap_or_else"), ("result_map_err", "result.map_err"), ("result_filter", "result.filter"), ("result_or_else", "result.or_else"), ("result_flatten", "result.flatten")]),
        (include_str!("../../../../stdlib/string_to_int.almd"), &[("string_to_int", "int.parse"), ("int_from_hex", "int.from_hex")]),
        (include_str!("../../../../stdlib/list_is_empty.almd"), &[("list_is_empty", "list.is_empty")]),
        (include_str!("../../../../stdlib/list_sum.almd"), &[("list_sum", "list.sum")]),
        (include_str!("../../../../stdlib/list_sort.almd"), &[("list_sort", "list.sort"), ("list_sort_str", "list.sort_str"), ("list_min_str", "list.min_str"), ("list_max_str", "list.max_str")]),
        (include_str!("../../../../stdlib/list_sort_float.almd"), &[("list_sort_float", "list.sort_float")]),
        (include_str!("../../../../stdlib/list_fold_float.almd"), &[("list_max_float", "list.max_float"), ("list_min_float", "list.min_float")]),
        (
            include_str!("../../../../stdlib/map_ivh.almd"),
            &[("map_new_ivh", "map.new_ivh"), ("map_set_ivh", "map.set_ivh"), ("map_eq_ivh", "map.eq_ivh"), ("map_from_list_ivh", "map.from_list_ivh"), ("map_to_string_ivh", "map.to_string_ivh"), ("map_len_ivh", "map.len_ivh")],
        ),
        (
            include_str!("../../../../stdlib/map_hval.almd"),
            &[("map_new_hval", "map.new_hval"), ("map_set_hval", "map.set_hval"), ("map_eq_hval", "map.eq_hval"), ("map_from_list_hval", "map.from_list_hval"), ("map_to_string_hval", "map.to_string_hval"), ("list_to_string_lmh", "list.to_string_lmh"), ("map_len_hval", "map.len_hval"), ("map_contains_hval", "map.contains_hval"), ("map_get_hval", "map.get_hval"), ("list_group_by", "list.group_by")],
        ),
        (include_str!("../../../../stdlib/list_sortby_float.almd"), &[("list_sort_by_float", "list.sort_by_float"), ("list_sort_by_float_rc", "list.sort_by_float_rc")]),
        (include_str!("../../../../stdlib/list_unique.almd"), &[("list_unique", "list.unique")]),
        (include_str!("../../../../stdlib/list_dedup.almd"), &[("list_dedup", "list.dedup")]),
        (
            include_str!("../../../../stdlib/list_intersperse.almd"),
            &[("list_intersperse", "list.intersperse")],
        ),
        (
            include_str!("../../../../stdlib/int_wrap.almd"),
            &[
                ("int_wrap_add", "int.wrap_add"),
                ("int_wrap_mul", "int.wrap_mul"),
                ("int_to_u32", "int.to_u32"),
                ("int_to_u8", "int.to_u8"),
            ],
        ),
        (
            include_str!("../../../../stdlib/int_sized.almd"),
            &[
                ("int_to_int8", "int.to_int8"),
                ("int_to_int16", "int.to_int16"),
                ("int_to_int32", "int.to_int32"),
                ("int_to_int64", "int.to_int64"),
                ("int_to_int8_saturating", "int.to_int8_saturating"),
                ("int_to_int16_saturating", "int.to_int16_saturating"),
                ("int_to_int32_saturating", "int.to_int32_saturating"),
                ("int_to_uint64", "int.to_uint64"),
                ("int_from_int64", "int.from_int64"),
                ("int_from_uint64", "int.from_uint64"),
                ("int_to_uint8", "int.to_uint8"),
                ("int_to_uint16", "int.to_uint16"),
                ("int_to_uint32", "int.to_uint32"),
                ("int_from_int8", "int.from_int8"),
                ("int_from_int16", "int.from_int16"),
                ("int_from_int32", "int.from_int32"),
                ("int_from_uint8", "int.from_uint8"),
                ("int_from_uint16", "int.from_uint16"),
                ("int_from_uint32", "int.from_uint32"),
                ("int_to_uint8_saturating", "int.to_uint8_saturating"),
                ("int_to_uint16_saturating", "int.to_uint16_saturating"),
                ("int_to_uint32_saturating", "int.to_uint32_saturating"),
                ("int_to_uint64_saturating", "int.to_uint64_saturating"),
            ],
        ),
        (
            include_str!("../../../../stdlib/int_checked.almd"),
            &[
                ("int_to_int8_checked", "int.to_int8_checked"),
                ("int_to_int16_checked", "int.to_int16_checked"),
                ("int_to_int32_checked", "int.to_int32_checked"),
                ("int_to_uint8_checked", "int.to_uint8_checked"),
                ("int_to_uint16_checked", "int.to_uint16_checked"),
                ("int_to_uint32_checked", "int.to_uint32_checked"),
                ("int_to_uint64_checked", "int.to_uint64_checked"),
                ("int_to_float32_checked", "int.to_float32_checked"),
            ],
        ),
        (
            include_str!("../../../../stdlib/string_mutate.almd"),
            &[("string_clear", "string.clear")],
        ),
        (
            include_str!("../../../../stdlib/float_saturating.almd"),
            &[
                ("float_to_int8_saturating", "float.to_int8_saturating"),
                ("float_to_int16_saturating", "float.to_int16_saturating"),
                ("float_to_int32_saturating", "float.to_int32_saturating"),
                ("float_to_int64_saturating", "float.to_int64_saturating"),
                ("float_to_uint8_saturating", "float.to_uint8_saturating"),
                ("float_to_uint16_saturating", "float.to_uint16_saturating"),
                ("float_to_uint32_saturating", "float.to_uint32_saturating"),
                ("float_to_uint64_saturating", "float.to_uint64_saturating"),
            ],
        ),
        (include_str!("../../../../stdlib/string_slice.almd"), &[("string_slice", "string.slice")]),
        (include_str!("../../../../stdlib/string_slice2.almd"), &[("string_slice2", "string.slice2")]),
        (include_str!("../../../../stdlib/string_to_lower.almd"), &[("string_to_lower", "string.to_lower")]),
        (include_str!("../../../../stdlib/string_to_upper.almd"), &[("string_to_upper", "string.to_upper")]),
        (include_str!("../../../../stdlib/float_parse.almd"), &[("float_parse", "float.parse")]),
        (include_str!("../../../../stdlib/list_enumerate.almd"), &[("list_enumerate_str", "list.enumerate_str")]),
        (include_str!("../../../../stdlib/list_find_int_str.almd"), &[("list_find_int_str", "list.find_int_str")]),
        (
            include_str!("../../../../stdlib/string_is_digit.almd"),
            &[("string_is_digit", "string.is_digit")],
        ),
        (
            include_str!("../../../../stdlib/string_from_codepoint.almd"),
            &[("string_from_codepoint", "string.from_codepoint")],
        ),
        (
            include_str!("../../../../stdlib/string_codepoint.almd"),
            &[("string_codepoint", "string.codepoint")],
        ),
        (
            include_str!("../../../../stdlib/string_take_drop.almd"),
            &[
                ("string_take", "string.take"),
                ("string_take_end", "string.take_end"),
                ("string_drop", "string.drop"),
                ("string_drop_end", "string.drop_end"),
            ],
        ),
        (
            include_str!("../../../../stdlib/string_to_bytes.almd"),
            &[("string_to_bytes", "string.to_bytes")],
        ),
        (
            include_str!("../../../../stdlib/string_from_bytes_self.almd"),
            &[("string_from_bytes", "string.from_bytes")],
        ),
        (
            include_str!("../../../../stdlib/string_first_last.almd"),
            &[
                ("string_first", "string.first"), ("string_last", "string.last"),
                ("string_char_at", "string.get"),
                ("string_strip_prefix", "string.strip_prefix"),
                ("string_strip_suffix", "string.strip_suffix"),
                ("string_is_whitespace", "string.is_whitespace"),
            ],
        ),
        (
            include_str!("../../../../stdlib/string_trim.almd"),
            &[
                ("string_trim", "string.trim"),
                ("string_trim_start", "string.trim_start"),
                ("string_trim_end", "string.trim_end"),
            ],
        ),
        (include_str!("../../../../stdlib/string_reverse.almd"), &[("string_reverse", "string.reverse")]),
        (
            include_str!("../../../../stdlib/string_replace.almd"),
            &[
                ("string_replace", "string.replace"),
                ("string_replace_first", "string.replace_first"),
            ],
        ),
        (
            include_str!("../../../../stdlib/string_pad.almd"),
            &[("string_pad_start", "string.pad_start"), ("string_pad_end", "string.pad_end")],
        ),
        (include_str!("../../../../stdlib/list_get_or.almd"), &[("list_get_or", "list.get_or")]),
        (include_str!("../../../../stdlib/list_get_or_str.almd"), &[("list_get_or_str", "list.get_or_str")]),
        (
            include_str!("../../../../stdlib/int_bitcount.almd"),
            &[
                ("int_pop_count", "int.pop_count"),
                ("int_count_trailing_zeros", "int.count_trailing_zeros"),
                ("int_count_leading_zeros", "int.count_leading_zeros"),
                ("int_bit_width", "int.bit_width"),
                ("int_log2_floor", "int.log2_floor"),
                ("int_log2_ceil", "int.log2_ceil"),
                ("int_next_power_of_two", "int.next_power_of_two"),
                ("int_prev_power_of_two", "int.prev_power_of_two"),
            ],
        ),
        (
            include_str!("../../../../stdlib/int_bits.almd"),
            &[
                ("int_band", "int.band"),
                ("int_bor", "int.bor"),
                ("int_bxor", "int.bxor"),
                ("int_bshl", "int.bshl"),
                ("int_bshr", "int.bshr"),
                ("int_bnot", "int.bnot"),
                ("int_byte_swap", "int.byte_swap"),
                ("int_bit_reverse", "int.bit_reverse"),
            ],
        ),
        (include_str!("../../../../stdlib/int_hex.almd"), &[("int_to_hex", "int.to_hex")]),
        (
            include_str!("../../../../stdlib/int_scalar.almd"),
            &[
                ("int_abs", "int.abs"),
                ("int_min", "int.min"),
                ("int_max", "int.max"),
                ("int_clamp", "int.clamp"),
            ],
        ),
        (
            include_str!("../../../../stdlib/list_get.almd"),
            &[("list_get", "list.get"), ("list_first", "list.first"), ("list_last", "list.last")],
        ),
        (
            include_str!("../../../../stdlib/list_search.almd"),
            &[
                ("list_contains", "list.contains"),
                ("list_index_of", "list.index_of"),
                ("list_binary_search", "list.binary_search"),
            ],
        ),
        (include_str!("../../../../stdlib/list_reverse.almd"), &[("list_reverse", "list.reverse")]),
        (
            include_str!("../../../../stdlib/list_make.almd"),
            &[("list_range", "list.range"), ("list_repeat", "list.repeat"), ("list_repeat_rc", "list.repeat_rc"), ("list_with_capacity", "list.with_capacity")],
        ),
        (
            include_str!("../../../../stdlib/list_take_drop.almd"),
            &[
                ("list_take", "list.take"),
                ("list_drop", "list.drop"),
                ("list_slice", "list.slice"),
            ],
        ),
        (include_str!("../../../../stdlib/list_pop.almd"), &[("list_pop", "list.pop")]),
        (
            include_str!("../../../../stdlib/list_fold.almd"),
            &[
                ("list_product", "list.product"),
                ("list_max", "list.max"),
                ("list_min", "list.min"),
            ],
        ),
        (
            include_str!("../../../../stdlib/string_search.almd"),
            &[
                ("string_starts_with", "string.starts_with"),
                ("string_ends_with", "string.ends_with"),
                ("string_contains", "string.contains"),
                ("string_count", "string.count"),
                ("string_index_of", "string.index_of"),
                ("string_last_index_of", "string.last_index_of"),
            ],
        ),
    ]
}
