//! Generates `matrix_desugar_gen.rs`: the reverse of the `@rewrite` fusion
//! rules in `stdlib/matrix.almd`. For each rule `from => to` (un-fused tree =>
//! fused op), emit `to_op + args => from-tree IR`, so a target without a native
//! arm for a fused op can rebuild and emit the primitive composition instead of
//! panicking (ICE). Same single source of truth as the egg fusion rules and the
//! shared `fusion_parse.rs` parser — one `@rewrite` declaration now drives
//! fusion (forward) AND desugar (reverse). Adding a fusion op can never again
//! leave a target ICE-ing: if it has an `@rewrite`, it has a desugar.

#[path = "fusion_parse.rs"]
mod fusion_parse;

use fusion_parse::{extract_rewrites, Pat};
use std::path::Path;

pub fn generate(workspace_root: &Path, out_dir: &Path) {
    let stdlib_path = workspace_root.join("stdlib/matrix.almd");
    println!("cargo:rerun-if-changed={}", stdlib_path.display());
    let src = std::fs::read_to_string(&stdlib_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {}", stdlib_path.display(), e));
    let decls = extract_rewrites(&src);

    let mut out = String::new();
    out.push_str("// @generated by buildscript/matrix_desugar.rs from stdlib/matrix.almd\n");
    out.push_str("// @rewrite attributes — DO NOT EDIT. The reverse of the fusion rules:\n");
    out.push_str("// fused op + args -> the un-fused primitive IR, so any target lacking a\n");
    out.push_str("// native arm emits the composition instead of ICE-ing.\n\n");
    out.push_str("fn mk_mx(func: &str, args: Vec<IrExpr>) -> IrExpr {\n");
    out.push_str("    IrExpr {\n");
    out.push_str("        kind: IrExprKind::Call {\n");
    out.push_str("            target: CallTarget::Module { module: sym(\"matrix\"), func: sym(func), def_id: None },\n");
    out.push_str("            args,\n");
    out.push_str("            type_args: vec![],\n");
    out.push_str("        },\n");
    out.push_str("        ty: Ty::Matrix,\n");
    out.push_str("        span: None,\n");
    out.push_str("        def_id: None,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("/// Reverse of an `@rewrite` fusion: a fused matrix op plus its args -> the\n");
    out.push_str("/// primitive composition IR (the rule's `from`). `None` for ops with no\n");
    out.push_str("/// `@rewrite` rule. Every captured arg is reused by clone; intermediate\n");
    out.push_str("/// nodes are matrix-typed (matrix ops return Matrix).\n");
    out.push_str("pub(super) fn desugar_matrix_fusion(method: &str, args: &[IrExpr]) -> Option<IrExpr> {\n");
    out.push_str("    match method {\n");
    // Several @rewrite rules can share one `to` (e.g. `scale` on either matmul
    // operand both fuse to `mul_scaled`). Their `from`s are equivalent by
    // construction — both reduce to the same fused op — so one desugar arm
    // suffices. Keep the first; skipping the rest avoids an unreachable arm.
    let mut seen: Vec<String> = Vec::new();
    for decl in &decls {
        let (to_func, caps) = match &decl.to {
            Pat::Call { func, children } => {
                let caps: Vec<String> = children
                    .iter()
                    .map(|c| match c {
                        Pat::Capture(n) => n.clone(),
                        _ => panic!(
                            "@rewrite {}: `to` must be a flat fused call with only capture args",
                            decl.name
                        ),
                    })
                    .collect();
                (func.clone(), caps)
            }
            _ => panic!("@rewrite {}: `to` must be a `matrix.<fused>(...)` call", decl.name),
        };
        if seen.contains(&to_func) {
            continue;
        }
        seen.push(to_func.clone());
        let body = emit_from(&decl.from, &caps, &decl.name);
        out.push_str(&format!(
            "        \"{}\" if args.len() == {} => Some({}),\n",
            to_func,
            caps.len(),
            body
        ));
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    let out_path = out_dir.join("matrix_desugar_gen.rs");
    std::fs::write(&out_path, out)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", out_path.display(), e));
}

/// Emit a Rust expression building the un-fused IR for `from`: each `?cap` maps
/// to `args[i].clone()` (i = its position in the fused op's arg list), each
/// `matrix.f(..)` to `mk_mx("f", vec![..])`.
fn emit_from(pat: &Pat, caps: &[String], rule: &str) -> String {
    match pat {
        Pat::Capture(name) => {
            let idx = caps.iter().position(|c| c == name).unwrap_or_else(|| {
                panic!("@rewrite {rule}: capture `?{name}` in `from` is not bound by `to`")
            });
            format!("args[{idx}usize].clone()")
        }
        Pat::Call { func, children } => {
            let kids: Vec<String> = children.iter().map(|c| emit_from(c, caps, rule)).collect();
            format!("mk_mx(\"{}\", vec![{}])", func, kids.join(", "))
        }
    }
}
