use std::fs;
use std::path::Path;

pub fn generate(workspace_root: &Path, out_dir: &Path) {
    let rust_dir = workspace_root.join("runtime/rs/src");
    if !rust_dir.exists() {
        return;
    }

    let mut rust_entries: Vec<_> = fs::read_dir(&rust_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "rs"))
        .filter(|e| e.file_name() != "lib.rs")
        .collect();
    rust_entries.sort_by_key(|e| e.file_name());

    let mut rust_out = String::new();
    rust_out.push_str("// AUTO-GENERATED by build.rs from runtime/rs/src/ — DO NOT EDIT\n\n");
    rust_out.push_str("pub const RUST_RUNTIME_MODULES: &[(&str, &str)] = &[\n");
    for entry in &rust_entries {
        let stem = entry
            .path()
            .file_stem()
            .unwrap()
            .to_str()
            .unwrap()
            .to_string();
        let content = fs::read_to_string(entry.path()).unwrap();
        rust_out.push_str(&format!("    (\"{stem}\", {content:?}),\n"));
    }
    rust_out.push_str("];\n\n");

    // Auto-extract inter-module dependencies by scanning each module's
    // source for `almide_rt_{other}_` references. No manual whitelist.
    let module_names: Vec<String> = rust_entries.iter().map(|e| {
        e.path().file_stem().unwrap().to_str().unwrap().to_string()
    }).collect();

    rust_out.push_str("/// Inter-module runtime dependencies, auto-extracted from source.\n");
    rust_out.push_str("/// If module A's source references `almide_rt_B_*`, A depends on B.\n");
    rust_out.push_str("pub const RUNTIME_DEPS: &[(&str, &[&str])] = &[\n");
    for entry in &rust_entries {
        let stem = entry.path().file_stem().unwrap().to_str().unwrap().to_string();
        let content = fs::read_to_string(entry.path()).unwrap();
        let mut deps: Vec<&str> = Vec::new();
        for other in &module_names {
            if *other == stem { continue; }
            let prefix = format!("almide_rt_{}_", other);
            if content.contains(&prefix) {
                deps.push(other);
            }
        }
        if !deps.is_empty() {
            rust_out.push_str(&format!("    (\"{}\", &[{}]),\n", stem,
                deps.iter().map(|d| format!("\"{}\"", d)).collect::<Vec<_>>().join(", ")));
        }
    }
    rust_out.push_str("];\n");

    fs::write(out_dir.join("rust_runtime.rs"), &rust_out).unwrap();

    // Auto-extract the runtime helpers whose LAST positional parameter is a generic
    // `F: Fn(...)` element fn (the value codec combinators — encode/decode list,
    // option, …). Their fn argument must stay a raw `impl Fn`, NOT the uniform
    // `Rc<dyn Fn>` closure value. Derived from the signatures themselves (no
    // hand-maintained allow-list) so a new codec combinator needs no codegen edit.
    let mut raw_fn_helpers: Vec<String> = Vec::new();
    for entry in &rust_entries {
        let content = fs::read_to_string(entry.path()).unwrap();
        raw_fn_helpers.extend(extract_raw_fn_last_arg_helpers(&content));
    }
    raw_fn_helpers.sort();
    raw_fn_helpers.dedup();

    let mut modes_out = String::new();
    modes_out.push_str("// AUTO-GENERATED by build.rs from runtime/rs/src/ — DO NOT EDIT\n\n");
    modes_out.push_str("/// Runtime helpers whose LAST positional argument is a generic `F: Fn(...)`\n");
    modes_out.push_str("/// element fn (value codec combinators) — extracted from the signatures.\n");
    modes_out.push_str("pub fn takes_raw_fn_last_arg(name: &str) -> bool {\n");
    if raw_fn_helpers.is_empty() {
        modes_out.push_str("    let _ = name;\n    false\n");
    } else {
        modes_out.push_str("    matches!(name,\n");
        for (i, h) in raw_fn_helpers.iter().enumerate() {
            let sep = if i + 1 < raw_fn_helpers.len() { " |" } else { "" };
            modes_out.push_str(&format!("        \"{}\"{}\n", h, sep));
        }
        modes_out.push_str("    )\n");
    }
    modes_out.push_str("}\n");
    fs::write(out_dir.join("runtime_fn_modes.rs"), &modes_out).unwrap();

    println!("cargo:rerun-if-changed={}", rust_dir.display());
}

/// Names of `pub fn`s whose declared generics include a `<G>: Fn(...)` bound and
/// whose LAST positional parameter has type exactly that generic `G`. These take a
/// raw `impl Fn` (monomorphized), not a `Rc<dyn Fn>` closure value.
fn extract_raw_fn_last_arg_helpers(content: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cursor = 0;
    while let Some(rel) = content[cursor..].find("pub fn ") {
        let name_start = cursor + rel + "pub fn ".len();
        let name_end = content[name_start..]
            .find(|c: char| !(c.is_alphanumeric() || c == '_'))
            .map(|i| name_start + i)
            .unwrap_or(content.len());
        let name = content[name_start..name_end].to_string();
        cursor = name_end;

        let rest = content[name_end..].trim_start();
        // Optional `<generics>` then `(params)`.
        let (generics, after) = if rest.starts_with('<') {
            match balanced(rest, '<', '>') {
                Some(end) => (&rest[1..end], rest[end + 1..].trim_start()),
                None => continue,
            }
        } else {
            ("", rest)
        };
        if !after.starts_with('(') {
            continue;
        }
        let params = match balanced(after, '(', ')') {
            Some(end) => &after[1..end],
            None => continue,
        };

        // Generics with a `Fn` bound: `F: Fn(...) -> _`.
        let fn_generics: Vec<&str> = split_top_level(generics)
            .into_iter()
            .filter_map(|g| {
                let g = g.trim();
                let colon = g.find(':')?;
                if g[colon + 1..].trim_start().starts_with("Fn") {
                    Some(g[..colon].trim())
                } else {
                    None
                }
            })
            .collect();
        if fn_generics.is_empty() {
            continue;
        }

        // Last param's type is exactly one of those Fn generics.
        if let Some(last) = split_top_level(params).last() {
            if let Some(colon) = last.rfind(':') {
                let ty = last[colon + 1..].trim();
                if fn_generics.contains(&ty) {
                    out.push(name);
                }
            }
        }
    }
    out
}

/// Index of the close delimiter matching the open at `s[0]` (`s` must start with
/// `open`), honoring nesting. The `>` in a `->` return arrow is NOT a closing angle
/// bracket (e.g. `<F: Fn(T) -> Value>`). Returns None if unbalanced.
fn balanced(s: &str, open: char, close: char) -> Option<usize> {
    let mut depth = 0i32;
    let mut prev = ' ';
    for (i, c) in s.char_indices() {
        if c == close && close == '>' && prev == '-' {
            prev = c;
            continue;
        }
        if c == open {
            depth += 1;
        } else if c == close {
            depth -= 1;
            if depth == 0 {
                return Some(i);
            }
        }
        prev = c;
    }
    None
}

/// Split by top-level commas, ignoring commas nested in `<>`, `()`, or `[]`. The
/// `>` in a `->` return arrow does not close an angle bracket.
fn split_top_level(s: &str) -> Vec<&str> {
    let mut parts = Vec::new();
    let mut depth = 0i32;
    let mut start = 0;
    let mut prev = ' ';
    for (i, c) in s.char_indices() {
        match c {
            '<' | '(' | '[' => depth += 1,
            '>' if prev == '-' => {}
            '>' | ')' | ']' => depth -= 1,
            ',' if depth == 0 => {
                parts.push(&s[start..i]);
                start = i + 1;
            }
            _ => {}
        }
        prev = c;
    }
    if !s[start..].trim().is_empty() {
        parts.push(&s[start..]);
    }
    parts
}
