use std::fs;
use std::path::Path;

pub fn generate(workspace_root: &Path, out_dir: &Path) {
    let rust_dir = workspace_root.join("runtime/rs/src");
    if !rust_dir.exists() {
        return;
    }

    let mut rust_entries: Vec<_> = fs::read_dir(&rust_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "rs"))
        .filter(|e| e.file_name() != "lib.rs")
        .collect();
    rust_entries.sort_by_key(|e| e.file_name());

    let mut rust_out = String::new();
    rust_out.push_str("// AUTO-GENERATED by build.rs from runtime/rs/src/ — DO NOT EDIT\n\n");
    rust_out.push_str("pub const RUST_RUNTIME_MODULES: &[(&str, &str)] = &[\n");
    for entry in &rust_entries {
        let stem = entry
            .path()
            .file_stem()
            .unwrap()
            .to_str()
            .unwrap()
            .to_string();
        let content = fs::read_to_string(entry.path()).unwrap();
        rust_out.push_str(&format!("    (\"{stem}\", {content:?}),\n"));
    }
    rust_out.push_str("];\n");

    fs::write(out_dir.join("rust_runtime.rs"), &rust_out).unwrap();

    println!("cargo:rerun-if-changed={}", rust_dir.display());
}
