//! Generate `stdlib_ret_ty.rs`: a minimal lookup from (module, func, arg_types)
//! to the return `Ty` for every stdlib function declared in `stdlib/defs/*.toml`.
//!
//! This gives `ConcretizeTypes` enough info to resolve Call return types
//! without hardcoding every stdlib signature in a match. It replaces the
//! whack-a-mole pattern of adding entries to `resolve_call_ret_ty` per
//! function encountered.
//!
//! ## Scope
//!
//! Return type strings from TOML are parsed with a very small grammar:
//!   - `Int`, `Float`, `Bool`, `String`, `Bytes`, `Matrix`, `Unit`
//!   - `List[T]`, `Option[T]`, `Result[T, E]`, `Map[K, V]`, `Set[T]`
//!   - `(T1, T2, ...)` tuple
//!   - Type variables matching `[A-Z]` or `[A-Z][A-Za-z0-9_]*` (for generics)
//!
//! When the return type mentions a type variable, we emit a post-processing
//! helper that substitutes it using arg positions (from TOML `params` list).

use serde::Deserialize;
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

#[derive(Deserialize, Debug)]
struct FnDef {
    #[serde(default)]
    params: Vec<Param>,
    #[serde(rename = "return", default)]
    ret: String,
    #[serde(default)]
    #[allow(dead_code)]
    type_params: Vec<String>,
}

#[derive(Deserialize, Debug)]
struct Param {
    name: String,
    #[serde(rename = "type")]
    ty: String,
}

pub fn generate(workspace_root: &Path, out_dir: &Path) {
    let defs_dir = workspace_root.join("stdlib/defs");
    let mut entries: Vec<(String, String, String, Vec<String>)> = Vec::new(); // (module, func, ret_ty_expr, param_tys)

    if let Ok(read) = fs::read_dir(&defs_dir) {
        for entry in read.flatten() {
            let path = entry.path();
            let Some(ext) = path.extension() else { continue };
            if ext != "toml" { continue }
            let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else { continue };
            let module = stem.to_string();

            let Ok(raw) = fs::read_to_string(&path) else { continue };
            #[derive(serde::Deserialize)]
            struct ModuleFile {
                #[serde(default)]
                #[allow(dead_code)]
                types: Vec<toml::Value>,
                #[serde(flatten)]
                functions: BTreeMap<String, FnDef>,
            }
            let Ok(mf) = toml::from_str::<ModuleFile>(&raw) else { continue };

            for (func, def) in mf.functions {
                if def.ret.is_empty() { continue }
                let param_tys: Vec<String> = def.params.iter().map(|p| p.ty.clone()).collect();
                entries.push((module.clone(), func, def.ret, param_tys));
            }
        }
    }

    entries.sort();

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs from stdlib/defs/*.toml — DO NOT EDIT\n");
    out.push_str("//\n");
    out.push_str("// Minimal stdlib return-type lookup for ConcretizeTypes pass.\n");
    out.push_str("// Returns a `Ty` with TypeVars that need to be substituted by\n");
    out.push_str("// the caller using the actual argument types.\n\n");
    out.push_str("use almide_lang::types::Ty;\n");
    out.push_str("use almide_lang::types::constructor::TypeConstructorId as TCI;\n");
    out.push_str("use almide_base::intern::sym;\n\n");
    out.push_str("/// Return-type template for a stdlib function. Type variables\n");
    out.push_str("/// (`Ty::TypeVar`) in the template refer to parameter type names.\n");
    out.push_str("pub struct StdlibSig {\n");
    out.push_str("    pub ret_ty: Ty,\n");
    out.push_str("    pub param_tys: &'static [&'static str],\n");
    out.push_str("}\n\n");
    out.push_str("pub fn lookup_stdlib_ret(module: &str, func: &str) -> Option<StdlibSig> {\n");
    out.push_str("    match (module, func) {\n");

    for (module, func, ret_ty_str, param_tys) in &entries {
        let Some(ret_expr) = parse_ty_to_rust(ret_ty_str) else { continue };
        let param_arr: Vec<String> = param_tys.iter().map(|t| format!("{:?}", t)).collect();
        out.push_str(&format!(
            "        ({:?}, {:?}) => Some(StdlibSig {{ ret_ty: {}, param_tys: &[{}] }}),\n",
            module, func, ret_expr, param_arr.join(", ")
        ));
    }

    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    let target = out_dir.join("stdlib_ret_ty.rs");
    fs::write(target, out).expect("write stdlib_ret_ty.rs");
}

/// Parse a TOML type string to a Rust expression building a `Ty`. Returns
/// None for constructs we don't model (complex Fn types, structural bounds).
fn parse_ty_to_rust(s: &str) -> Option<String> {
    let s = s.trim();
    // Scalars
    match s {
        "Int"     => return Some("Ty::Int".into()),
        "Float"   => return Some("Ty::Float".into()),
        "Bool"    => return Some("Ty::Bool".into()),
        "String"  => return Some("Ty::String".into()),
        "Bytes"   => return Some("Ty::Bytes".into()),
        "Matrix"  => return Some("Ty::Matrix".into()),
        "Unit"    => return Some("Ty::Unit".into()),
        "RawPtr"  => return Some("Ty::RawPtr".into()),
        "Never"   => return Some("Ty::Never".into()),
        "Value"   => return Some("Ty::Named(sym(\"Value\"), vec![])".into()),
        _ => {}
    }

    // Tuple: `(T1, T2, ...)`
    if s.starts_with('(') && s.ends_with(')') {
        let inner = &s[1..s.len()-1];
        let parts = split_top_level(inner, ',');
        let exprs: Option<Vec<String>> = parts.iter().map(|p| parse_ty_to_rust(p.trim())).collect();
        let exprs = exprs?;
        return Some(format!("Ty::Tuple(vec![{}])", exprs.join(", ")));
    }

    // Applied: `List[T]`, `Option[T]`, `Result[T, E]`, `Map[K, V]`, `Set[T]`
    if let Some(idx) = s.find('[') {
        if s.ends_with(']') {
            let head = &s[..idx];
            let inner = &s[idx+1..s.len()-1];
            let parts = split_top_level(inner, ',');
            let exprs: Option<Vec<String>> = parts.iter().map(|p| parse_ty_to_rust(p.trim())).collect();
            let exprs = exprs?;
            let tci = match head {
                "List"   => "TCI::List",
                "Option" => "TCI::Option",
                "Result" => "TCI::Result",
                "Map"    => "TCI::Map",
                "Set"    => "TCI::Set",
                other if head.chars().next().map(|c| c.is_uppercase()).unwrap_or(false) => {
                    // User-defined parameterized type: Named(other, [args])
                    return Some(format!(
                        "Ty::Named(sym({:?}), vec![{}])",
                        other, exprs.join(", ")
                    ));
                }
                _ => return None,
            };
            return Some(format!("Ty::Applied({}, vec![{}])", tci, exprs.join(", ")));
        }
    }

    // Bare identifier: single type variable (generic like K, V, T, A, B)
    // or a Named type like Value, MyStruct.
    if s.chars().all(|c| c.is_alphanumeric() || c == '_') {
        let first = s.chars().next()?;
        if first.is_uppercase() {
            if s.len() <= 2 && s.chars().all(|c| c.is_uppercase() || c.is_ascii_digit()) {
                // Short uppercase identifier → type variable
                return Some(format!("Ty::TypeVar(sym({:?}))", s));
            }
            // Longer uppercase → Named type
            return Some(format!("Ty::Named(sym({:?}), vec![])", s));
        }
    }

    None
}

/// Split a comma-separated list respecting nested `[...]` and `(...)`.
fn split_top_level(s: &str, delim: char) -> Vec<String> {
    let mut parts = Vec::new();
    let mut depth = 0i32;
    let mut cur = String::new();
    for ch in s.chars() {
        match ch {
            '[' | '(' | '<' => { depth += 1; cur.push(ch); }
            ']' | ')' | '>' => { depth -= 1; cur.push(ch); }
            c if c == delim && depth == 0 => {
                parts.push(cur.trim().to_string());
                cur.clear();
            }
            c => cur.push(c),
        }
    }
    if !cur.trim().is_empty() { parts.push(cur.trim().to_string()); }
    parts
}
