//! Emit `egg::rewrite!` invocations for every `@rewrite` attribute in
//! `stdlib/matrix.almd`. Output lands at `$OUT_DIR/matrix_rules_gen.rs`
//! and is `include!`-ed from `crates/almide-egg-lab/src/lib.rs`.
//!
//! Parser is shared with `almide-codegen/buildscript/fusion_parse.rs`
//! via `#[path]` include — stdlib is the single source of truth for
//! both the imperative `FusionRule` registry and the egg `rewrite!`
//! table. Rename convention: stdlib `matrix.<func>` → egg `matrix_<func>`
//! because egg's S-expr tokenizer treats `.` as a separator.

#[path = "../../almide-codegen/buildscript/fusion_parse.rs"]
mod fusion_parse;

use fusion_parse::{extract_rewrites, Pat, RewriteDecl};
use std::path::Path;

pub fn generate(workspace_root: &Path, out_dir: &Path) {
    let stdlib_path = workspace_root.join("stdlib/matrix.almd");
    println!("cargo:rerun-if-changed={}", stdlib_path.display());

    let src = std::fs::read_to_string(&stdlib_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {}", stdlib_path.display(), e));

    let decls = extract_rewrites(&src);
    let rust_src = emit_rust(&decls);

    let out_path = out_dir.join("matrix_rules_gen.rs");
    std::fs::write(&out_path, rust_src)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", out_path.display(), e));
}

fn emit_rust(decls: &[RewriteDecl]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by buildscript/egg_rules.rs from stdlib/matrix.almd.\n");
    out.push_str("// Any edits here will be overwritten.\n");
    out.push_str("//\n");
    out.push_str("// Source of truth:\n");
    out.push_str("//   the `@rewrite(name, from, to)` attributes in stdlib/matrix.almd.\n");
    out.push_str("// Rename: stdlib `matrix.<func>` → egg `matrix_<func>` (egg S-expr\n");
    out.push_str("// tokenizer treats `.` as separator).\n\n");

    out.push_str("pub fn generated_matrix_fusion_rules() -> Vec<::egg::Rewrite<crate::AlmideExpr, ()>> {\n");
    out.push_str("    vec![\n");
    for decl in decls {
        out.push_str(&format!("        ::egg::rewrite!(\"{}\"; ", decl.name));
        out.push('"');
        emit_sexp(&decl.from, &mut out);
        out.push_str("\" => \"");
        emit_sexp(&decl.to, &mut out);
        out.push_str("\"),\n");
    }
    out.push_str("    ]\n}\n");
    out
}

/// Serialize a `Pat` as egg S-expression source with the
/// `matrix.<func>` → `matrix_<func>` rename.
fn emit_sexp(pat: &Pat, out: &mut String) {
    match pat {
        Pat::Call { func, children } => {
            out.push('(');
            out.push_str("matrix_");
            out.push_str(func);
            for c in children {
                out.push(' ');
                emit_sexp(c, out);
            }
            out.push(')');
        }
        Pat::Capture(name) => {
            out.push('?');
            out.push_str(name);
        }
    }
}
