#!/usr/bin/env python3
"""Loss-decomposition measurements (vibe-battle str_build method): isolate which
phase/construct pays for each axis Almide loses on the main matrix.

Variants (decomposition/):
  float_loop_noprint  (almide, rust) — 20M float loop, constant print
  list_copy_only      (almide, rust) — 300x copy+index, sort removed
  str_build_tenth     (almide)       — 300k iterations, RSS scaling probe
Reference (src/grain/):
  int_loop_int64      (grain)        — type-choice reference for the Number rows

Run AFTER measure.sh (idle machine). Writes out/decomposition.md.
"""
import os
import statistics
import subprocess
import time
from pathlib import Path

S = Path(__file__).resolve().parent
OUT = S / "out"
BREW = "/opt/homebrew/bin"
WASMTIME = f"{BREW}/wasmtime"
ENV = dict(os.environ, PATH=f"{BREW}:{os.environ['PATH']}")
DOUT = OUT / "decomposition"
DOUT.mkdir(parents=True, exist_ok=True)


def run5(wasm):
    cmd = [WASMTIME, "run", str(wasm)]
    subprocess.run(cmd, capture_output=True, env=ENV, timeout=300)  # warmup
    times = []
    out = None
    for _ in range(5):
        t0 = time.perf_counter()
        p = subprocess.run(cmd, capture_output=True, text=True, env=ENV, timeout=300)
        times.append(time.perf_counter() - t0)
        assert p.returncode == 0, p.stderr
        out = p.stdout.strip()
    p = subprocess.run(["/usr/bin/time", "-l", *cmd], capture_output=True, text=True,
                       env=ENV, timeout=300)
    rss = next((int(l.split()[0]) for l in p.stderr.splitlines()
                if "maximum resident set size" in l), None)
    return min(times), statistics.median(times), rss, out


def build():
    emit = S / "tools/emit-only/target/release/almide-emit-only"
    for v in ["float_loop_noprint", "list_copy_only", "str_build_tenth"]:
        subprocess.run([str(emit), f"decomposition/almide/{v}.almd",
                        f"{DOUT}/almide_{v}.wasm"], cwd=S, env=ENV, check=True)
    for v in ["float_loop_noprint", "list_copy_only"]:
        subprocess.run(["rustc", "--sysroot", str(OUT / "rust-sysroot-overlay"),
                        "--target", "wasm32-wasip1", "-C", "opt-level=3",
                        f"decomposition/rust/{v}.rs", "-o", f"{DOUT}/rust_{v}.wasm"],
                       cwd=S, env=ENV, check=True)
    subprocess.run(["grain", "compile", "--release", "-o",
                    f"{DOUT}/grain_int_loop_int64.wasm", "int_loop_int64.gr"],
                   cwd=S / "src/grain", env=ENV, check=True)


def main():
    build()
    lines = ["# decomposition measurements (generated by decompose.py)",
             "",
             "| variant | best (s) | median (s) | peak RSS (bytes) | output |",
             "|---|---|---|---|---|"]
    for wasm in sorted(DOUT.glob("*.wasm")):
        b, m, rss, out = run5(wasm)
        lines.append(f"| {wasm.stem} | {b:.4f} | {m:.4f} | {rss} | {out} |")
    (OUT / "decomposition.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
