#!/usr/bin/env python3
import sys
import unicodedata

msg = open(sys.argv[1]).read()
if any(unicodedata.east_asian_width(c) in ('W', 'F') for c in msg):
    print("ERROR: Commit message contains Japanese characters. Please write in English.")
    sys.exit(1)
