//! Embed the self-hosted stdlib with WHOLE-LINE COMMENTS BLANKED (#878).
//!
//! Every `stdlib/*.almd` is embedded verbatim in the compiler binary — the
//! wasm self-host registry and the bundled-module table together carry ~1.19MB
//! of it, which was 2.04MB of the playground's 5.8MB download. The sources are
//! heavily commented on purpose (the comments are the design record and they
//! belong in the repo), but a comment costs the same bytes in every embedder's
//! binary as it does in the file.
//!
//! So the EMBEDDED copy blanks them: a line whose first non-space character
//! starts `//` becomes empty. Two properties make this safe rather than a
//! trade:
//!
//! * LINE COUNT is preserved exactly — a blanked line is still a line — so
//!   every span into a bundled source (the `file:line` in a diagnostic, the
//!   `@intrinsic` lookups, the wall reasons) points where it did before.
//! * Only WHOLE-LINE comments are blanked. A trailing `// …` after code stays,
//!   because finding its start needs the lexer (a `//` inside a string literal
//!   is not a comment), and that judgement does not belong in a build script.
//!
//! Measured 374234 bytes saved of 1190489 — 31%.
//!
//! The generated module is `embedded.rs` in `OUT_DIR`: one `pub const` per
//! source plus `source_of(stem)`. Consumers `include!` it rather than
//! `include_str!`ing the files directly.

use std::fmt::Write as _;

fn main() {
    let manifest = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let stdlib = manifest.join("../../stdlib");
    println!("cargo:rerun-if-changed={}", stdlib.display());

    let mut files: Vec<std::path::PathBuf> = std::fs::read_dir(&stdlib)
        .unwrap_or_else(|e| panic!("read {}: {e}", stdlib.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map(|x| x == "almd").unwrap_or(false))
        .collect();
    files.sort();

    let mut out = String::new();
    out.push_str("// @generated by crates/almide-types/build.rs — do not edit.\n");
    let mut arms = String::new();
    for path in &files {
        let stem = path.file_stem().expect("almd file has a stem").to_string_lossy().to_string();
        let raw = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let stripped = blank_comment_lines(&raw);
        let ident = format!("SRC_{}", stem.to_uppercase());
        writeln!(out, "pub const {ident}: &str = {};", escape(&stripped)).expect("write to String");
        writeln!(arms, "        {:?} => Some({ident}),", stem).expect("write to String");
        println!("cargo:rerun-if-changed={}", path.display());
    }
    writeln!(
        out,
        "\n/// The embedded source of `stdlib/<stem>.almd`, comments blanked.\n\
         pub fn source_of(stem: &str) -> Option<&'static str> {{\n\
         \x20   match stem {{\n{arms}        _ => None,\n    }}\n}}"
    )
    .expect("write to String");

    let dest = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("embedded.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}

/// Blank every WHOLE-LINE `//` comment, keeping the line itself so line
/// numbers are unchanged. Trailing comments after code are left alone.
fn blank_comment_lines(src: &str) -> String {
    src.split('\n')
        .map(|line| if line.trim_start().starts_with("//") { "" } else { line })
        .collect::<Vec<_>>()
        .join("\n")
}

fn escape(s: &str) -> String {
    // A raw string with enough hashes to clear any `"#` run in the source.
    let mut hashes = 1;
    while s.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let h = "#".repeat(hashes);
    format!("r{h}\"{s}\"{h}")
}
