/// The self-hosted stdlib, embedded with whole-line `//` comments blanked
/// (#878 — 31% of the payload every embedder downloads) and whole-line
/// `///` doc comments kept (#2436 — they are the interface JSON's `doc`
/// input on the by-name compile route). Generated by `build.rs` into the
/// committed `src/generated/embedded.rs` (#3361: the package carries it, so a
/// vendored almide-types builds without `stdlib/`); line numbers are
/// preserved so spans into a bundled source still point where they did.
pub mod embedded {
    include!("generated/embedded.rs");
}

pub mod dialect;
pub mod types;
pub mod stdlib_info;
pub mod self_host_registry;
pub mod time_units;
pub mod fallible_hofs;

// Re-export almide-base for convenience
pub use almide_base;
pub use almide_base::intern;
