/// The self-hosted stdlib, embedded with whole-line comments blanked
/// (#878 — 31% of the payload every embedder downloads). Generated by
/// `build.rs`; line numbers are preserved so spans into a bundled source
/// still point where they did.
pub mod embedded {
    include!(concat!(env!("OUT_DIR"), "/embedded.rs"));
}

pub mod dialect;
pub mod types;
pub mod stdlib_info;
pub mod self_host_registry;
pub mod time_units;

// Re-export almide-base for convenience
pub use almide_base;
pub use almide_base::intern;
