//! The self-hosted stdlib runtime registry: (source, &[(impl_fn, call_name)]) tuples.
//!
//! This is the SINGLE authority tying a stdlib call name (`"int.to_int8"`) to the
//! pure-Almide impl fn (`int_to_int8`) inside its embedded source. Two consumers
//! read it, and keeping them on one table is the point:
//!
//! - the WASM renderer (`almide-mir::render_wasm`) links each source into the
//!   build to fixpoint, so every wasm binary runs these bodies;
//! - the interp oracle (`almide-interp`) lowers the same sources once and
//!   evaluates the same bodies as the third cross-target vote, so a scalar
//!   stdlib fn is covered by the executable spec WITHOUT hand-written glue —
//!   the hand-mirrored-bridge drift class (a restated subset of this table's
//!   semantics) structurally cannot recur.
//!
//! It lives here, beside `crate::embedded`'s sources, because the mapping is a
//! property of the stdlib itself, not of any one backend.

pub fn self_host_runtime() -> &'static [(&'static str, &'static [(&'static str, &'static str)])] {
    &[
        (crate::embedded::SRC_INT_TO_STRING, &[("int_to_string", "int.to_string")]),
        (crate::embedded::SRC_RANDOM_INT, &[("random_int", "random.int")]),
        (crate::embedded::SRC_RANDOM_FLOAT, &[("random_float", "random.float")]),
        (crate::embedded::SRC_RANDOM_CHOICE, &[("random_choice", "random.choice"), ("random_choice_str", "random.choice_str")]),
        (crate::embedded::SRC_RANDOM_SHUFFLE, &[("random_shuffle", "random.shuffle"), ("random_shuffle_str", "random.shuffle_str")]),
        (crate::embedded::SRC_ENV_ARGS, &[("env_args", "env.args")]),
        (crate::embedded::SRC_ENV_GET, &[("env_get", "env.get")]),
        (crate::embedded::SRC_PROCESS_ARGS, &[("process_args", "process.args")]),
        (crate::embedded::SRC_ENV_OS, &[("env_os", "env.os")]),
        (crate::embedded::SRC_ENV_TEMP_DIR, &[("env_temp_dir", "env.temp_dir")]),
        (crate::embedded::SRC_ENV_UNIX_TIMESTAMP, &[("env_unix_timestamp", "env.unix_timestamp")]),
        (crate::embedded::SRC_CLOCK_NOW, &[("datetime_now", "datetime.now"), ("env_millis", "env.millis")]),
        (crate::embedded::SRC_FS_READ_TEXT, &[("fs_read_text", "fs.read_text")]),
        (crate::embedded::SRC_FS_STAT, &[("fs_stat", "fs.stat")]),
        (crate::embedded::SRC_FS_READ_BYTES_RAW, &[("fs_read_bytes_raw", "fs.read_bytes_raw")]),
        (crate::embedded::SRC_FS_READ_BYTES, &[("fs_read_bytes", "fs.read_bytes")]),
        (crate::embedded::SRC_FS_LIST_DIR, &[("fs_list_dir", "fs.list_dir")]),
        (crate::embedded::SRC_FS_WRITE, &[("fs_write", "fs.write")]),
        (crate::embedded::SRC_FS_MKDIR_P, &[("fs_mkdir_p", "fs.mkdir_p")]),
        (crate::embedded::SRC_FS_REMOVE_ALL, &[("fs_remove_all", "fs.remove_all")]),
        (crate::embedded::SRC_FS_EXISTS, &[("fs_exists", "fs.exists")]),
        (crate::embedded::SRC_IO_PRINT, &[("io_print", "io.print")]),
        (crate::embedded::SRC_IO_WRITE, &[("io_write", "io.write"), ("io_write_bytes", "io.write_bytes")]),
        (crate::embedded::SRC_IO_READ_LINE, &[("io_read_line", "io.read_line")]),
        (crate::embedded::SRC_IO_READ_N_BYTES, &[("io_read_n_bytes", "io.read_n_bytes")]),
        (crate::embedded::SRC_IO_READ_ALL, &[("io_read_all", "io.read_all")]),
        (crate::embedded::SRC_JSON_GET, &[("json_get", "json.get")]),
        (crate::embedded::SRC_JSON_AS_ARRAY, &[("json_as_array", "json.as_array")]),
        (crate::embedded::SRC_JSON_GET_TYPED, &[("json_get_string", "json.get_string"), ("json_get_int", "json.get_int"), ("json_get_float", "json.get_float"), ("json_get_bool", "json.get_bool"), ("json_get_array", "json.get_array")]),
        (crate::embedded::SRC_FLOAT_TO_STRING, &[("float_to_string", "float.to_string"), ("float_to_fixed", "float.to_fixed")]),
        (crate::embedded::SRC_BOOL, &[("bool_to_string", "bool.to_string")]),
        (crate::embedded::SRC_ERROR_CHAIN, &[("error_chain", "error.chain"), ("error_context", "error.context")]),
        (crate::embedded::SRC_ERROR_MESSAGE, &[("error_message", "error.message")]),
        (crate::embedded::SRC_STRING_LEN, &[("string_len", "string.len"), ("string_length", "string.length")]),
        (crate::embedded::SRC_STRING_REPEAT, &[("string_repeat", "string.repeat")]),
        (crate::embedded::SRC_STRING_RLE, &[("string_run_length_encode", "string.run_length_encode")]),
        (crate::embedded::SRC_LIST_TO_STRING_LSI, &[("list_to_string_lsi", "list.to_string_lsi")]),
        (crate::embedded::SRC_STRING_IS_EMPTY, &[("string_is_empty", "string.is_empty")]),
        (crate::embedded::SRC_STRING_EQ, &[("string_eq", "string.eq")]),
        (crate::embedded::SRC_STRING_CLASS, &[("string_is_alpha", "string.is_alpha"), ("string_is_upper", "string.is_upper"), ("string_is_lower", "string.is_lower"), ("string_is_alphanumeric_uni", "string.is_alphanumeric")]),
        (crate::embedded::SRC_STRING_CMP, &[("string_cmp", "string.cmp")]),
        (
            crate::embedded::SRC_MATH_INT,
            &[
                ("math_abs", "math.abs"),
                ("math_max", "math.max"),
                ("math_min", "math.min"),
                ("math_sign", "math.sign"),
                ("math_pow", "math.pow"),
                ("math_factorial", "math.factorial"),
                ("math_choose", "math.choose"),
            ],
        ),
        (
            crate::embedded::SRC_OPTION_PRED,
            &[
                ("option_is_some", "option.is_some"),
                ("option_is_none", "option.is_none"),
                ("option_unwrap_or", "option.unwrap_or"),
                ("option_to_list", "option.to_list"),
                ("option_to_list_rc", "option.to_list_rc"),
            ],
        ),
        (
            crate::embedded::SRC_OPTION_UNWRAP_OR_STR,
            &[("option_unwrap_or_str", "option.unwrap_or_str")],
        ),
        (
            crate::embedded::SRC_LIST_MODIFY,
            &[
                ("list_set", "list.set"),
                ("list_set_str", "list.set_str"),
                ("list_insert_str", "list.insert_str"),
                ("list_remove_at_str", "list.remove_at_str"),
                ("list_swap_str", "list.swap_str"),
                ("list_update_str", "list.update_str"),
                ("list_update_value", "list.update_value"),
                ("list_swap", "list.swap"),
                ("list_insert", "list.insert"),
                ("list_remove_at", "list.remove_at"),
                ("list_tail", "list.tail"),
                ("list_take_end", "list.take_end"),
                ("list_drop_end", "list.drop_end"),
                ("list_drop_end_str", "list.drop_end_str"),
                ("list_take_end_str", "list.take_end_str"),
                ("list_tail_str", "list.tail_str"),
                ("list_update", "list.update"),
            ],
        ),
        (crate::embedded::SRC_LIST_MAP, &[("list_map", "list.map")]),
        // #850: rc-correct twins for a heap element that is neither String nor Value
        // (tuples, records, nested lists). Before these the instantiations routed to
        // an unregistered `_heapelem` name and walled cleanly rather than double-free.
        (crate::embedded::SRC_LIST_HEAPELEM, &[("list_set_heapelem", "list.set_heapelem"), ("list_update_heapelem", "list.update_heapelem"), ("list_insert_heapelem", "list.insert_heapelem"), ("list_remove_at_heapelem", "list.remove_at_heapelem"), ("list_swap_heapelem", "list.swap_heapelem"), ("list_take_end_heapelem", "list.take_end_heapelem"), ("list_drop_end_heapelem", "list.drop_end_heapelem"), ("list_tail_heapelem", "list.tail_heapelem")]),
        (crate::embedded::SRC_LIST_PARTITION, &[("list_partition", "list.partition"), ("list_partition_rc", "list.partition_rc")]),
        (crate::embedded::SRC_LIST_PAIRS, &[("list_enumerate", "list.enumerate"), ("list_enumerate_str", "list.enumerate_str"), ("list_zip", "list.zip"), ("list_zip_rc", "list.zip_rc"), ("list_zip_sh", "list.zip_sh"), ("list_zip_hs", "list.zip_hs"), ("list_zip_h", "list.zip_h")]),
        (crate::embedded::SRC_LIST_HSHARE, &[("list_get_or_hshare", "list.get_or_hshare"), ("list_get_hshare", "list.get_hshare"), ("list_first_hshare", "list.first_hshare"), ("list_last_hshare", "list.last_hshare"), ("list_take_hshare", "list.take_hshare"), ("list_unique_hshare", "list.unique_hshare"), ("list_dedup_hshare", "list.dedup_hshare"), ("list_contains_hshare", "list.contains_hshare"), ("list_index_of_hshare", "list.index_of_hshare"), ("list_drop_hshare", "list.drop_hshare")]),
        (crate::embedded::SRC_LIST_MAP_STR, &[("list_map_str", "list.map_str")]),
        (crate::embedded::SRC_LIST_MAP_S2H, &[("list_map_s2h", "list.map_s2h")]),
        (crate::embedded::SRC_LIST_FILTER_STR, &[("list_filter_str", "list.filter_str")]),
        (crate::embedded::SRC_LIST_REVERSE_STR, &[("list_reverse_str", "list.reverse_str")]),
        (crate::embedded::SRC_LIST_TAKEDROP_STR, &[("list_take_str", "list.take_str"), ("list_drop_str", "list.drop_str"), ("list_slice_str", "list.slice_str")]),
        (crate::embedded::SRC_LIST_GET_STR, &[("list_get_str", "list.get_str"), ("list_first_str", "list.first_str"), ("list_last_str", "list.last_str")]),
        (crate::embedded::SRC_BYTES_ARRAY, &[("bytes_read_u16_le_array", "bytes.read_u16_le_array"), ("bytes_read_u32_le_array", "bytes.read_u32_le_array"), ("bytes_read_i32_le_array", "bytes.read_i32_le_array"), ("bytes_read_u16_be_array", "bytes.read_u16_be_array"), ("bytes_read_u32_be_array", "bytes.read_u32_be_array"), ("bytes_read_i16_le_array", "bytes.read_i16_le_array"), ("bytes_read_i16_be_array", "bytes.read_i16_be_array"), ("bytes_read_i32_be_array", "bytes.read_i32_be_array"), ("bytes_read_i64_le_array", "bytes.read_i64_le_array"), ("bytes_read_i64_be_array", "bytes.read_i64_be_array"), ("bytes_read_f64_le_array", "bytes.read_f64_le_array"), ("bytes_read_f64_be_array", "bytes.read_f64_be_array"), ("bytes_read_f32_le_array", "bytes.read_f32_le_array"), ("bytes_read_f32_be_array", "bytes.read_f32_be_array")]),
        (crate::embedded::SRC_SET_CORE, &[("set_from_list", "set.from_list"), ("set_len", "set.len"), ("set_is_empty", "set.is_empty"), ("set_contains", "set.contains"), ("set_to_list", "set.to_list"), ("set_union", "set.union"), ("set_intersection", "set.intersection"), ("set_difference", "set.difference"), ("set_is_subset", "set.is_subset"), ("set_is_disjoint", "set.is_disjoint"), ("set_new", "set.new"), ("set_insert", "set.insert"), ("set_remove", "set.remove"), ("set_symmetric_difference", "set.symmetric_difference"), ("set_filter", "set.filter"), ("set_all", "set.all"), ("set_any", "set.any"), ("set_map", "set.map"), ("set_fold", "set.fold")]),
        (crate::embedded::SRC_LIST_STR, &[("list_contains_str", "list.contains_str"), ("list_index_of_str", "list.index_of_str"), ("list_any_str", "list.any_str"), ("list_all_str", "list.all_str"), ("list_count_str", "list.count_str"), ("list_fold_str", "list.fold_str"), ("list_find_str", "list.find_str"), ("list_unique_str", "list.unique_str"), ("list_dedup_str", "list.dedup_str"), ("list_intersperse_str", "list.intersperse_str")]),
        (crate::embedded::SRC_LIST_FOLD_OLS, &[("list_fold_ols", "list.fold_ols"), ("list_fold_str_hacc", "list.fold_str_hacc"), ("set_fold_str_hacc", "set.fold_str_hacc")]),
        (crate::embedded::SRC_LIST_FOLD_HREC, &[("list_fold_hrec", "list.fold_hrec")]),
        (crate::embedded::SRC_LIST_FOLD_HSCA, &[("list_fold_hsca", "list.fold_hsca")]),
        (crate::embedded::SRC_LIST_SORT_BY_KEYS, &[("list_sort_by_keys", "list.sort_by_keys")]),
        (crate::embedded::SRC_MAP_HOBJ, &[("map_from_list_hobj", "map.from_list_hobj")]),
        (crate::embedded::SRC_SET_STR, &[("set_from_list_str", "set.from_list_str"), ("set_contains_str", "set.contains_str"), ("set_to_list_str", "set.to_list_str"), ("set_union_str", "set.union_str"), ("set_intersection_str", "set.intersection_str"), ("set_difference_str", "set.difference_str"), ("set_is_subset_str", "set.is_subset_str"), ("set_is_disjoint_str", "set.is_disjoint_str"), ("set_new_str", "set.new_str"), ("set_insert_str", "set.insert_str"), ("set_remove_str", "set.remove_str"), ("set_symmetric_difference_str", "set.symmetric_difference_str"), ("set_filter_str", "set.filter_str"), ("set_all_str", "set.all_str"), ("set_any_str", "set.any_str"), ("set_fold_str", "set.fold_str"), ("set_eq_str", "set.eq_str")]),
        (crate::embedded::SRC_MAP_STR, &[("map_new_str", "map.new_str"), ("map_from_list_str", "map.from_list_str"), ("map_len_str", "map.len_str"), ("map_is_empty_str", "map.is_empty_str"), ("map_contains_str", "map.contains_str"), ("map_get_str", "map.get_str"), ("map_set_str", "map.set_str"), ("map_keys_str", "map.keys_str"), ("map_values_str", "map.values_str"), ("map_remove_str", "map.remove_str"), ("map_merge_str", "map.merge_str"), ("map_update_str", "map.update_str"), ("map_filter_str", "map.filter_str"), ("map_all_str", "map.all_str"), ("map_any_str", "map.any_str"), ("map_count_str", "map.count_str"), ("map_fold_str", "map.fold_str")]),
        (crate::embedded::SRC_MAP_FOLD_HACC, &[("map_fold_str_msi", "map.fold_str_msi"), ("map_fold_skv_msi", "map.fold_skv_msi"), ("map_fold_str_sacc", "map.fold_str_sacc"), ("map_fold_skv_hacc", "map.fold_skv_hacc"), ("list_fold_str_msi", "list.fold_str_msi")]),
        (crate::embedded::SRC_MAP_MSV, &[("map_new_msv", "map.new_msv"), ("map_set_msv", "map.set_msv"), ("map_from_list_msv", "map.from_list_msv"), ("map_get_or_msv", "map.get_or_msv")]),
        (crate::embedded::SRC_MAP_MLO, &[("map_new_mlo", "map.new_mlo"), ("map_set_mlo", "map.set_mlo"), ("map_from_list_mlo", "map.from_list_mlo"), ("map_to_string_mlo", "map.to_string_mlo"), ("list_to_string_lmlo", "list.to_string_lmlo")]),
        (crate::embedded::SRC_MAP_CORE, &[("map_new", "map.new"), ("map_len", "map.len"), ("map_is_empty", "map.is_empty"), ("map_contains", "map.contains"), ("map_get_or", "map.get_or"), ("map_set", "map.set"), ("map_remove", "map.remove"), ("map_keys", "map.keys"), ("map_values", "map.values"), ("map_get", "map.get"), ("map_merge", "map.merge"), ("map_update", "map.update"), ("map_filter", "map.filter"), ("map_all", "map.all"), ("map_any", "map.any"), ("map_count", "map.count"), ("map_fold", "map.fold"), ("map_from_list", "map.from_list")]),
        (crate::embedded::SRC_MAP_SKV, &[("map_new_skv", "map.new_skv"), ("map_len_skv", "map.len_skv"), ("map_is_empty_skv", "map.is_empty_skv"), ("map_contains_skv", "map.contains_skv"), ("map_get_or_skv", "map.get_or_skv"), ("map_get_skv", "map.get_skv"), ("map_set_skv", "map.set_skv"), ("map_remove_skv", "map.remove_skv"), ("map_keys_skv", "map.keys_skv"), ("map_values_skv", "map.values_skv"), ("map_filter_skv", "map.filter_skv"), ("map_all_skv", "map.all_skv"), ("map_any_skv", "map.any_skv"), ("map_count_skv", "map.count_skv"), ("map_fold_skv", "map.fold_skv"), ("map_eq_skv", "map.eq_skv"), ("map_entries_skv", "map.entries_skv"), ("map_from_list_skv", "map.from_list_skv"), ("map_find_skv", "map.find_skv"), ("map_update_skv", "map.update_skv"), ("map_map_skv", "map.map_skv"), ("map_merge_skv", "map.merge_skv")]),
                        (crate::embedded::SRC_CODEC_ENCODE, &[
            ("__encode_list_int", "__encode_list_int"), ("__encode_list_float", "__encode_list_float"),
            ("__encode_list_bool", "__encode_list_bool"), ("__encode_list_string", "__encode_list_string"),
            ("__encode_option_int", "__encode_option_int"), ("__encode_option_float", "__encode_option_float"),
            ("__encode_option_bool", "__encode_option_bool"), ("__encode_option_string", "__encode_option_string")]),
        (crate::embedded::SRC_CODEC_DECODE, &[
            ("__decode_list_int", "__decode_list_int"), ("__decode_list_float", "__decode_list_float"),
            ("__decode_list_bool", "__decode_list_bool"), ("__decode_list_string", "__decode_list_string"),
            ("__decode_option_int", "__decode_option_int"), ("__decode_option_float", "__decode_option_float"),
            ("__decode_option_bool", "__decode_option_bool"), ("__decode_option_string", "__decode_option_string"),
            ("__decode_default_int", "__decode_default_int"), ("__decode_default_float", "__decode_default_float"),
            ("__decode_default_bool", "__decode_default_bool"), ("__decode_default_string", "__decode_default_string")]),
        (crate::embedded::SRC_VALUE_CORE, &[("value_null", "value.null"), ("value_int", "value.int"), ("value_bool", "value.bool"), ("value_float", "value.float"), ("value_as_int", "value.as_int"), ("value_as_bool", "value.as_bool"), ("value_as_float", "value.as_float"), ("value_str", "value.str"), ("value_as_string", "value.as_string"), ("value_array", "value.array"), ("value_as_array", "value.as_array"), ("value_object", "value.object"), ("value_eq", "value.eq"), ("list_eq_int", "list.eq_int"), ("list_eq_str", "list.eq_str"), ("list_eq_value", "list.eq_value"), ("list_eq_float", "list.eq_float"), ("list_eq_bool", "list.eq_bool"), ("list_eq_list_int", "list.eq_list_int"), ("list_eq_list_float", "list.eq_list_float"), ("list_eq_list_str", "list.eq_list_str"), ("list_eq_opt_int", "list.eq_opt_int"), ("list_set_value", "list.set_value"), ("list_insert_value", "list.insert_value"), ("list_remove_at_value", "list.remove_at_value"), ("list_swap_value", "list.swap_value"), ("list_take_end_value", "list.take_end_value"), ("list_drop_end_value", "list.drop_end_value"), ("list_tail_value", "list.tail_value"), ("value_merge", "value.merge"), ("json_keys", "json.keys"), ("value_stringify", "value.stringify"), ("json_stringify_pretty", "json.stringify_pretty"), ("value_get", "value.get"), ("value_field", "value.field"), ("result_value_unwrap_or", "result.value_unwrap_or"), ("result_list_value_unwrap_or", "result.list_value_unwrap_or"), ("result_str_unwrap_or", "result.str_unwrap_or"), ("result_flat_unwrap_or", "result.flat_unwrap_or"), ("option_value_unwrap_or", "option.value_unwrap_or"), ("option_liststr_unwrap_or", "option.liststr_unwrap_or"), ("option_listint_unwrap_or", "option.listint_unwrap_or"), ("option_unwrap_or_hx", "option.unwrap_or_hx"), ("result_unwrap_or_hx", "result.unwrap_or_hx"), ("option_listvalue_unwrap_or", "option.listvalue_unwrap_or"), ("list_get_value", "list.get_value"), ("list_get_or_value", "list.get_or_value"), ("list_first_value", "list.first_value"), ("list_last_value", "list.last_value"), ("list_get_liststr", "list.get_liststr"), ("list_first_liststr", "list.first_liststr"), ("list_last_liststr", "list.last_liststr"), ("map_entries_str", "map.entries_str"), ("list_take_liststr", "list.take_liststr"), ("list_drop_liststr", "list.drop_liststr")]),
        (crate::embedded::SRC_LIST_FILTER, &[("list_filter", "list.filter")]),
        (crate::embedded::SRC_LIST_FILTER_RC, &[("list_filter_rc", "list.filter_rc")]),
        (
            crate::embedded::SRC_LIST_ANYALL,
            &[("list_any", "list.any"), ("list_all", "list.all"), ("list_count", "list.count")],
        ),
        (
            crate::embedded::SRC_LIST_WHILEP,
            &[("list_take_while", "list.take_while"), ("list_drop_while", "list.drop_while"), ("list_take_while_str", "list.take_while_str"), ("list_drop_while_str", "list.drop_while_str")],
        ),
        (crate::embedded::SRC_LIST_FOLDF, &[("list_fold", "list.fold")]),
        (
            crate::embedded::SRC_LIST_FIND,
            &[("list_find", "list.find"), ("list_find_index", "list.find_index")],
        ),
        (crate::embedded::SRC_LIST_REDUCE, &[("list_reduce", "list.reduce"), ("list_reduce_str", "list.reduce_str")]),
        (crate::embedded::SRC_LIST_SCAN, &[("list_scan", "list.scan"), ("list_scan_str", "list.scan_str")]),
        (crate::embedded::SRC_EPRINTLN, &[("__eprintln_str", "eprintln")]),
        (crate::embedded::SRC_LIST_ZIPWITH, &[("list_zip_with", "list.zip_with"), ("list_zip_with_str", "list.zip_with_str")]),
        (crate::embedded::SRC_LIST_SORTBY, &[("list_sort_by", "list.sort_by"), ("list_sort_by_rc", "list.sort_by_rc")]),
        (crate::embedded::SRC_LIST_SORT_BY_STR_KEY, &[("list_sort_by_str_key", "list.sort_by_str_key")]),
        (crate::embedded::SRC_LIST_UNIQUEBY, &[("list_unique_by", "list.unique_by"), ("list_unique_by_sk", "list.unique_by_sk")]),
        (crate::embedded::SRC_LIST_FILTERMAP, &[("list_filter_map", "list.filter_map")]),
        (crate::embedded::SRC_LIST_FLATMAP, &[("list_flat_map", "list.flat_map")]),
        (
            crate::embedded::SRC_FLOAT_CORE,
            &[
                ("float_abs", "float.abs"),
                ("float_sqrt", "float.sqrt"),
                ("float_floor", "float.floor"),
                ("float_ceil", "float.ceil"),
                ("float_min", "float.min"),
                ("float_max", "float.max"),
                ("float_to_int", "float.to_int"),
                ("float_from_int", "float.from_int"),
                ("float_to_float64", "float.to_float64"),
                ("float_from_float64", "float.from_float64"),
            ],
        ),
        (
            crate::embedded::SRC_FLOAT_EXTRA,
            &[
                ("float_clamp", "float.clamp"),
                ("float_is_nan", "float.is_nan"),
                ("float_sign", "float.sign"),
                ("float_is_infinite", "float.is_infinite"),
            ],
        ),
        (crate::embedded::SRC_FLOAT_ROUND, &[("float_round", "float.round")]),
        (
            crate::embedded::SRC_MATH_FLOAT,
            &[
                ("math_sqrt", "math.sqrt"), ("math_fmin", "math.fmin"), ("math_fmax", "math.fmax"),
                ("math_pi", "math.pi"), ("math_e", "math.e"),
            ],
        ),
        (crate::embedded::SRC_MATH_LOG, &[("math_log", "math.log"), ("math_log2", "math.log2"), ("math_log10", "math.log10")]),
        (crate::embedded::SRC_MATH_EXP, &[("math_exp", "math.exp")]),
        (crate::embedded::SRC_MATH_TRIG, &[("math_sin", "math.sin"), ("math_cos", "math.cos"), ("math_tan", "math.tan")]),
        (crate::embedded::SRC_MATH_ATAN, &[("math_atan", "math.atan")]),
        (crate::embedded::SRC_MATH_TANH, &[("math_tanh", "math.tanh")]),
        (crate::embedded::SRC_MATH_FPOW, &[("math_fpow", "math.fpow")]),
        (crate::embedded::SRC_MATH_LGAMMA, &[("math_log_gamma", "math.log_gamma")]),
        (crate::embedded::SRC_BYTES_APPEND_MULTI, &[("bytes_append_u16_le", "bytes.append_u16_le"), ("bytes_append_u16_be", "bytes.append_u16_be"), ("bytes_append_i16_le", "bytes.append_i16_le"), ("bytes_append_i16_be", "bytes.append_i16_be"), ("bytes_append_u32_le", "bytes.append_u32_le"), ("bytes_append_u32_be", "bytes.append_u32_be"), ("bytes_append_i32_le", "bytes.append_i32_le"), ("bytes_append_i32_be", "bytes.append_i32_be"), ("bytes_append_i64_le", "bytes.append_i64_le"), ("bytes_append_i64_be", "bytes.append_i64_be"), ("bytes_append_f32_le", "bytes.append_f32_le"), ("bytes_append_f32_be", "bytes.append_f32_be"), ("bytes_append_f64_le", "bytes.append_f64_le"), ("bytes_append_f64_be", "bytes.append_f64_be")]),
        (crate::embedded::SRC_BYTES_TYPED, &[("bytes_endian_le", "LittleEndian"), ("bytes_endian_be", "BigEndian"), ("bytes_read_uint16", "bytes.read_uint16"), ("bytes_read_uint32", "bytes.read_uint32"), ("bytes_read_int32", "bytes.read_int32"), ("bytes_read_float32", "bytes.read_float32"), ("bytes_write_uint16", "bytes.write_uint16"), ("bytes_write_uint32", "bytes.write_uint32"), ("bytes_write_int32", "bytes.write_int32"), ("bytes_write_float32", "bytes.write_float32"), ("bytes_set_uint16", "bytes.set_uint16"), ("bytes_set_uint32", "bytes.set_uint32"), ("bytes_set_int32", "bytes.set_int32"), ("bytes_set_float32", "bytes.set_float32")]),
        (crate::embedded::SRC_BYTES_CURSOR, &[("bytes_read_u8_at", "bytes.read_u8_at"), ("bytes_read_bool_at", "bytes.read_bool_at"), ("bytes_read_u16_le_at", "bytes.read_u16_le_at"), ("bytes_read_u16_be_at", "bytes.read_u16_be_at"), ("bytes_read_i16_le_at", "bytes.read_i16_le_at"), ("bytes_read_i16_be_at", "bytes.read_i16_be_at"), ("bytes_read_u32_le_at", "bytes.read_u32_le_at"), ("bytes_read_u32_be_at", "bytes.read_u32_be_at"), ("bytes_read_i32_le_at", "bytes.read_i32_le_at"), ("bytes_read_i32_be_at", "bytes.read_i32_be_at"), ("bytes_read_i64_le_at", "bytes.read_i64_le_at"), ("bytes_read_i64_be_at", "bytes.read_i64_be_at"), ("bytes_read_f16_le_at", "bytes.read_f16_le_at"), ("bytes_read_f32_le_at", "bytes.read_f32_le_at"), ("bytes_read_f32_be_at", "bytes.read_f32_be_at"), ("bytes_read_f64_le_at", "bytes.read_f64_le_at"), ("bytes_read_f64_be_at", "bytes.read_f64_be_at"), ("bytes_take_at", "bytes.take_at"), ("bytes_read_string_be_at", "bytes.read_string_be_at")]),
        (crate::embedded::SRC_BYTES_F16, &[("bytes_read_f16_le", "bytes.read_f16_le"), ("bytes_read_f16_le_array", "bytes.read_f16_le_array")]),
        (
            crate::embedded::SRC_MATRIX_ACTIVATIONS,
            &[("matrix_softmax_rows", "matrix.softmax_rows"), ("matrix_gelu", "matrix.gelu"), ("matrix_swiglu_gate", "matrix.swiglu_gate"), ("matrix_rope_rotate", "matrix.rope_rotate"), ("matrix_multi_head_attention", "matrix.multi_head_attention"), ("matrix_masked_multi_head_attention", "matrix.masked_multi_head_attention"), ("matrix_from_q1_0_bytes", "matrix.from_q1_0_bytes")],
        ),
        (
            crate::embedded::SRC_MATRIX_SHAPE,
            &[("matrix_shape", "matrix.shape")],
        ),
        (
            crate::embedded::SRC_MATRIX_FUSED,
            &[("matrix_mul_scaled", "matrix.mul_scaled"), ("matrix_mul_f32", "matrix.mul_f32"), ("matrix_mul_f32_scaled", "matrix.mul_f32_scaled"), ("matrix_mul_f32_t", "matrix.mul_f32_t"), ("matrix_mul_f32_t_scaled", "matrix.mul_f32_t_scaled"), ("matrix_zeros_f32", "matrix.zeros_f32"), ("matrix_ones_f32", "matrix.ones_f32"), ("matrix_attention_weights", "matrix.attention_weights"), ("matrix_scaled_dot_product_attention", "matrix.scaled_dot_product_attention")],
        ),
        (
            crate::embedded::SRC_MATRIX_EXT,
            &[("matrix_silu_mul", "matrix.silu_mul"), ("matrix_broadcast_add_row", "matrix.broadcast_add_row"), ("matrix_row_dot", "matrix.row_dot"), ("matrix_conv1d", "matrix.conv1d"), ("matrix_to_bytes_f64_le", "matrix.to_bytes_f64_le"), ("matrix_to_bytes_f32_le", "matrix.to_bytes_f32_le"), ("matrix_from_bytes_f64_le", "matrix.from_bytes_f64_le")],
        ),
        (
            crate::embedded::SRC_MATRIX_ARITH,
            &[("matrix_sub", "matrix.sub"), ("matrix_div", "matrix.div"), ("matrix_neg", "matrix.neg"), ("matrix_pow", "matrix.pow")],
        ),
        (
            crate::embedded::SRC_MATRIX_CORE,
            &[
                ("matrix_from_lists", "matrix.from_lists"),
                ("matrix_to_lists", "matrix.to_lists"),
                ("matrix_zeros", "matrix.zeros"),
                ("matrix_ones", "matrix.ones"),
                ("matrix_rows", "matrix.rows"),
                ("matrix_cols", "matrix.cols"),
                ("matrix_get", "matrix.get"),
                ("matrix_add", "matrix.add"),
                ("matrix_scale", "matrix.scale"),
                ("matrix_map", "matrix.map"),
                ("matrix_transpose", "matrix.transpose"),
                ("matrix_slice_rows", "matrix.slice_rows"),
                ("matrix_gather_rows", "matrix.gather_rows"),
                ("matrix_causal_mask_add", "matrix.causal_mask_add"),
                ("matrix_dot_row", "matrix.dot_row"),
                ("matrix_mul", "matrix.mul"),
                ("matrix_linear_row", "matrix.linear_row"),
                ("matrix_linear_row_no_bias", "matrix.linear_row_no_bias"),
                ("matrix_rms_norm_rows", "matrix.rms_norm_rows"),
                ("matrix_layer_norm_rows", "matrix.layer_norm_rows"),
                ("matrix_from_bytes_f32_le", "matrix.from_bytes_f32_le"),
                ("matrix_from_bytes_f16_le", "matrix.from_bytes_f16_le"),
                ("matrix_split_cols_even", "matrix.split_cols_even"),
                ("matrix_concat_cols", "matrix.concat_cols"),
                ("matrix_concat_cols_many", "matrix.concat_cols_many"),
            ],
        ),
        (crate::embedded::SRC_STRING_CONCAT, &[("__str_concat", "__str_concat")]),
        (crate::embedded::SRC_LIST_CONCAT, &[("__list_concat", "__list_concat"), ("__list_concat_rc", "__list_concat_rc"), ("__list_append1", "__list_append1")]),
        (crate::embedded::SRC_BYTES_SKIP, &[("bytes_skip_length_prefixed_le", "bytes.skip_length_prefixed_le")]),
        (crate::embedded::SRC_BYTES_LENPREFIX, &[("bytes_read_length_prefixed_strings_le", "bytes.read_length_prefixed_strings_le")]),
        (crate::embedded::SRC_BYTES_STRING, &[("bytes_to_string_lossy", "bytes.to_string_lossy"), ("bytes_read_string_at", "bytes.read_string_at"), ("bytes_read_string_be", "bytes.read_string_be")]),
        (crate::embedded::SRC_JSON_SCALAR, &[("json_null", "json.null"), ("json_from_int", "json.from_int"), ("json_from_bool", "json.from_bool"), ("json_from_float", "json.from_float"), ("json_as_int", "json.as_int"), ("json_as_float", "json.as_float"), ("json_as_bool", "json.as_bool")]),
        (crate::embedded::SRC_JSON_STRING, &[("json_from_string", "json.from_string"), ("json_as_string", "json.as_string")]),
        (crate::embedded::SRC_JSON_PARSE, &[("json_parse", "json.parse")]),
        (crate::embedded::SRC_JSON_CTOR, &[("json_object", "json.object"), ("json_array", "json.array"), ("json_stringify", "json.stringify")]),
        (crate::embedded::SRC_JSON_PATH, &[("json_path_root", "json.root"), ("json_path_field", "json.field"), ("json_path_index", "json.index"), ("json_path_get", "json.get_path"), ("json_path_set", "json.set_path"), ("json_path_remove", "json.remove_path")]),
        (crate::embedded::SRC_RESULT_COLLECT, &[("result_collect", "result.collect"), ("result_partition", "result.partition"), ("result_collect_map", "result.collect_map")]),
        (crate::embedded::SRC_VALUE_UTILS, &[("value_pick", "value.pick"), ("value_omit", "value.omit"), ("value_to_camel_case", "value.to_camel_case"), ("value_to_snake_case", "value.to_snake_case")]),
        (crate::embedded::SRC_HTTP_URL_DECODE, &[("http_url_decode", "http.url_decode")]),
        (crate::embedded::SRC_DATETIME_PARSE_ISO, &[("datetime_parse_iso", "datetime.parse_iso")]),
        (crate::embedded::SRC_HTTP_RESPONSE, &[("http_response", "http.response"), ("http_json", "http.json"), ("http_redirect", "http.redirect"), ("http_with_headers", "http.with_headers"), ("http_status", "http.status"), ("http_body", "http.body"), ("http_set_header", "http.set_header"), ("http_get_header", "http.get_header")]),
        (crate::embedded::SRC_STRING_CAPITALIZE, &[("string_capitalize", "string.capitalize")]),
        (crate::embedded::SRC_UINT8_CONVERT, &[("uint8_to_int8", "uint8.to_int8"), ("uint8_to_int16", "uint8.to_int16"), ("uint8_to_int32", "uint8.to_int32"), ("uint8_to_int64", "uint8.to_int64"), ("uint8_to_uint16", "uint8.to_uint16"), ("uint8_to_uint32", "uint8.to_uint32"), ("uint8_to_uint64", "uint8.to_uint64"), ("uint8_to_float32", "uint8.to_float32"), ("uint8_to_float64", "uint8.to_float64"), ("uint8_to_string", "uint8.to_string")]),
        (crate::embedded::SRC_UINT16_CONVERT, &[("uint16_to_int8", "uint16.to_int8"), ("uint16_to_int16", "uint16.to_int16"), ("uint16_to_int32", "uint16.to_int32"), ("uint16_to_int64", "uint16.to_int64"), ("uint16_to_uint8", "uint16.to_uint8"), ("uint16_to_uint32", "uint16.to_uint32"), ("uint16_to_uint64", "uint16.to_uint64"), ("uint16_to_float32", "uint16.to_float32"), ("uint16_to_float64", "uint16.to_float64"), ("uint16_to_string", "uint16.to_string")]),
        (crate::embedded::SRC_UINT32_CONVERT, &[("uint32_to_int8", "uint32.to_int8"), ("uint32_to_int16", "uint32.to_int16"), ("uint32_to_int32", "uint32.to_int32"), ("uint32_to_int64", "uint32.to_int64"), ("uint32_to_uint8", "uint32.to_uint8"), ("uint32_to_uint16", "uint32.to_uint16"), ("uint32_to_uint64", "uint32.to_uint64"), ("uint32_to_float32", "uint32.to_float32"), ("uint32_to_float64", "uint32.to_float64"), ("uint32_to_string", "uint32.to_string")]),
        (crate::embedded::SRC_UINT64_CONVERT, &[("uint64_to_int8", "uint64.to_int8"), ("uint64_to_int16", "uint64.to_int16"), ("uint64_to_int32", "uint64.to_int32"), ("uint64_to_int64", "uint64.to_int64"), ("uint64_to_uint8", "uint64.to_uint8"), ("uint64_to_uint16", "uint64.to_uint16"), ("uint64_to_uint32", "uint64.to_uint32"), ("uint64_to_float32", "uint64.to_float32"), ("uint64_to_float64", "uint64.to_float64"), ("uint64_to_string", "uint64.to_string")]),
        (crate::embedded::SRC_INT64_CONVERT, &[("int64_to_string", "int64.to_string"), ("int64_to_int8", "int64.to_int8"), ("int64_to_int16", "int64.to_int16"), ("int64_to_int32", "int64.to_int32"), ("int64_to_uint8", "int64.to_uint8"), ("int64_to_uint16", "int64.to_uint16"), ("int64_to_uint32", "int64.to_uint32"), ("int64_to_uint64", "int64.to_uint64"), ("int64_to_float32", "int64.to_float32"), ("int64_to_float64", "int64.to_float64")]),
        (crate::embedded::SRC_FLOAT64_CONVERT, &[("float64_to_string", "float64.to_string"), ("float64_to_int8", "float64.to_int8"), ("float64_to_int16", "float64.to_int16"), ("float64_to_int32", "float64.to_int32"), ("float64_to_int64", "float64.to_int64"), ("float64_to_uint8", "float64.to_uint8"), ("float64_to_uint16", "float64.to_uint16"), ("float64_to_uint32", "float64.to_uint32"), ("float64_to_uint64", "float64.to_uint64"), ("float64_to_float32", "float64.to_float32")]),
        (crate::embedded::SRC_STRING_SPLIT, &[("string_split", "string.split")]),
        (crate::embedded::SRC_STRING_CHARS, &[("string_chars", "string.chars")]),
        (crate::embedded::SRC_STRING_LINES, &[("string_lines", "string.lines")]),
        (crate::embedded::SRC_STRING_JOIN, &[("string_join", "string.join"), ("list_join", "list.join")]),
        (
            crate::embedded::SRC_BYTES_CORE,
            BYTES_CORE_FNS,
        ),
        (
            crate::embedded::SRC_INT_TO_FLOAT,
            &[
                ("int_to_float", "int.to_float"),
                ("int_to_float64", "int.to_float64"),
                ("int_to_float32", "int.to_float32"),
            ],
        ),
        (
            crate::embedded::SRC_FLOAT_CONVERT,
            &[
                ("float_to_int8", "float.to_int8"),
                ("float_to_int16", "float.to_int16"),
                ("float_to_int32", "float.to_int32"),
                ("float_to_uint8", "float.to_uint8"),
                ("float_to_uint16", "float.to_uint16"),
                ("float_to_uint32", "float.to_uint32"),
                ("float_to_int64", "float.to_int64"),
                ("float_to_uint64", "float.to_uint64"),
                ("float_to_float32", "float.to_float32"),
                ("float_from_float32", "float.from_float32"),
                ("float_to_float32_checked", "float.to_float32_checked"),
            ],
        ),
        (
            crate::embedded::SRC_FLOAT_CHECKED,
            &[
                ("float_to_int8_checked", "float.to_int8_checked"),
                ("float_to_int16_checked", "float.to_int16_checked"),
                ("float_to_int32_checked", "float.to_int32_checked"),
                ("float_to_uint8_checked", "float.to_uint8_checked"),
                ("float_to_uint16_checked", "float.to_uint16_checked"),
                ("float_to_uint32_checked", "float.to_uint32_checked"),
                ("float_to_int64_checked", "float.to_int64_checked"),
                ("float_to_uint64_checked", "float.to_uint64_checked"),
            ],
        ),
        (
            crate::embedded::SRC_BYTES_SPLIT,
            &[
                ("bytes_split", "bytes.split"),
                ("bytes_lines", "bytes.lines"),
                ("bytes_chunks", "bytes.chunks"),
            ],
        ),
        (
            crate::embedded::SRC_BYTES_MUTATE,
            BYTES_MUTATE_FNS,
        ),
        (
            crate::embedded::SRC_DATETIME_FORMAT,
            &[("datetime_to_iso", "datetime.to_iso"), ("datetime_format", "datetime.format")],
        ),
        (
            crate::embedded::SRC_DATETIME_CALENDAR,
            &[
                ("datetime_year", "datetime.year"),
                ("datetime_month", "datetime.month"),
                ("datetime_day", "datetime.day"),
                ("datetime_weekday", "datetime.weekday"),
                ("datetime_from_parts", "datetime.from_parts"),
            ],
        ),
        (
            crate::embedded::SRC_DATETIME_ARITH,
            &[
                ("datetime_add_days", "datetime.add_days"),
                ("datetime_add_hours", "datetime.add_hours"),
                ("datetime_add_minutes", "datetime.add_minutes"),
                ("datetime_add_seconds", "datetime.add_seconds"),
                ("datetime_diff_seconds", "datetime.diff_seconds"),
                ("datetime_from_unix", "datetime.from_unix"),
                ("datetime_to_unix", "datetime.to_unix"),
                ("datetime_hour", "datetime.hour"),
                ("datetime_minute", "datetime.minute"),
                ("datetime_second", "datetime.second"),
                ("datetime_is_before", "datetime.is_before"),
                ("datetime_is_after", "datetime.is_after"),
            ],
        ),
        (
            crate::embedded::SRC_FLOAT32_CONVERT,
            &[
                ("float32_to_int8", "float32.to_int8"),
                ("float32_to_int16", "float32.to_int16"),
                ("float32_to_int32", "float32.to_int32"),
                ("float32_to_int64", "float32.to_int64"),
                ("float32_to_uint8", "float32.to_uint8"),
                ("float32_to_uint16", "float32.to_uint16"),
                ("float32_to_uint32", "float32.to_uint32"),
                ("float32_to_uint64", "float32.to_uint64"),
                ("float32_to_float64", "float32.to_float64"),
            ],
        ),
        (
            crate::embedded::SRC_INT8_CONVERT,
            &[
                ("int8_to_int16", "int8.to_int16"),
                ("int8_to_int32", "int8.to_int32"),
                ("int8_to_int64", "int8.to_int64"),
                ("int8_to_uint8", "int8.to_uint8"),
                ("int8_to_uint16", "int8.to_uint16"),
                ("int8_to_uint32", "int8.to_uint32"),
                ("int8_to_uint64", "int8.to_uint64"),
                ("int8_to_float32", "int8.to_float32"),
                ("int8_to_float64", "int8.to_float64"),
                ("int8_to_string", "int8.to_string"),
            ],
        ),
        (
            crate::embedded::SRC_INT16_CONVERT,
            &[
                ("int16_to_int8", "int16.to_int8"),
                ("int16_to_int32", "int16.to_int32"),
                ("int16_to_int64", "int16.to_int64"),
                ("int16_to_uint8", "int16.to_uint8"),
                ("int16_to_uint16", "int16.to_uint16"),
                ("int16_to_uint32", "int16.to_uint32"),
                ("int16_to_uint64", "int16.to_uint64"),
                ("int16_to_float32", "int16.to_float32"),
                ("int16_to_float64", "int16.to_float64"),
                ("int16_to_string", "int16.to_string"),
            ],
        ),
        (
            crate::embedded::SRC_INT32_CONVERT,
            &[
                ("int32_to_int8", "int32.to_int8"),
                ("int32_to_int16", "int32.to_int16"),
                ("int32_to_int64", "int32.to_int64"),
                ("int32_to_uint8", "int32.to_uint8"),
                ("int32_to_uint16", "int32.to_uint16"),
                ("int32_to_uint32", "int32.to_uint32"),
                ("int32_to_uint64", "int32.to_uint64"),
                ("int32_to_float32", "int32.to_float32"),
                ("int32_to_float64", "int32.to_float64"),
                ("int32_to_string", "int32.to_string"),
            ],
        ),
        (
            crate::embedded::SRC_HEX_ENCODE,
            &[("hex_encode", "hex.encode"), ("hex_encode_upper", "hex.encode_upper"), ("hex_decode", "hex.decode")],
        ),
        (
            crate::embedded::SRC_BASE64_ENCODE,
            &[("base64_encode", "base64.encode"), ("base64_encode_url", "base64.encode_url"), ("base64_decode", "base64.decode"), ("base64_decode_url", "base64.decode_url")],
        ),
        (
            crate::embedded::SRC_INT_ROTATE,
            &[("int_rotate_left", "int.rotate_left"), ("int_rotate_right", "int.rotate_right")],
        ),
        (
            crate::embedded::SRC_FLOAT_BITS,
            &[
                ("float_to_bits", "float.to_bits"),
                ("int_bits_to_float", "int.bits_to_float"),
                ("int_bits_to_f32", "int.bits_to_f32"),
            ],
        ),
        (crate::embedded::SRC_FAN_MAP, &[("fan_map", "fan.map"), ("fan_map_is", "fan.map_is"), ("fan_map_ss", "fan.map_ss"), ("fan_map_si", "fan.map_si")]),
        // The self-hosted regex ENGINE (Stage 1: is_match/full_match — v0's
        // runtime regex ported quirk-for-quirk; see stdlib/regex_engine.almd).
        (crate::embedded::SRC_REGEX_ENGINE, &[("regex_is_match", "regex.is_match"), ("regex_full_match", "regex.full_match"), ("regex_find", "regex.find"), ("regex_find_all", "regex.find_all"), ("regex_replace", "regex.replace"), ("regex_replace_first", "regex.replace_first"), ("regex_split", "regex.split"), ("regex_captures", "regex.captures")]),
        (crate::embedded::SRC_LIST_TO_STRING, &[("list_to_string", "list.to_string")]),
        (crate::embedded::SRC_LIST_TO_STRING_LL, &[("list_to_string_ll", "list.to_string_ll"), ("list_to_string_llf", "list.to_string_llf")]),
        (crate::embedded::SRC_LIST_TO_STRING_B, &[("list_to_string_b", "list.to_string_b")]),
        (crate::embedded::SRC_LIST_TO_STRING_S, &[("list_to_string_s", "list.to_string_s")]),
        (crate::embedded::SRC_LIST_TO_STRING_F, &[("list_to_string_f", "list.to_string_f")]),
        // `${Option[T]}` → `some(<T>)` / `none`, per element type (mirrors the List family).
        (crate::embedded::SRC_OPTION_TO_STRING, &[("option_to_string", "option.to_string")]),
        (crate::embedded::SRC_OPTION_TO_STRING_S, &[("option_to_string_s", "option.to_string_s")]),
        (crate::embedded::SRC_OPTION_TO_STRING_LI, &[("option_to_string_li", "option.to_string_li")]),
        (crate::embedded::SRC_OPTION_TO_STRING_OI, &[("option_to_string_oi", "option.to_string_oi")]),
        (crate::embedded::SRC_OPTION_TO_STRING_LS, &[("option_to_string_ls", "option.to_string_ls")]),
        (crate::embedded::SRC_OPTION_TO_STRING_MSI, &[("option_to_string_msi", "option.to_string_msi")]),
        (crate::embedded::SRC_OPTION_TO_STRING_LF, &[("option_to_string_lf", "option.to_string_lf")]),
        (crate::embedded::SRC_OPTION_TO_STRING_NESTED, &[("option_to_string_ob", "option.to_string_ob"), ("option_to_string_os", "option.to_string_os"), ("option_to_string_ri", "option.to_string_ri"), ("option_to_string_rs", "option.to_string_rs"), ("option_to_string_lb", "option.to_string_lb"), ("option_to_string_ooi", "option.to_string_ooi"), ("option_to_string_ooli", "option.to_string_ooli"), ("option_to_string_rli", "option.to_string_rli")]),
        (crate::embedded::SRC_OPTION_TO_STRING_F, &[("option_to_string_f", "option.to_string_f")]),
        (crate::embedded::SRC_OPTION_TO_STRING_B, &[("option_to_string_b", "option.to_string_b")]),
        (crate::embedded::SRC_RESULT_TO_STRING, &[("result_to_string", "result.to_string"), ("result_to_string_ss", "result.to_string_ss"), ("result_to_string_li", "result.to_string_li"), ("result_to_string_ls", "result.to_string_ls"), ("result_to_string_b", "result.to_string_b"), ("result_to_string_lb", "result.to_string_lb"), ("result_to_string_oi", "result.to_string_oi"), ("result_to_string_os", "result.to_string_os"), ("result_to_string_ri", "result.to_string_ri"), ("result_to_string_f", "result.to_string_f"), ("result_to_string_oli", "result.to_string_oli"), ("result_to_string_lf", "result.to_string_lf"), ("result_to_string_osl", "result.to_string_osl"), ("result_to_string_msi", "result.to_string_msi")]),
        (crate::embedded::SRC_SET_TO_STRING, &[("set_to_string", "set.to_string")]),
        (crate::embedded::SRC_SET_TO_STRING_S, &[("set_to_string_s", "set.to_string_s")]),
        (crate::embedded::SRC_MAP_TO_STRING, &[("map_to_string", "map.to_string"), ("map_to_string_ss", "map.to_string_ss"), ("map_to_string_sb", "map.to_string_sb"), ("map_to_string_sf", "map.to_string_sf")]),
        (crate::embedded::SRC_MAP_TYPECHANGE, &[("map_entries_core", "map.entries"), ("map_entries_hvalt", "map.entries_hvalt"), ("map_map_skv2str", "map.map_skv2str"), ("map_map_str2skv", "map.map_str2skv"), ("map_map_ivh2core", "map.map_ivh2core"), ("map_map_skv2hvalt", "map.map_skv2hvalt"), ("set_map_i2s", "set.map_i2s")]),
        (crate::embedded::SRC_BYTES_RAWPTR, &[("bytes_as_ptr", "bytes.as_ptr"), ("bytes_as_mut_ptr", "bytes.as_mut_ptr"), ("bytes_from_raw_ptr", "bytes.from_raw_ptr"), ("bytes_copy_to_ptr", "bytes.copy_to_ptr")]),
        (crate::embedded::SRC_LIST_TO_STRING_LO, &[("list_to_string_lo", "list.to_string_lo")]),
        (crate::embedded::SRC_LIST_TO_STRING_LOB, &[("list_to_string_lob", "list.to_string_lob")]),
        (crate::embedded::SRC_LIST_TO_STRING_LR, &[("list_to_string_lr", "list.to_string_lr")]),
        (crate::embedded::SRC_MAP_IF, &[("map_from_list_if", "map.from_list_if"), ("map_to_string_if", "map.to_string_if")]),
        // Single-value compound formatters for record/tuple Display (the `${record}`/`${tuple}`
        // form): a Float field drops the trailing ".0" like a List[Float] element, a String field
        // is quoted+escaped like a List[String] element. Both reuse the proven list-element logic.
        (crate::embedded::SRC_FLOAT_TO_STRING_COMPOUND, &[("float_to_string_compound", "float.to_string_compound")]),
        (crate::embedded::SRC_STRING_QUOTE, &[("string_quote", "string.quote")]),
        (crate::embedded::SRC_LIST_LEN, &[("list_len", "list.len"), ("list_length", "list.length")]),
        (crate::embedded::SRC_LIST_FLATTEN, &[("list_flatten", "list.flatten"), ("list_flatten_rc", "list.flatten_rc")]),
        (crate::embedded::SRC_LIST_CHUNK, &[("list_chunk", "list.chunk"), ("list_windows", "list.windows"), ("list_window", "list.window"), ("list_chunk_str", "list.chunk_str"), ("list_windows_str", "list.windows_str"), ("list_window_str", "list.window_str")]),
        (crate::embedded::SRC_RESULT_CORE, &[("result_is_ok", "result.is_ok"), ("result_is_err", "result.is_err"), ("result_unwrap_or", "result.unwrap_or"), ("result_to_option", "result.to_option"), ("result_to_list", "result.to_list"), ("result_zip", "result.zip"), ("result_is_ok_h", "result.is_ok_h"), ("result_is_err_h", "result.is_err_h")]),
        (crate::embedded::SRC_OPTION_COLLECT, &[("option_collect", "option.collect")]),
        (crate::embedded::SRC_OPTION_COLLECT_MAP, &[("option_collect_map", "option.collect_map")]),
        (crate::embedded::SRC_TESTING_ASSERT, &[("testing_assert_gt", "testing.assert_gt"), ("testing_assert_lt", "testing.assert_lt"), ("testing_assert_approx", "testing.assert_approx"), ("testing_assert_contains", "testing.assert_contains"), ("testing_assert_some", "testing.assert_some"), ("testing_assert_ok", "testing.assert_ok")]),
        (crate::embedded::SRC_OPTION_MAP, &[("option_map", "option.map"), ("option_map_h", "option.map_h"), ("option_filter_h", "option.filter_h"), ("option_flatten_h", "option.flatten_h"), ("option_unwrap_or_else_h", "option.unwrap_or_else_h"), ("option_or_else_h", "option.or_else_h"), ("option_filter", "option.filter"), ("option_flat_map", "option.flat_map"), ("option_unwrap_or_else", "option.unwrap_or_else"), ("option_or_else", "option.or_else"), ("option_to_result", "option.to_result"), ("option_to_result_h", "option.to_result_h"), ("option_flatten", "option.flatten"), ("option_zip", "option.zip")]),
        (crate::embedded::SRC_RESULT_MAP, &[("result_map", "result.map"), ("result_flat_map", "result.flat_map"), ("result_to_err_option", "result.to_err_option"), ("result_unwrap_or_else", "result.unwrap_or_else"), ("result_map_err", "result.map_err"), ("result_filter", "result.filter"), ("result_or_else", "result.or_else"), ("result_flatten", "result.flatten"), ("result_map_h", "result.map_h"), ("result_map_err_h", "result.map_err_h"), ("result_flat_map_h", "result.flat_map_h"), ("result_unwrap_or_else_h", "result.unwrap_or_else_h"), ("result_to_option_h", "result.to_option_h"), ("result_to_err_option_h", "result.to_err_option_h"), ("result_map_s2h", "result.map_s2h")]),
        (crate::embedded::SRC_STRING_TO_INT, &[("string_to_int", "int.parse"), ("int_from_hex", "int.from_hex")]),
        (crate::embedded::SRC_LIST_IS_EMPTY, &[("list_is_empty", "list.is_empty")]),
        (crate::embedded::SRC_LIST_SUM, &[("list_sum", "list.sum")]),
        (crate::embedded::SRC_LIST_SORT, &[("list_sort", "list.sort"), ("list_sort_str", "list.sort_str"), ("list_min_str", "list.min_str"), ("list_max_str", "list.max_str")]),
        (crate::embedded::SRC_LIST_ORD_COMPOUND, &[("list_sort_tss", "list.sort_tss"), ("list_sort_tsstr", "list.sort_tsstr"), ("list_sort_lint", "list.sort_lint"), ("list_sort_oint", "list.sort_oint"), ("list_min_tss", "list.min_tss"), ("list_max_tss", "list.max_tss"), ("list_min_tsstr", "list.min_tsstr"), ("list_max_tsstr", "list.max_tsstr"), ("list_min_lint", "list.min_lint"), ("list_max_lint", "list.max_lint"), ("list_min_lstr", "list.min_lstr"), ("list_max_lstr", "list.max_lstr"), ("list_min_oint", "list.min_oint"), ("list_max_oint", "list.max_oint")]),
        (crate::embedded::SRC_LIST_SORT_FLOAT, &[("list_sort_float", "list.sort_float")]),
        (crate::embedded::SRC_LIST_FOLD_FLOAT, &[("list_max_float", "list.max_float"), ("list_min_float", "list.min_float")]),
        (
            crate::embedded::SRC_MAP_IVH,
            &[("map_new_ivh", "map.new_ivh"), ("map_set_ivh", "map.set_ivh"), ("map_eq_ivh", "map.eq_ivh"), ("map_from_list_ivh", "map.from_list_ivh"), ("map_to_string_ivh", "map.to_string_ivh"), ("map_len_ivh", "map.len_ivh"), ("map_get_ivh", "map.get_ivh")],
        ),
        (
            crate::embedded::SRC_MAP_VKEY,
            &[("map_from_list_vtag", "map.from_list_vtag"), ("map_get_vtag", "map.get_vtag"), ("map_from_list_srec", "map.from_list_srec"), ("map_get_srec", "map.get_srec"), ("map_set_srec", "map.set_srec"), ("map_contains_srec", "map.contains_srec"), ("set_from_list_srec", "set.from_list_srec"), ("set_insert_srec", "set.insert_srec"), ("set_contains_srec", "set.contains_srec")],
        ),
        (
            crate::embedded::SRC_MAP_HVAL,
            &[("map_new_hval", "map.new_hval"), ("map_set_hval", "map.set_hval"), ("map_eq_hval", "map.eq_hval"), ("map_from_list_hval", "map.from_list_hval"), ("map_to_string_hval", "map.to_string_hval"), ("list_to_string_lmh", "list.to_string_lmh"), ("map_len_hval", "map.len_hval"), ("map_contains_hval", "map.contains_hval"), ("map_get_hval", "map.get_hval"), ("map_get_or_hval", "map.get_or_hval"), ("map_keys_hval", "map.keys_hval"), ("list_group_by", "list.group_by")],
        ),
        (crate::embedded::SRC_LIST_SORTBY_FLOAT, &[("list_sort_by_float", "list.sort_by_float"), ("list_sort_by_float_rc", "list.sort_by_float_rc")]),
        (crate::embedded::SRC_LIST_UNIQUE, &[("list_unique", "list.unique")]),
        (crate::embedded::SRC_LIST_DEDUP, &[("list_dedup", "list.dedup")]),
        (
            crate::embedded::SRC_LIST_INTERSPERSE,
            &[("list_intersperse", "list.intersperse")],
        ),
        (
            crate::embedded::SRC_INT_WRAP,
            &[
                ("int_wrap_add", "int.wrap_add"),
                ("int_wrap_mul", "int.wrap_mul"),
                ("int_to_u32", "int.to_u32"),
                ("int_to_u8", "int.to_u8"),
            ],
        ),
        (
            crate::embedded::SRC_INT_SIZED,
            INT_SIZED_FNS,
        ),
        (
            crate::embedded::SRC_INT_CHECKED,
            &[
                ("int_to_int8_checked", "int.to_int8_checked"),
                ("int_to_int16_checked", "int.to_int16_checked"),
                ("int_to_int32_checked", "int.to_int32_checked"),
                ("int_to_uint8_checked", "int.to_uint8_checked"),
                ("int_to_uint16_checked", "int.to_uint16_checked"),
                ("int_to_uint32_checked", "int.to_uint32_checked"),
                ("int_to_uint64_checked", "int.to_uint64_checked"),
                ("int_to_float32_checked", "int.to_float32_checked"),
            ],
        ),
        (
            crate::embedded::SRC_STRING_MUTATE,
            &[("string_clear", "string.clear")],
        ),
        (
            crate::embedded::SRC_FLOAT_SATURATING,
            &[
                ("float_to_int8_saturating", "float.to_int8_saturating"),
                ("float_to_int16_saturating", "float.to_int16_saturating"),
                ("float_to_int32_saturating", "float.to_int32_saturating"),
                ("float_to_int64_saturating", "float.to_int64_saturating"),
                ("float_to_uint8_saturating", "float.to_uint8_saturating"),
                ("float_to_uint16_saturating", "float.to_uint16_saturating"),
                ("float_to_uint32_saturating", "float.to_uint32_saturating"),
                ("float_to_uint64_saturating", "float.to_uint64_saturating"),
            ],
        ),
        (crate::embedded::SRC_STRING_SLICE, &[("string_slice", "string.slice")]),
        (crate::embedded::SRC_STRING_SLICE2, &[("string_slice2", "string.slice2")]),
        (crate::embedded::SRC_STRING_TO_LOWER, &[("string_to_lower", "string.to_lower")]),
        (crate::embedded::SRC_STRING_TO_UPPER, &[("string_to_upper", "string.to_upper")]),
        (crate::embedded::SRC_FLOAT_PARSE, &[("float_parse", "float.parse")]),
        (crate::embedded::SRC_LIST_ENUMERATE, &[("list_enumerate_str", "list.enumerate_str")]),
        (crate::embedded::SRC_LIST_FIND_INT_STR, &[("list_find_int_str", "list.find_int_str")]),
        (
            crate::embedded::SRC_STRING_IS_DIGIT,
            &[("string_is_digit", "string.is_digit")],
        ),
        (
            crate::embedded::SRC_STRING_FROM_CODEPOINT,
            &[("string_from_codepoint", "string.from_codepoint")],
        ),
        (
            crate::embedded::SRC_STRING_CODEPOINT,
            &[("string_codepoint", "string.codepoint")],
        ),
        (
            crate::embedded::SRC_STRING_TAKE_DROP,
            &[
                ("string_take", "string.take"),
                ("string_take_end", "string.take_end"),
                ("string_drop", "string.drop"),
                ("string_drop_end", "string.drop_end"),
            ],
        ),
        (
            crate::embedded::SRC_STRING_TO_BYTES,
            &[("string_to_bytes", "string.to_bytes")],
        ),
        (
            crate::embedded::SRC_STRING_FROM_BYTES_SELF,
            &[("string_from_bytes", "string.from_bytes")],
        ),
        (
            crate::embedded::SRC_STRING_FIRST_LAST,
            &[
                ("string_first", "string.first"), ("string_last", "string.last"),
                ("string_char_at", "string.get"),
                ("string_strip_prefix", "string.strip_prefix"),
                ("string_strip_suffix", "string.strip_suffix"),
                ("string_is_whitespace", "string.is_whitespace"),
            ],
        ),
        (
            crate::embedded::SRC_STRING_TRIM,
            &[
                ("string_trim", "string.trim"),
                ("string_trim_start", "string.trim_start"),
                ("string_trim_end", "string.trim_end"),
            ],
        ),
        (crate::embedded::SRC_STRING_REVERSE, &[("string_reverse", "string.reverse")]),
        (
            crate::embedded::SRC_STRING_REPLACE,
            &[
                ("string_replace", "string.replace"),
                ("string_replace_first", "string.replace_first"),
            ],
        ),
        (
            crate::embedded::SRC_STRING_PAD,
            &[("string_pad_start", "string.pad_start"), ("string_pad_end", "string.pad_end")],
        ),
        (crate::embedded::SRC_LIST_GET_OR, &[("list_get_or", "list.get_or")]),
        (crate::embedded::SRC_LIST_GET_OR_STR, &[("list_get_or_str", "list.get_or_str")]),
        (
            crate::embedded::SRC_INT_BITCOUNT,
            &[
                ("int_pop_count", "int.pop_count"),
                ("int_count_trailing_zeros", "int.count_trailing_zeros"),
                ("int_count_leading_zeros", "int.count_leading_zeros"),
                ("int_bit_width", "int.bit_width"),
                ("int_log2_floor", "int.log2_floor"),
                ("int_log2_ceil", "int.log2_ceil"),
                ("int_next_power_of_two", "int.next_power_of_two"),
                ("int_prev_power_of_two", "int.prev_power_of_two"),
            ],
        ),
        (
            crate::embedded::SRC_INT_BITS,
            &[
                ("int_band", "int.band"),
                ("int_bor", "int.bor"),
                ("int_bxor", "int.bxor"),
                ("int_bshl", "int.bshl"),
                ("int_bshr", "int.bshr"),
                ("int_bnot", "int.bnot"),
                ("int_byte_swap", "int.byte_swap"),
                ("int_bit_reverse", "int.bit_reverse"),
            ],
        ),
        (crate::embedded::SRC_INT_HEX, &[("int_to_hex", "int.to_hex")]),
        (
            crate::embedded::SRC_INT_SCALAR,
            &[
                ("int_abs", "int.abs"),
                ("int_min", "int.min"),
                ("int_max", "int.max"),
                ("int_clamp", "int.clamp"),
            ],
        ),
        (
            crate::embedded::SRC_LIST_GET,
            &[("list_get", "list.get"), ("list_first", "list.first"), ("list_last", "list.last")],
        ),
        (
            crate::embedded::SRC_LIST_SEARCH,
            &[
                ("list_contains", "list.contains"),
                ("list_index_of", "list.index_of"),
                ("list_binary_search", "list.binary_search"),
            ],
        ),
        (crate::embedded::SRC_LIST_REVERSE, &[("list_reverse", "list.reverse")]),
        (
            crate::embedded::SRC_LIST_MAKE,
            &[("list_range", "list.range"), ("list_repeat", "list.repeat"), ("list_repeat_rc", "list.repeat_rc"), ("list_with_capacity", "list.with_capacity")],
        ),
        (
            crate::embedded::SRC_LIST_TAKE_DROP,
            &[
                ("list_take", "list.take"),
                ("list_drop", "list.drop"),
                ("list_slice", "list.slice"),
            ],
        ),
        (crate::embedded::SRC_LIST_POP, &[("list_pop", "list.pop")]),
        (
            crate::embedded::SRC_LIST_FOLD,
            &[
                ("list_product", "list.product"),
                ("list_max", "list.max"),
                ("list_min", "list.min"),
            ],
        ),
        (
            crate::embedded::SRC_STRING_SEARCH,
            &[
                ("string_starts_with", "string.starts_with"),
                ("string_ends_with", "string.ends_with"),
                ("string_contains", "string.contains"),
                ("string_count", "string.count"),
                ("string_index_of", "string.index_of"),
                ("string_last_index_of", "string.last_index_of"),
            ],
        ),
    ]
}

include!("self_host_fn_tables.rs");
