const __almd_float = {
  to_string(n: number): string { const s = String(n); return s.includes('.') || s.includes('e') ? s : s + '.0'; },
  to_int(n: number): number { return Math.trunc(n); },
  round(n: number): number { return Math.round(n); },
  floor(n: number): number { return Math.floor(n); },
  ceil(n: number): number { return Math.ceil(n); },
  abs(n: number): number { return Math.abs(n); },
  sqrt(n: number): number { return Math.sqrt(n); },
  parse(s: string): number { const n = parseFloat(s); if (isNaN(n)) throw new Error("invalid float: " + s); return n; },
  from_int(n: number): number { return n; },
  min(a: number, b: number): number { return Math.min(a, b); },
  max(a: number, b: number): number { return Math.max(a, b); },
  clamp(n: number, lo: number, hi: number): number { return Math.max(lo, Math.min(hi, n)); },
  to_fixed(n: number, decimals: number): string { return n.toFixed(decimals); },
};
