const __almd_http = {
  async serve(port: number, handler: (req: any) => any): Promise<void> { const server = Deno.serve({ port }, async (request: Request) => { const url = new URL(request.url); const method = request.method; const path = url.pathname; const body = method === "POST" || method === "PUT" ? await request.text() : ""; const headers: Record<string, string> = {}; request.headers.forEach((v: string, k: string) => { headers[k] = v; }); const req = { method, path, body, headers }; const res = handler(req); return new Response(res.body, { status: res.status, headers: res.headers || {} }); }); },
  response(status: number, body: string): any { return { status, body, headers: { "content-type": "text/plain" } }; },
  json(status: number, body: string): any { return { status, body, headers: { "content-type": "application/json" } }; },
  with_headers(status: number, body: string, headers: any): any { const h: Record<string, string> = {}; if (headers instanceof Map) { headers.forEach((v: string, k: string) => { h[k] = v; }); } else { Object.assign(h, headers); } return { status, body, headers: h }; },
  async get(url: string): Promise<string> { const r = await fetch(url); if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.text(); },
  async post(url: string, body: string): Promise<string> { const r = await fetch(url, { method: "POST", body, headers: { "content-type": "application/json" } }); if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.text(); },
  async get_with_headers(url: string, headers: Map<string, string>): Promise<string> { const h: Record<string, string> = {}; headers.forEach((v, k) => { h[k] = v; }); const r = await fetch(url, { headers: h }); if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.text(); },
  async request(method: string, url: string, body: string, headers: Map<string, string>): Promise<string> { const h: Record<string, string> = {}; headers.forEach((v, k) => { h[k] = v; }); const opts: any = { method, headers: h }; if (body) opts.body = body; const r = await fetch(url, opts); if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.text(); },
};
