const __almd_int = {
  to_hex(n: bigint): string { return (n >= 0n ? n : n + (1n << 64n)).toString(16); },
  to_string(n: number): string { return String(n); },
  band(a: number, b: number): number { return (a & b) >>> 0; },
  bor(a: number, b: number): number { return (a | b) >>> 0; },
  bxor(a: number, b: number): number { return (a ^ b) >>> 0; },
  bshl(a: number, n: number): number { return (a << n) >>> 0; },
  bshr(a: number, n: number): number { return a >>> n; },
  bnot(a: number): number { return ~a; },
  wrap_add(a: number, b: number, bits: number): number { const mask = bits === 32 ? 0xFFFFFFFF : (1 << bits) - 1; return ((a + b) & mask) >>> 0; },
  wrap_mul(a: number, b: number, bits: number): number { const mask = bits === 32 ? 0xFFFFFFFF : (1 << bits) - 1; return (Math.imul(a, b) & mask) >>> 0; },
  rotate_right(a: number, n: number, bits: number): number { const mask = bits === 32 ? 0xFFFFFFFF : (1 << bits) - 1; const v = a & mask; n = n % bits; return (((v >>> n) | (v << (bits - n))) & mask) >>> 0; },
  rotate_left(a: number, n: number, bits: number): number { const mask = bits === 32 ? 0xFFFFFFFF : (1 << bits) - 1; const v = a & mask; n = n % bits; return (((v << n) | (v >>> (bits - n))) & mask) >>> 0; },
  to_u32(a: number): number { return a >>> 0; },
  to_u8(a: number): number { return a & 0xFF; },
  clamp(n: number, lo: number, hi: number): number { return Math.max(lo, Math.min(hi, n)); },
  parse(s: string): number { const n = parseInt(s, 10); if (isNaN(n) || !/^-?\d+$/.test(s.trim())) throw new Error("invalid digit found in string"); return n; },
  parse_hex(s: string): number { const h = s.startsWith("0x") || s.startsWith("0X") ? s.slice(2) : s; const n = parseInt(h, 16); if (isNaN(n)) throw new Error("invalid digit found in string"); return n; },
  abs(n: number): number { return Math.abs(n); },
  min(a: number, b: number): number { return Math.min(a, b); },
  max(a: number, b: number): number { return Math.max(a, b); },
  to_float(n: number): number { return n; },
};
