const __almd_json = {
  parse(text: string): any { return JSON.parse(text); },
  stringify(j: any): string { return JSON.stringify(j); },
  get(j: any, key: string): any | null { return (j && typeof j === "object" && !Array.isArray(j) && key in j) ? j[key] : null; },
  get_string(j: any, key: string): string | null { const v = __almd_json.get(j, key); return typeof v === "string" ? v : null; },
  get_int(j: any, key: string): number | null { const v = __almd_json.get(j, key); return typeof v === "number" ? v : null; },
  get_bool(j: any, key: string): boolean | null { const v = __almd_json.get(j, key); return typeof v === "boolean" ? v : null; },
  get_array(j: any, key: string): any[] | null { const v = __almd_json.get(j, key); return Array.isArray(v) ? v : null; },
  keys(j: any): string[] { return (j && typeof j === "object" && !Array.isArray(j)) ? Object.keys(j).sort() : []; },
  to_string(j: any): string | null { return typeof j === "string" ? j : null; },
  to_int(j: any): number | null { return typeof j === "number" ? j : null; },
  from_string(s: string): any { return s; },
  from_int(n: number): any { return n; },
  from_bool(b: boolean): any { return b; },
  null_(): any { return null; },
  array(items: any[]): any { return items; },
  from_map(m: any): any { if (m instanceof Map) { const o: any = {}; m.forEach((v: any, k: string) => { o[k] = v; }); return o; } return m; },
  get_float(j: any, key: string): number | null { const v = __almd_json.get(j, key); return typeof v === "number" ? v : null; },
  from_float(n: number): any { return n; },
  stringify_pretty(j: any): string { return JSON.stringify(j, null, 2); },
  object(entries: [string, any][]): any { const o: any = {}; for (const [k, v] of entries) { o[k] = v; } return o; },
  as_float(j: any): number | null { return typeof j === "number" ? j : null; },
  as_bool(j: any): boolean | null { return typeof j === "boolean" ? j : null; },
  as_array(j: any): any[] | null { return Array.isArray(j) ? j : null; },
  path_root(): any { return { type: "root" }; },
  path_field(parent: any, name: string): any { return { type: "field", parent, name }; },
  path_index(parent: any, i: number): any { return { type: "index", parent, i }; },
  _path_segs(p: any): any[] { const s: any[] = []; let c = p; while (c.type !== "root") { s.push(c); c = c.parent; } s.reverse(); return s; },
  get_path(j: any, path: any): any | null { const segs = __almd_json._path_segs(path); let cur = j; for (const seg of segs) { if (seg.type === "field") { if (cur == null || typeof cur !== "object" || Array.isArray(cur)) return null; cur = cur[seg.name]; if (cur === undefined) return null; } else { if (!Array.isArray(cur) || seg.i < 0 || seg.i >= cur.length) return null; cur = cur[seg.i]; } } return cur; },
  set_path(j: any, path: any, value: any): any { const segs = __almd_json._path_segs(path); if (segs.length === 0) return value; return __almd_json._set_at(j, segs, 0, value, false); },
  upsert_path(j: any, path: any, value: any): any { const segs = __almd_json._path_segs(path); if (segs.length === 0) return value; return __almd_json._set_at(j, segs, 0, value, true); },
  remove_path(j: any, path: any): any { const segs = __almd_json._path_segs(path); if (segs.length === 0) return null; return __almd_json._remove_at(j, segs, 0); },
  _set_at(j: any, segs: any[], idx: number, value: any, upsert: boolean): any { if (idx >= segs.length) return value; const seg = segs[idx]; if (seg.type === "field") { let m = (j && typeof j === "object" && !Array.isArray(j)) ? { ...j } : (upsert ? {} : (() => { throw new Error(`path error: expected object at field "${seg.name}"`); })()); if (idx + 1 === segs.length) { if (!upsert && !(seg.name in m)) throw new Error(`path error: field "${seg.name}" does not exist`); m[seg.name] = value; } else { m[seg.name] = __almd_json._set_at(m[seg.name] ?? null, segs, idx + 1, value, upsert); } return m; } else { if (!Array.isArray(j)) throw new Error(`path error: expected array at index ${seg.i}`); if (seg.i < 0 || seg.i >= j.length) throw new Error(`path error: index ${seg.i} out of bounds`); const a = [...j]; if (idx + 1 === segs.length) { a[seg.i] = value; } else { a[seg.i] = __almd_json._set_at(a[seg.i], segs, idx + 1, value, upsert); } return a; } },
  _remove_at(j: any, segs: any[], idx: number): any { if (idx >= segs.length) return j; const seg = segs[idx]; if (seg.type === "field") { if (!j || typeof j !== "object" || Array.isArray(j)) return j; const m = { ...j }; if (idx + 1 === segs.length) { delete m[seg.name]; } else if (seg.name in m) { m[seg.name] = __almd_json._remove_at(m[seg.name], segs, idx + 1); } return m; } else { if (!Array.isArray(j) || seg.i < 0 || seg.i >= j.length) return j; const a = [...j]; if (idx + 1 === segs.length) { a.splice(seg.i, 1); } else { a[seg.i] = __almd_json._remove_at(a[seg.i], segs, idx + 1); } return a; } },
};
