const __almd_list = {
  len<T>(xs: T[]): number { return xs.length; },
  get<T>(xs: T[], i: number): T | null { return (i >= 0 && i < xs.length) ? xs[i] : null; },
  get_or<T>(xs: T[], i: number, d: T): T { return (i >= 0 && i < xs.length) ? xs[i] : d; },
  set<T>(xs: T[], i: number, v: T): T[] { const r = [...xs]; if (i >= 0 && i < r.length) r[i] = v; return r; },
  swap<T>(xs: T[], i: number, j: number): T[] { const r = [...xs]; if (i >= 0 && i < r.length && j >= 0 && j < r.length) { const t = r[i]; r[i] = r[j]; r[j] = t; } return r; },
  sort<T>(xs: T[]): T[] { return [...xs].sort(); },
  reverse<T>(xs: T[]): T[] { return [...xs].reverse(); },
  any<T>(xs: T[], f: (x: T) => boolean): boolean { return xs.some(f); },
  all<T>(xs: T[], f: (x: T) => boolean): boolean { return xs.every(f); },
  contains<T>(xs: T[], x: T): boolean { return xs.includes(x); },
  each<T>(xs: T[], f: (x: T) => void): void { xs.forEach(f); },
  map<T, U>(xs: T[], f: (x: T) => U): U[] { return xs.map(f); },
  filter<T>(xs: T[], f: (x: T) => boolean): T[] { return xs.filter(f); },
  find<T>(xs: T[], f: (x: T) => boolean): T | null { return xs.find(f) ?? null; },
  fold<T, U>(xs: T[], init: U, f: (acc: U, x: T) => U): U { return xs.reduce(f, init); },
  enumerate<T>(xs: T[]): [number, T][] { return xs.map((x, i) => [i, x]); },
  zip<T, U>(a: T[], b: U[]): [T, U][] { return a.slice(0, Math.min(a.length, b.length)).map((x, i) => [x, b[i]]); },
  flatten<T>(xss: T[][]): T[] { return xss.flat(); },
  take<T>(xs: T[], n: number): T[] { return xs.slice(0, n); },
  drop<T>(xs: T[], n: number): T[] { return xs.slice(n); },
  sort_by<T>(xs: T[], f: (x: T) => any): T[] { return [...xs].sort((a, b) => { const ka = f(a), kb = f(b); return ka < kb ? -1 : ka > kb ? 1 : 0; }); },
  unique<T>(xs: T[]): T[] { const seen: T[] = []; return xs.filter(x => { if (seen.includes(x)) return false; seen.push(x); return true; }); },
  index_of<T>(xs: T[], x: T): number | null { const i = xs.indexOf(x); return i >= 0 ? i : null; },
  chunk<T>(xs: T[], n: number): T[][] { const r: T[][] = []; for (let i = 0; i < xs.length; i += n) r.push(xs.slice(i, i + n)); return r; },
  filter_map<T, U>(xs: T[], f: (x: T) => U | null): U[] { const r: U[] = []; for (const x of xs) { const v = f(x); if (v !== null) r.push(v); } return r; },
  take_while<T>(xs: T[], f: (x: T) => boolean): T[] { const r: T[] = []; for (const x of xs) { if (!f(x)) break; r.push(x); } return r; },
  drop_while<T>(xs: T[], f: (x: T) => boolean): T[] { let dropping = true; const r: T[] = []; for (const x of xs) { if (dropping && f(x)) continue; dropping = false; r.push(x); } return r; },
  count<T>(xs: T[], f: (x: T) => boolean): number { return xs.filter(f).length; },
  partition<T>(xs: T[], f: (x: T) => boolean): [T[], T[]] { const a: T[] = [], b: T[] = []; for (const x of xs) { if (f(x)) a.push(x); else b.push(x); } return [a, b]; },
  reduce<T>(xs: T[], f: (a: T, b: T) => T): T | null { if (xs.length === 0) return null; return xs.reduce(f); },
  group_by<T, K>(xs: T[], f: (x: T) => K): Map<K, T[]> { const m = new Map<K, T[]>(); for (const x of xs) { const k = f(x); if (!m.has(k)) m.set(k, []); m.get(k)!.push(x); } return m; },
  last<T>(xs: T[]): T | null { return xs.length > 0 ? xs[xs.length - 1] : null; },
  first<T>(xs: T[]): T | null { return xs.length > 0 ? xs[0] : null; },
  sum(xs: number[]): number { return xs.reduce((a, b) => a + b, 0); },
  product(xs: number[]): number { return xs.reduce((a, b) => a * b, 1); },
  is_empty<T>(xs: T[]): boolean { return xs.length === 0; },
  flat_map<T, U>(xs: T[], f: (x: T) => U[]): U[] { return xs.flatMap(f); },
  min<T>(xs: T[]): T | null { return xs.length === 0 ? null : xs.reduce((a, b) => a < b ? a : b); },
  max<T>(xs: T[]): T | null { return xs.length === 0 ? null : xs.reduce((a, b) => a > b ? a : b); },
  join(xs: string[], sep: string): string { return xs.join(sep); },
  range(start: number, end: number): number[] { const r: number[] = []; for (let i = start; i < end; i++) r.push(i); return r; },
  slice<T>(xs: T[], start: number, end: number): T[] { return xs.slice(start, end); },
  insert<T>(xs: T[], i: number, v: T): T[] { const r = [...xs]; r.splice(i, 0, v); return r; },
  remove_at<T>(xs: T[], i: number): T[] { const r = [...xs]; if (i >= 0 && i < r.length) r.splice(i, 1); return r; },
  find_index<T>(xs: T[], f: (x: T) => boolean): number | null { const i = xs.findIndex(f); return i >= 0 ? i : null; },
  update<T>(xs: T[], i: number, f: (x: T) => T): T[] { const r = [...xs]; if (i >= 0 && i < r.length) r[i] = f(r[i]); return r; },
  repeat<T>(v: T, n: number): T[] { return Array(Math.max(0, n)).fill(v); },
  scan<T, U>(xs: T[], init: U, f: (acc: U, x: T) => U): U[] { let acc = init; return xs.map(x => { acc = f(acc, x); return acc; }); },
  intersperse<T>(xs: T[], sep: T): T[] { const r: T[] = []; xs.forEach((x, i) => { if (i > 0) r.push(sep); r.push(x); }); return r; },
  windows<T>(xs: T[], n: number): T[][] { if (n <= 0 || n > xs.length) return []; const r: T[][] = []; for (let i = 0; i <= xs.length - n; i++) r.push(xs.slice(i, i + n)); return r; },
  dedup<T>(xs: T[]): T[] { const r: T[] = []; for (const x of xs) { if (r.length === 0 || r[r.length - 1] !== x) r.push(x); } return r; },
  zip_with<A, B, C>(a: A[], b: B[], f: (x: A, y: B) => C): C[] { return a.slice(0, Math.min(a.length, b.length)).map((x, i) => f(x, b[i])); },
  sum_float(xs: number[]): number { return xs.reduce((a, b) => a + b, 0); },
  product_float(xs: number[]): number { return xs.reduce((a, b) => a * b, 1); },
  take_end<T>(xs: T[], n: number): T[] { return n >= xs.length ? xs.slice() : xs.slice(xs.length - n); },
  drop_end<T>(xs: T[], n: number): T[] { return n >= xs.length ? [] : xs.slice(0, xs.length - n); },
  unique_by<T, K>(xs: T[], f: (x: T) => K): T[] { const seen = new Set<K>(); return xs.filter(x => { const k = f(x); if (seen.has(k)) return false; seen.add(k); return true; }); },
  shuffle<T>(xs: T[]): T[] { const r = [...xs]; for (let i = r.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [r[i], r[j]] = [r[j], r[i]]; } return r; },
  window<T>(xs: T[], n: number): T[][] { const r: T[][] = []; for (let i = 0; i <= xs.length - n; i++) r.push(xs.slice(i, i + n)); return r; },
  pop<T>(xs: T[]): T | null { return xs.length > 0 ? xs.pop()! : null; },
};
