const __almd_set = {
  insert<T>(s: Set<T>, v: T): Set<T> { const r = new Set(s); r.add(v); return r; },
  remove<T>(s: Set<T>, v: T): Set<T> { const r = new Set(s); r.delete(v); return r; },
  union<T>(a: Set<T>, b: Set<T>): Set<T> { const r = new Set(a); for (const v of b) r.add(v); return r; },
  intersection<T>(a: Set<T>, b: Set<T>): Set<T> { const r = new Set<T>(); for (const v of a) { if (b.has(v)) r.add(v); } return r; },
  difference<T>(a: Set<T>, b: Set<T>): Set<T> { const r = new Set<T>(); for (const v of a) { if (!b.has(v)) r.add(v); } return r; },
  symmetric_difference<T>(a: Set<T>, b: Set<T>): Set<T> { const r = new Set<T>(); for (const v of a) { if (!b.has(v)) r.add(v); } for (const v of b) { if (!a.has(v)) r.add(v); } return r; },
  is_subset<T>(a: Set<T>, b: Set<T>): boolean { for (const v of a) { if (!b.has(v)) return false; } return true; },
  is_disjoint<T>(a: Set<T>, b: Set<T>): boolean { for (const v of a) { if (b.has(v)) return false; } return true; },
  filter<T>(s: Set<T>, f: (x: T) => boolean): Set<T> { const r = new Set<T>(); for (const v of s) { if (f(v)) r.add(v); } return r; },
  map<T, U>(s: Set<T>, f: (x: T) => U): Set<U> { const r = new Set<U>(); for (const v of s) r.add(f(v)); return r; },
  fold<T, B>(s: Set<T>, init: B, f: (acc: B, x: T) => B): B { let acc = init; for (const v of s) acc = f(acc, v); return acc; },
  each<T>(s: Set<T>, f: (x: T) => void): void { for (const v of s) f(v); },
  any<T>(s: Set<T>, f: (x: T) => boolean): boolean { for (const v of s) { if (f(v)) return true; } return false; },
  all<T>(s: Set<T>, f: (x: T) => boolean): boolean { for (const v of s) { if (!f(v)) return false; } return true; },
};
