const __almd_value = {
  field(v: any, key: string): any { if (v && typeof v === "object" && key in v) return v[key]; throw new Error(`key not found: ${key}`); },
  as_string(v: any): string { if (typeof v === "string") return v; throw new Error(`expected string, got ${typeof v}`); },
  as_int(v: any): number { if (typeof v === "number" && Number.isInteger(v)) return v; throw new Error(`expected int, got ${typeof v}`); },
  as_float(v: any): number { if (typeof v === "number") return v; throw new Error(`expected float, got ${typeof v}`); },
  as_bool(v: any): boolean { if (typeof v === "boolean") return v; throw new Error(`expected bool, got ${typeof v}`); },
  as_array(v: any): any[] { if (Array.isArray(v)) return v; throw new Error(`expected array, got ${typeof v}`); },
  str(s: string): any { return s; },
  int(n: number): any { return n; },
  float(f: number): any { return f; },
  bool(b: boolean): any { return b; },
  object(pairs: [string, any][]): any { const o: Record<string, any> = {}; for (const [k, v] of pairs) o[k] = v; return o; },
  array(items: any[]): any { return items; },
  pick(v: any, keys: string[]): any { const o: Record<string, any> = {}; for (const k of keys) if (k in v) o[k] = v[k]; return o; },
  omit(v: any, keys: string[]): any { const s = new Set(keys); const o: Record<string, any> = {}; for (const k in v) if (!s.has(k)) o[k] = v[k]; return o; },
  merge(a: any, b: any): any { return { ...a, ...b }; },
  to_camel_case(v: any): any { if (typeof v !== "object" || v === null || Array.isArray(v)) return v; const o: Record<string, any> = {}; for (const k in v) { const cc = k.replace(/_([a-z])/g, (_, c) => c.toUpperCase()); o[cc] = __almd_value.to_camel_case(v[k]); } return o; },
  to_snake_case(v: any): any { if (typeof v !== "object" || v === null || Array.isArray(v)) return v; const o: Record<string, any> = {}; for (const k in v) { const sc = k.replace(/[A-Z]/g, c => "_" + c.toLowerCase()); o[sc] = __almd_value.to_snake_case(v[k]); } return o; },
};
