//! Matrix stdlib call dispatch for WASM codegen.
//!
//! Memory layout: [rows:i32][cols:i32][data:f64...]  (row-major, 8 bytes per element)
//! Total size: 8 + rows*cols*8

use super::FuncCompiler;
use almide_ir::{IrExpr, IrExprKind, CallTarget};
use almide_lang::types::Ty;
use almide_base::intern::sym;

// @rewrite-derived desugar fallback: fused matrix op + args -> primitive
// composition IR. Generated by buildscript/matrix_desugar.rs from the SAME
// stdlib @rewrite rules that drive fusion (forward); this is the reverse. Shares
// this module's IrExpr / IrExprKind / CallTarget / Ty / sym imports.
include!("../generated/matrix_desugar_gen.rs");

impl FuncCompiler<'_> {
    /// Dispatch a matrix stdlib method call. Returns true if handled.
    pub(super) fn emit_matrix_call(&mut self, method: &str, args: &[IrExpr]) -> bool {
        // WASM matrix runtime is f64-only. The _f32 variants of primitive ops
        // are preview API surfaces for the native path; on WASM they dispatch
        // to their f64 equivalents (storage & arithmetic identical at this
        // layer).
        let method = match method {
            "zeros_f32" => "zeros",
            "ones_f32" => "ones",
            "mul_f32" => "mul",
            _ => method,
        };
        // mul_scaled / mul_f32_scaled: alpha * A * B — emit as scale(mul(a, b), alpha).
        if method == "mul_scaled" || method == "mul_f32_scaled" {
            let mul_call = IrExpr {
                kind: IrExprKind::Call {
                    target: CallTarget::Module { module: sym("matrix"), func: sym("mul"), def_id: None },
                    args: vec![args[0].clone(), args[2].clone()],
                    type_args: vec![],
                },
                ty: Ty::Matrix,
                span: None, def_id: None,
            };
            let scale_args = vec![mul_call, args[1].clone()];
            return self.emit_matrix_call("scale", &scale_args);
        }
        // mul_f32_t / mul_f32_t_scaled: A @ B^T — emit transpose(B) then mul.
        if method == "mul_f32_t" {
            let transpose_call = IrExpr {
                kind: IrExprKind::Call {
                    target: CallTarget::Module { module: sym("matrix"), func: sym("transpose"), def_id: None },
                    args: vec![args[1].clone()],
                    type_args: vec![],
                },
                ty: Ty::Matrix,
                span: None, def_id: None,
            };
            return self.emit_matrix_call("mul", &[args[0].clone(), transpose_call]);
        }
        if method == "mul_f32_t_scaled" {
            let transpose_call = IrExpr {
                kind: IrExprKind::Call {
                    target: CallTarget::Module { module: sym("matrix"), func: sym("transpose"), def_id: None },
                    args: vec![args[2].clone()],
                    type_args: vec![],
                },
                ty: Ty::Matrix,
                span: None, def_id: None,
            };
            return self.emit_matrix_call("mul_scaled", &[args[0].clone(), args[1].clone(), transpose_call]);
        }
        // Disjoint sub-match groups (behavior-preserving split of the giant
        // dispatcher). Each group matches a distinct, non-overlapping set of
        // method strings, so chain order is irrelevant. See calls_matrix_p2..p5.
        if self.emit_matrix_call_g2(method, args) { return true; }
        if self.emit_matrix_call_g3(method, args) { return true; }
        if self.emit_matrix_call_g4(method, args) { return true; }
        if self.emit_matrix_call_g5(method, args) { return true; }
        match method {
            "zeros" | "ones" => {
                // matrix.zeros(rows, cols) / matrix.ones(rows, cols) → Matrix
                let rows = self.scratch.alloc_i32();
                let cols = self.scratch.alloc_i32();
                let ptr = self.scratch.alloc_i32();
                let total = self.scratch.alloc_i32();
                self.emit_expr(&args[0]);
                wasm!(self.func, { i32_wrap_i64; local_set(rows); });
                self.emit_expr(&args[1]);
                wasm!(self.func, {
                    i32_wrap_i64; local_set(cols);
                    // total_bytes = 8 + rows*cols*8
                    local_get(rows); local_get(cols); i32_mul; local_set(total);
                    local_get(total); i32_const(8); i32_mul; i32_const(self.emitter.layout_reg.header_size(super::engine::layout::LIST) as i32); i32_add;
                    call(self.emitter.rt.alloc);
                    local_set(ptr);
                    // store rows, cols
                    local_get(ptr); local_get(rows); i32_store(0);
                    local_get(ptr); local_get(cols); i32_store(4);
                });
                if method == "zeros" {
                    // zero-fill data
                    wasm!(self.func, {
                        local_get(ptr); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                        i32_const(0);
                        local_get(total); i32_const(8); i32_mul;
                        memory_fill;
                    });
                } else {
                    // fill with 1.0
                    let i = self.scratch.alloc_i32();
                    wasm!(self.func, {
                        i32_const(0); local_set(i);
                        block_empty; loop_empty;
                          local_get(i); local_get(total); i32_ge_u; br_if(1);
                          local_get(ptr); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                          local_get(i); i32_const(8); i32_mul; i32_add;
                          f64_const(1.0);
                          f64_store(0);
                          local_get(i); i32_const(1); i32_add; local_set(i);
                          br(0);
                        end; end;
                    });
                    self.scratch.free_i32(i);
                }
                wasm!(self.func, { local_get(ptr); });
                self.scratch.free_i32(total);
                self.scratch.free_i32(ptr);
                self.scratch.free_i32(cols);
                self.scratch.free_i32(rows);
            }
            "rows" => {
                self.emit_expr(&args[0]);
                wasm!(self.func, { i32_load(0); i64_extend_i32_u; });
            }
            "cols" => {
                self.emit_expr(&args[0]);
                wasm!(self.func, { i32_load(4); i64_extend_i32_u; });
            }
            "shape" => {
                // Returns (Int, Int) as a tuple: [fst:i64][snd:i64]
                let m = self.scratch.alloc_i32();
                let t = self.scratch.alloc_i32();
                self.emit_expr(&args[0]);
                wasm!(self.func, {
                    local_set(m);
                    i32_const(16); call(self.emitter.rt.alloc); local_set(t);
                    local_get(t);
                    local_get(m); i32_load(0); i64_extend_i32_u;
                    i64_store(0);
                    local_get(t);
                    local_get(m); i32_load(4); i64_extend_i32_u;
                    i64_store(8);
                    local_get(t);
                });
                self.scratch.free_i32(t);
                self.scratch.free_i32(m);
            }
            "get" => {
                // matrix.get(m, row, col) → Float (f64)
                let m = self.scratch.alloc_i32();
                let row = self.scratch.alloc_i32();
                let col = self.scratch.alloc_i32();
                self.emit_expr(&args[0]);
                wasm!(self.func, { local_set(m); });
                self.emit_expr(&args[1]);
                wasm!(self.func, { i32_wrap_i64; local_set(row); });
                self.emit_expr(&args[2]);
                wasm!(self.func, {
                    i32_wrap_i64; local_set(col);
                    // offset = 8 + (row * cols + col) * 8
                    local_get(m); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                    local_get(row); local_get(m); i32_load(4); i32_mul;
                    local_get(col); i32_add;
                    i32_const(8); i32_mul;
                    i32_add;
                    f64_load(0);
                });
                self.scratch.free_i32(col);
                self.scratch.free_i32(row);
                self.scratch.free_i32(m);
            }
            "transpose" => {
                let src = self.scratch.alloc_i32();
                let dst = self.scratch.alloc_i32();
                let r = self.scratch.alloc_i32();
                let c = self.scratch.alloc_i32();
                let rows = self.scratch.alloc_i32();
                let cols = self.scratch.alloc_i32();
                self.emit_expr(&args[0]);
                wasm!(self.func, {
                    local_set(src);
                    local_get(src); i32_load(0); local_set(rows);
                    local_get(src); i32_load(4); local_set(cols);
                    // alloc dst: [cols, rows, data...]
                    local_get(cols); local_get(rows); i32_mul; i32_const(8); i32_mul;
                    i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                    call(self.emitter.rt.alloc); local_set(dst);
                    local_get(dst); local_get(cols); i32_store(0);
                    local_get(dst); local_get(rows); i32_store(4);
                    // loop: dst[c][r] = src[r][c]
                    i32_const(0); local_set(r);
                    block_empty; loop_empty;
                      local_get(r); local_get(rows); i32_ge_u; br_if(1);
                      i32_const(0); local_set(c);
                      block_empty; loop_empty;
                        local_get(c); local_get(cols); i32_ge_u; br_if(1);
                        // dst offset: 8 + (c * rows + r) * 8
                        local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                        local_get(c); local_get(rows); i32_mul; local_get(r); i32_add;
                        i32_const(8); i32_mul; i32_add;
                        // src offset: 8 + (r * cols + c) * 8
                        local_get(src); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                        local_get(r); local_get(cols); i32_mul; local_get(c); i32_add;
                        i32_const(8); i32_mul; i32_add;
                        f64_load(0);
                        f64_store(0);
                        local_get(c); i32_const(1); i32_add; local_set(c);
                        br(0);
                      end; end;
                      local_get(r); i32_const(1); i32_add; local_set(r);
                      br(0);
                    end; end;
                    local_get(dst);
                });
                self.scratch.free_i32(cols);
                self.scratch.free_i32(rows);
                self.scratch.free_i32(c);
                self.scratch.free_i32(r);
                self.scratch.free_i32(dst);
                self.scratch.free_i32(src);
            }
            "add" | "sub" | "div" => {
                // element-wise add/sub/div with f64x2 SIMD inner loop + scalar tail
                let a = self.scratch.alloc_i32();
                let b = self.scratch.alloc_i32();
                let dst = self.scratch.alloc_i32();
                let total = self.scratch.alloc_i32();
                let i = self.scratch.alloc_i32();
                self.emit_expr(&args[0]);
                wasm!(self.func, { local_set(a); });
                self.emit_expr(&args[1]);
                wasm!(self.func, {
                    local_set(b);
                    local_get(a); i32_load(0); local_get(a); i32_load(4); i32_mul; local_set(total);
                    local_get(total); i32_const(8); i32_mul; i32_const(self.emitter.layout_reg.header_size(super::engine::layout::LIST) as i32); i32_add;
                    call(self.emitter.rt.alloc); local_set(dst);
                    local_get(dst); local_get(a); i32_load(0); i32_store(0);
                    local_get(dst); local_get(a); i32_load(4); i32_store(4);
                    i32_const(0); local_set(i);
                    // SIMD loop: 2 elements per iter
                    block_empty; loop_empty;
                      local_get(i); i32_const(1); i32_add; local_get(total); i32_ge_u; br_if(1);
                      local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      local_get(a); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add; v128_load(0);
                      local_get(b); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add; v128_load(0);
                });
                match method {
                    "add" => { wasm!(self.func, { f64x2_add; }); }
                    "sub" => { wasm!(self.func, { f64x2_sub; }); }
                    "div" => { wasm!(self.func, { f64x2_div; }); }
                    _ => unreachable!(),
                }
                wasm!(self.func, {
                      v128_store(0);
                      local_get(i); i32_const(2); i32_add; local_set(i);
                      br(0);
                    end; end;
                    // Scalar tail (1 element if total is odd)
                    local_get(i); local_get(total); i32_lt_u;
                    if_empty;
                      local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      local_get(a); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add; f64_load(0);
                      local_get(b); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add; f64_load(0);
                });
                match method {
                    "add" => { wasm!(self.func, { f64_add; }); }
                    "sub" => { wasm!(self.func, { f64_sub; }); }
                    "div" => { wasm!(self.func, { f64_div; }); }
                    _ => unreachable!(),
                }
                wasm!(self.func, {
                      f64_store(0);
                    end;
                    local_get(dst);
                });
                self.scratch.free_i32(i);
                self.scratch.free_i32(total);
                self.scratch.free_i32(dst);
                self.scratch.free_i32(b);
                self.scratch.free_i32(a);
            }
            "mul" => {
                // Tiled matrix multiplication for cache locality.
                // Loop order: i-k-j (inner loop scans B row = contiguous memory).
                // Tile size 32 fits 3 tiles in L1 cache (32×32×8 bytes × 3 = 24KB).
                let a = self.scratch.alloc_i32();
                let b = self.scratch.alloc_i32();
                let dst = self.scratch.alloc_i32();
                let ra = self.scratch.alloc_i32();
                let ca = self.scratch.alloc_i32();
                let cb = self.scratch.alloc_i32();
                let i0 = self.scratch.alloc_i32();
                let k0 = self.scratch.alloc_i32();
                let j0 = self.scratch.alloc_i32();
                let i = self.scratch.alloc_i32();
                let k = self.scratch.alloc_i32();
                let j = self.scratch.alloc_i32();
                let i1 = self.scratch.alloc_i32();
                let k1 = self.scratch.alloc_i32();
                let j1 = self.scratch.alloc_i32();
                let a_ik = self.scratch.alloc_f64();
                const TILE: i32 = 32;
                self.emit_expr(&args[0]);
                wasm!(self.func, { local_set(a); });
                self.emit_expr(&args[1]);
                wasm!(self.func, {
                    local_set(b);
                    local_get(a); i32_load(0); local_set(ra);
                    local_get(a); i32_load(4); local_set(ca);
                    local_get(b); i32_load(4); local_set(cb);
                    // alloc + zero result
                    local_get(ra); local_get(cb); i32_mul; i32_const(8); i32_mul;
                    i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                    call(self.emitter.rt.alloc); local_set(dst);
                    local_get(dst); local_get(ra); i32_store(0);
                    local_get(dst); local_get(cb); i32_store(4);
                    local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                    i32_const(0);
                    local_get(ra); local_get(cb); i32_mul; i32_const(8); i32_mul;
                    memory_fill;
                    // Tiled loops: i0, k0, j0 (tile starts)
                    i32_const(0); local_set(i0);
                    block_empty; loop_empty;
                      local_get(i0); local_get(ra); i32_ge_u; br_if(1);
                      // i1 = min(i0+TILE, ra)
                      local_get(i0); i32_const(TILE); i32_add; local_set(i1);
                      local_get(i1); local_get(ra); i32_gt_u;
                      if_empty; local_get(ra); local_set(i1); end;

                      i32_const(0); local_set(k0);
                      block_empty; loop_empty;
                        local_get(k0); local_get(ca); i32_ge_u; br_if(1);
                        local_get(k0); i32_const(TILE); i32_add; local_set(k1);
                        local_get(k1); local_get(ca); i32_gt_u;
                        if_empty; local_get(ca); local_set(k1); end;

                        i32_const(0); local_set(j0);
                        block_empty; loop_empty;
                          local_get(j0); local_get(cb); i32_ge_u; br_if(1);
                          local_get(j0); i32_const(TILE); i32_add; local_set(j1);
                          local_get(j1); local_get(cb); i32_gt_u;
                          if_empty; local_get(cb); local_set(j1); end;

                          // Inner tile: i, k, j
                          local_get(i0); local_set(i);
                          block_empty; loop_empty;
                            local_get(i); local_get(i1); i32_ge_u; br_if(1);

                            local_get(k0); local_set(k);
                            block_empty; loop_empty;
                              local_get(k); local_get(k1); i32_ge_u; br_if(1);
                              // a_ik = A[i][k]
                              local_get(a); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                              local_get(i); local_get(ca); i32_mul; local_get(k); i32_add;
                              i32_const(8); i32_mul; i32_add; f64_load(0);
                              local_set(a_ik);

                              // SIMD inner loop: j steps by 2 (f64x2)
                              // j1_even = j1 & ~1 (round down to even)
                              local_get(j0); local_set(j);
                              block_empty; loop_empty;
                                // if j+1 >= j1, exit SIMD loop
                                local_get(j); i32_const(1); i32_add; local_get(j1); i32_gt_u; br_if(1);
                                // addr_c = dst + 8 + (i*cb + j)*8
                                local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                                local_get(i); local_get(cb); i32_mul; local_get(j); i32_add;
                                i32_const(8); i32_mul; i32_add;
                                // v_c = load C[i][j..j+2]
                                local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                                local_get(i); local_get(cb); i32_mul; local_get(j); i32_add;
                                i32_const(8); i32_mul; i32_add;
                                v128_load(0);
                                // v_a = splat(a_ik)
                                local_get(a_ik); f64x2_splat;
                                // v_b = load B[k][j..j+2]
                                local_get(b); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                                local_get(k); local_get(cb); i32_mul; local_get(j); i32_add;
                                i32_const(8); i32_mul; i32_add;
                                v128_load(0);
                                // v_c += v_a * v_b
                                f64x2_mul; f64x2_add;
                                // store C[i][j..j+2]
                                v128_store(0);

                                local_get(j); i32_const(2); i32_add; local_set(j);
                                br(0);
                              end; end;
                              // Scalar remainder: if j < j1, process 1 more element
                              local_get(j); local_get(j1); i32_lt_u;
                              if_empty;
                                local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                                local_get(i); local_get(cb); i32_mul; local_get(j); i32_add;
                                i32_const(8); i32_mul; i32_add;
                                local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                                local_get(i); local_get(cb); i32_mul; local_get(j); i32_add;
                                i32_const(8); i32_mul; i32_add; f64_load(0);
                                local_get(a_ik);
                                local_get(b); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                                local_get(k); local_get(cb); i32_mul; local_get(j); i32_add;
                                i32_const(8); i32_mul; i32_add; f64_load(0);
                                f64_mul; f64_add; f64_store(0);
                              end;
                              local_get(k); i32_const(1); i32_add; local_set(k);
                              br(0);
                            end; end;
                            local_get(i); i32_const(1); i32_add; local_set(i);
                            br(0);
                          end; end;

                          local_get(j0); i32_const(TILE); i32_add; local_set(j0);
                          br(0);
                        end; end;
                        local_get(k0); i32_const(TILE); i32_add; local_set(k0);
                        br(0);
                      end; end;
                      local_get(i0); i32_const(TILE); i32_add; local_set(i0);
                      br(0);
                    end; end;
                    local_get(dst);
                });
                self.scratch.free_f64(a_ik);
                self.scratch.free_i32(j1);
                self.scratch.free_i32(k1);
                self.scratch.free_i32(i1);
                self.scratch.free_i32(j);
                self.scratch.free_i32(k);
                self.scratch.free_i32(i);
                self.scratch.free_i32(j0);
                self.scratch.free_i32(k0);
                self.scratch.free_i32(i0);
                self.scratch.free_i32(cb);
                self.scratch.free_i32(ca);
                self.scratch.free_i32(ra);
                self.scratch.free_i32(dst);
                self.scratch.free_i32(b);
                self.scratch.free_i32(a);
            }
            "scale" => {
                // matrix.scale(m, s) → Matrix
                let m = self.scratch.alloc_i32();
                let dst = self.scratch.alloc_i32();
                let total = self.scratch.alloc_i32();
                let i = self.scratch.alloc_i32();
                let s = self.scratch.alloc_f64();
                self.emit_expr(&args[0]);
                wasm!(self.func, { local_set(m); });
                self.emit_expr(&args[1]);
                // scalar could be Int or Float — convert to f64
                if matches!(&args[1].ty, almide_lang::types::Ty::Int) {
                    wasm!(self.func, { f64_convert_i64_s; });
                }
                wasm!(self.func, {
                    local_set(s);
                    local_get(m); i32_load(0); local_get(m); i32_load(4); i32_mul; local_set(total);
                    local_get(total); i32_const(8); i32_mul; i32_const(self.emitter.layout_reg.header_size(super::engine::layout::LIST) as i32); i32_add;
                    call(self.emitter.rt.alloc); local_set(dst);
                    local_get(dst); local_get(m); i32_load(0); i32_store(0);
                    local_get(dst); local_get(m); i32_load(4); i32_store(4);
                    i32_const(0); local_set(i);
                    // SIMD f64x2 inner loop
                    block_empty; loop_empty;
                      local_get(i); i32_const(1); i32_add; local_get(total); i32_ge_u; br_if(1);
                      local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      local_get(m); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      v128_load(0); local_get(s); f64x2_splat; f64x2_mul;
                      v128_store(0);
                      local_get(i); i32_const(2); i32_add; local_set(i);
                      br(0);
                    end; end;
                    // Scalar tail (1 element if total is odd)
                    local_get(i); local_get(total); i32_lt_u;
                    if_empty;
                      local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      local_get(m); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      f64_load(0); local_get(s); f64_mul;
                      f64_store(0);
                    end;
                    local_get(dst);
                });
                self.scratch.free_f64(s);
                self.scratch.free_i32(i);
                self.scratch.free_i32(total);
                self.scratch.free_i32(dst);
                self.scratch.free_i32(m);
            }
            "fma" => {
                // matrix.fma(a, ka, b, kb) → a*ka + b*kb in one pass.
                // Layout: [rows:i32][cols:i32][f64 × rows*cols], same as
                // scale/add. Total i = rows*cols, single allocation, two
                // f64 loads + 2 muls + 1 add per element. Equivalent to
                // add(scale(a, ka), scale(b, kb)) but skips two intermediate
                // matrices and an extra pass.
                let a = self.scratch.alloc_i32();
                let b = self.scratch.alloc_i32();
                let dst = self.scratch.alloc_i32();
                let total = self.scratch.alloc_i32();
                let i = self.scratch.alloc_i32();
                let ka = self.scratch.alloc_f64();
                let kb = self.scratch.alloc_f64();
                self.emit_expr(&args[0]);
                wasm!(self.func, { local_set(a); });
                self.emit_expr(&args[1]);
                if matches!(&args[1].ty, almide_lang::types::Ty::Int) {
                    wasm!(self.func, { f64_convert_i64_s; });
                }
                wasm!(self.func, { local_set(ka); });
                self.emit_expr(&args[2]);
                wasm!(self.func, { local_set(b); });
                self.emit_expr(&args[3]);
                if matches!(&args[3].ty, almide_lang::types::Ty::Int) {
                    wasm!(self.func, { f64_convert_i64_s; });
                }
                wasm!(self.func, {
                    local_set(kb);
                    // total = rows * cols
                    local_get(a); i32_load(0); local_get(a); i32_load(4); i32_mul; local_set(total);
                    // alloc 8 + total*8
                    local_get(total); i32_const(8); i32_mul; i32_const(self.emitter.layout_reg.header_size(super::engine::layout::LIST) as i32); i32_add;
                    call(self.emitter.rt.alloc); local_set(dst);
                    // copy header
                    local_get(dst); local_get(a); i32_load(0); i32_store(0);
                    local_get(dst); local_get(a); i32_load(4); i32_store(4);
                    i32_const(0); local_set(i);

                    // SIMD f64x2 inner loop: process 2 f64 elements per iteration.
                    // Loop invariant: i + 1 < total (room for 2 lanes).
                    block_empty; loop_empty;
                      // exit when i+1 >= total (no room for full lane)
                      local_get(i); i32_const(1); i32_add; local_get(total); i32_ge_u; br_if(1);
                      // dst addr = dst + 8 + i*8
                      local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      // v_a = load a[i..i+2]
                      local_get(a); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      v128_load(0);
                      // v_a *= splat(ka)
                      local_get(ka); f64x2_splat;
                      f64x2_mul;
                      // v_b = load b[i..i+2]
                      local_get(b); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      v128_load(0);
                      // v_b *= splat(kb)
                      local_get(kb); f64x2_splat;
                      f64x2_mul;
                      // v_a + v_b
                      f64x2_add;
                      // store dst[i..i+2]
                      v128_store(0);
                      // i += 2
                      local_get(i); i32_const(2); i32_add; local_set(i);
                      br(0);
                    end; end;

                    // Scalar tail: process one trailing element if total is odd.
                    local_get(i); local_get(total); i32_lt_u;
                    if_empty;
                      local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      local_get(a); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add; f64_load(0);
                      local_get(ka); f64_mul;
                      local_get(b); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add; f64_load(0);
                      local_get(kb); f64_mul;
                      f64_add;
                      f64_store(0);
                    end;

                    local_get(dst);
                });
                self.scratch.free_f64(kb);
                self.scratch.free_f64(ka);
                self.scratch.free_i32(i);
                self.scratch.free_i32(total);
                self.scratch.free_i32(dst);
                self.scratch.free_i32(b);
                self.scratch.free_i32(a);
            }
            "fma3" => {
                // matrix.fma3(a, ka, b, kb, c, kc) → a*ka + b*kb + c*kc in one pass.
                // Target of MatrixFusionPass tree-fuse rule (nested fma collapse).
                // SIMD f64x2 inner loop + scalar tail, same shape as fma but with
                // a third input/coefficient pair.
                let a = self.scratch.alloc_i32();
                let b = self.scratch.alloc_i32();
                let c = self.scratch.alloc_i32();
                let dst = self.scratch.alloc_i32();
                let total = self.scratch.alloc_i32();
                let i = self.scratch.alloc_i32();
                let ka = self.scratch.alloc_f64();
                let kb = self.scratch.alloc_f64();
                let kc = self.scratch.alloc_f64();
                self.emit_expr(&args[0]);
                wasm!(self.func, { local_set(a); });
                self.emit_expr(&args[1]);
                if matches!(&args[1].ty, almide_lang::types::Ty::Int) { wasm!(self.func, { f64_convert_i64_s; }); }
                wasm!(self.func, { local_set(ka); });
                self.emit_expr(&args[2]);
                wasm!(self.func, { local_set(b); });
                self.emit_expr(&args[3]);
                if matches!(&args[3].ty, almide_lang::types::Ty::Int) { wasm!(self.func, { f64_convert_i64_s; }); }
                wasm!(self.func, { local_set(kb); });
                self.emit_expr(&args[4]);
                wasm!(self.func, { local_set(c); });
                self.emit_expr(&args[5]);
                if matches!(&args[5].ty, almide_lang::types::Ty::Int) { wasm!(self.func, { f64_convert_i64_s; }); }
                wasm!(self.func, {
                    local_set(kc);
                    local_get(a); i32_load(0); local_get(a); i32_load(4); i32_mul; local_set(total);
                    local_get(total); i32_const(8); i32_mul; i32_const(self.emitter.layout_reg.header_size(super::engine::layout::LIST) as i32); i32_add;
                    call(self.emitter.rt.alloc); local_set(dst);
                    local_get(dst); local_get(a); i32_load(0); i32_store(0);
                    local_get(dst); local_get(a); i32_load(4); i32_store(4);
                    i32_const(0); local_set(i);

                    block_empty; loop_empty;
                      local_get(i); i32_const(1); i32_add; local_get(total); i32_ge_u; br_if(1);
                      local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      local_get(a); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      v128_load(0);
                      local_get(ka); f64x2_splat;
                      f64x2_mul;
                      local_get(b); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      v128_load(0);
                      local_get(kb); f64x2_splat;
                      f64x2_mul;
                      f64x2_add;
                      local_get(c); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      v128_load(0);
                      local_get(kc); f64x2_splat;
                      f64x2_mul;
                      f64x2_add;
                      v128_store(0);
                      local_get(i); i32_const(2); i32_add; local_set(i);
                      br(0);
                    end; end;

                    // Scalar tail
                    local_get(i); local_get(total); i32_lt_u;
                    if_empty;
                      local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add;
                      local_get(a); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add; f64_load(0);
                      local_get(ka); f64_mul;
                      local_get(b); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add; f64_load(0);
                      local_get(kb); f64_mul;
                      f64_add;
                      local_get(c); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; local_get(i); i32_const(8); i32_mul; i32_add; f64_load(0);
                      local_get(kc); f64_mul;
                      f64_add;
                      f64_store(0);
                    end;

                    local_get(dst);
                });
                self.scratch.free_f64(kc);
                self.scratch.free_f64(kb);
                self.scratch.free_f64(ka);
                self.scratch.free_i32(i);
                self.scratch.free_i32(total);
                self.scratch.free_i32(dst);
                self.scratch.free_i32(c);
                self.scratch.free_i32(b);
                self.scratch.free_i32(a);
            }
            "from_lists" => {
                // matrix.from_lists(rows: List[List[Float]]) → Matrix
                // Input: List of Lists. List layout: [len:i32][elem0...]. Each inner list: [len:i32][f64...]
                let src = self.scratch.alloc_i32();
                let dst = self.scratch.alloc_i32();
                let nrows = self.scratch.alloc_i32();
                let ncols = self.scratch.alloc_i32();
                let r = self.scratch.alloc_i32();
                let c = self.scratch.alloc_i32();
                let row_ptr = self.scratch.alloc_i32();
                self.emit_expr(&args[0]);
                wasm!(self.func, {
                    local_set(src);
                    local_get(src); i32_load(0); local_set(nrows);
                    // cols from first row (or 0)
                    local_get(nrows); i32_eqz;
                    if_i32;
                      i32_const(0);
                    else_;
                      local_get(src); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add; i32_load(0); // ptr to first row
                      i32_load(0); // len of first row
                    end;
                    local_set(ncols);
                    // alloc matrix
                    local_get(nrows); local_get(ncols); i32_mul; i32_const(8); i32_mul;
                    i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                    call(self.emitter.rt.alloc); local_set(dst);
                    local_get(dst); local_get(nrows); i32_store(0);
                    local_get(dst); local_get(ncols); i32_store(4);
                    // copy data
                    i32_const(0); local_set(r);
                    block_empty; loop_empty;
                      local_get(r); local_get(nrows); i32_ge_u; br_if(1);
                      // row_ptr = *(src + 4 + r*4)  (pointer to inner list)
                      local_get(src); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                      local_get(r); i32_const(4); i32_mul; i32_add;
                      i32_load(0); local_set(row_ptr);
                      i32_const(0); local_set(c);
                      block_empty; loop_empty;
                        local_get(c); local_get(ncols); i32_ge_u; br_if(1);
                        // dst[r][c] = row_ptr->data[c]
                        local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                        local_get(r); local_get(ncols); i32_mul; local_get(c); i32_add;
                        i32_const(8); i32_mul; i32_add;
                        local_get(row_ptr); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                        local_get(c); i32_const(8); i32_mul; i32_add;
                        f64_load(0); f64_store(0);
                        local_get(c); i32_const(1); i32_add; local_set(c);
                        br(0);
                      end; end;
                      local_get(r); i32_const(1); i32_add; local_set(r);
                      br(0);
                    end; end;
                    local_get(dst);
                });
                self.scratch.free_i32(row_ptr);
                self.scratch.free_i32(c);
                self.scratch.free_i32(r);
                self.scratch.free_i32(ncols);
                self.scratch.free_i32(nrows);
                self.scratch.free_i32(dst);
                self.scratch.free_i32(src);
            }
            "to_lists" => {
                // matrix.to_lists(m) → List[List[Float]]
                let m = self.scratch.alloc_i32();
                let outer = self.scratch.alloc_i32();
                let nrows = self.scratch.alloc_i32();
                let ncols = self.scratch.alloc_i32();
                let r = self.scratch.alloc_i32();
                let c = self.scratch.alloc_i32();
                let row_ptr = self.scratch.alloc_i32();
                self.emit_expr(&args[0]);
                wasm!(self.func, {
                    local_set(m);
                    local_get(m); i32_load(0); local_set(nrows);
                    local_get(m); i32_load(4); local_set(ncols);
                    // alloc outer list: [len:i32][ptr0:i32][ptr1:i32]...
                    local_get(nrows); i32_const(4); i32_mul; i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                    call(self.emitter.rt.alloc); local_set(outer);
                    local_get(outer); local_get(nrows); i32_store(0);
                    // create each row list
                    i32_const(0); local_set(r);
                    block_empty; loop_empty;
                      local_get(r); local_get(nrows); i32_ge_u; br_if(1);
                      // alloc row: [len:i32][f64...]
                      local_get(ncols); i32_const(8); i32_mul; i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                      call(self.emitter.rt.alloc); local_set(row_ptr);
                      local_get(row_ptr); local_get(ncols); i32_store(0);
                      // copy data
                      i32_const(0); local_set(c);
                      block_empty; loop_empty;
                        local_get(c); local_get(ncols); i32_ge_u; br_if(1);
                        local_get(row_ptr); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                        local_get(c); i32_const(8); i32_mul; i32_add;
                        local_get(m); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                        local_get(r); local_get(ncols); i32_mul; local_get(c); i32_add;
                        i32_const(8); i32_mul; i32_add;
                        f64_load(0); f64_store(0);
                        local_get(c); i32_const(1); i32_add; local_set(c);
                        br(0);
                      end; end;
                      // store row ptr in outer list
                      local_get(outer); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                      local_get(r); i32_const(4); i32_mul; i32_add;
                      local_get(row_ptr); i32_store(0);
                      local_get(r); i32_const(1); i32_add; local_set(r);
                      br(0);
                    end; end;
                    local_get(outer);
                });
                self.scratch.free_i32(row_ptr);
                self.scratch.free_i32(c);
                self.scratch.free_i32(r);
                self.scratch.free_i32(ncols);
                self.scratch.free_i32(nrows);
                self.scratch.free_i32(outer);
                self.scratch.free_i32(m);
            }
            "map" => {
                // matrix.map(m, f) → Matrix: apply f(Float) -> Float to each element
                let m = self.scratch.alloc_i32();
                let closure = self.scratch.alloc_i32();
                let dst = self.scratch.alloc_i32();
                let total = self.scratch.alloc_i32();
                let i = self.scratch.alloc_i32();
                self.emit_expr(&args[0]);
                wasm!(self.func, { local_set(m); });
                self.emit_expr(&args[1]);
                wasm!(self.func, {
                    local_set(closure);
                    local_get(m); i32_load(0); local_get(m); i32_load(4); i32_mul; local_set(total);
                    local_get(total); i32_const(8); i32_mul; i32_const(self.emitter.layout_reg.header_size(super::engine::layout::LIST) as i32); i32_add;
                    call(self.emitter.rt.alloc); local_set(dst);
                    local_get(dst); local_get(m); i32_load(0); i32_store(0);
                    local_get(dst); local_get(m); i32_load(4); i32_store(4);
                    i32_const(0); local_set(i);
                    block_empty; loop_empty;
                      local_get(i); local_get(total); i32_ge_u; br_if(1);
                      // dst[i] = f(m[i])
                      local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                      local_get(i); i32_const(8); i32_mul; i32_add;
                      // call closure: env, arg, table_idx
                      local_get(closure); i32_load(4); // env
                      local_get(m); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                      local_get(i); i32_const(8); i32_mul; i32_add;
                      f64_load(0); // element value
                      local_get(closure); i32_load(0); // table_idx
                });
                self.emit_closure_call(&almide_lang::types::Ty::Float, &almide_lang::types::Ty::Float);
                wasm!(self.func, {
                      f64_store(0);
                      local_get(i); i32_const(1); i32_add; local_set(i);
                      br(0);
                    end; end;
                    local_get(dst);
                });
                self.scratch.free_i32(i);
                self.scratch.free_i32(total);
                self.scratch.free_i32(dst);
                self.scratch.free_i32(closure);
                self.scratch.free_i32(m);
            }
            "broadcast_add_row" => {
                // matrix.broadcast_add_row(m, bias) → Matrix
                // m: (R, C), bias: List[Float] of length C. result[r,c] = m[r,c] + bias[c]
                let m = self.scratch.alloc_i32();
                let bias = self.scratch.alloc_i32();
                let dst = self.scratch.alloc_i32();
                let rows = self.scratch.alloc_i32();
                let cols = self.scratch.alloc_i32();
                let r = self.scratch.alloc_i32();
                let c = self.scratch.alloc_i32();
                self.emit_expr(&args[0]);
                wasm!(self.func, { local_set(m); });
                self.emit_expr(&args[1]);
                wasm!(self.func, {
                    local_set(bias);
                    local_get(m); i32_load(0); local_set(rows);
                    local_get(m); i32_load(4); local_set(cols);
                    local_get(rows); local_get(cols); i32_mul; i32_const(8); i32_mul;
                    i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                    call(self.emitter.rt.alloc); local_set(dst);
                    local_get(dst); local_get(rows); i32_store(0);
                    local_get(dst); local_get(cols); i32_store(4);
                    i32_const(0); local_set(r);
                    block_empty; loop_empty;
                      local_get(r); local_get(rows); i32_ge_u; br_if(1);
                      i32_const(0); local_set(c);
                      block_empty; loop_empty;
                        local_get(c); local_get(cols); i32_ge_u; br_if(1);
                        // dst[r,c] = m[r,c] + bias[c]
                        local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                        local_get(r); local_get(cols); i32_mul; local_get(c); i32_add;
                        i32_const(8); i32_mul; i32_add;
                        local_get(m); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                        local_get(r); local_get(cols); i32_mul; local_get(c); i32_add;
                        i32_const(8); i32_mul; i32_add;
                        f64_load(0);
                        local_get(bias); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                        local_get(c); i32_const(8); i32_mul; i32_add;
                        f64_load(0);
                        f64_add;
                        f64_store(0);
                        local_get(c); i32_const(1); i32_add; local_set(c);
                        br(0);
                      end; end;
                      local_get(r); i32_const(1); i32_add; local_set(r);
                      br(0);
                    end; end;
                    local_get(dst);
                });
                self.scratch.free_i32(c);
                self.scratch.free_i32(r);
                self.scratch.free_i32(cols);
                self.scratch.free_i32(rows);
                self.scratch.free_i32(dst);
                self.scratch.free_i32(bias);
                self.scratch.free_i32(m);
            }
            "slice_rows" => {
                // matrix.slice_rows(m, start, end) → Matrix
                let m = self.scratch.alloc_i32();
                let start = self.scratch.alloc_i32();
                let end_ = self.scratch.alloc_i32();
                let dst = self.scratch.alloc_i32();
                let cols = self.scratch.alloc_i32();
                let nrows = self.scratch.alloc_i32();
                self.emit_expr(&args[0]);
                wasm!(self.func, { local_set(m); });
                self.emit_expr(&args[1]);
                wasm!(self.func, { i32_wrap_i64; local_set(start); });
                self.emit_expr(&args[2]);
                wasm!(self.func, {
                    i32_wrap_i64; local_set(end_);
                    local_get(m); i32_load(4); local_set(cols);
                    // nrows = end - start (clamped >= 0)
                    local_get(end_); local_get(start); i32_sub; local_set(nrows);
                    local_get(nrows); i32_const(0); i32_lt_s;
                    if_empty; i32_const(0); local_set(nrows); end;
                    // alloc + header
                    local_get(nrows); local_get(cols); i32_mul; i32_const(8); i32_mul;
                    i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                    call(self.emitter.rt.alloc); local_set(dst);
                    local_get(dst); local_get(nrows); i32_store(0);
                    local_get(dst); local_get(cols); i32_store(4);
                    // memcpy: dst.data, m.data + start*cols*8, nrows*cols*8
                    local_get(dst); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                    local_get(m); i32_const(self.emitter.layout_reg.fixed_offset(super::engine::layout::LIST, super::engine::layout::list::DATA) as i32); i32_add;
                    local_get(start); local_get(cols); i32_mul; i32_const(8); i32_mul; i32_add;
                    local_get(nrows); local_get(cols); i32_mul; i32_const(8); i32_mul;
                    memory_copy;
                    local_get(dst);
                });
                self.scratch.free_i32(nrows);
                self.scratch.free_i32(cols);
                self.scratch.free_i32(dst);
                self.scratch.free_i32(end_);
                self.scratch.free_i32(start);
                self.scratch.free_i32(m);
            }
            // No native WASM arm for this method. Try the @rewrite-derived
            // desugar: rebuild the primitive composition (the fusion rule's
            // `from`) and emit that instead. The desugar table is generated from
            // the same stdlib @rewrite rules that drive fusion, so any fused op
            // is emittable on every target — the old ICE is now impossible. A
            // genuinely unknown method has no desugar -> false (caller diagnoses).
            _ => match desugar_matrix_fusion(method, args) {
                Some(unfused) => self.emit_expr(&unfused),
                None => return false,
            },
        }
        true
    }
}

include!("calls_matrix_p2.rs");
include!("calls_matrix_p3.rs");
include!("calls_matrix_p4.rs");
include!("calls_matrix_p5.rs");
