#!/usr/bin/env bash
# STRUCTURAL CORPUS WALL (#2759, #1696 step 4): the corpus sweep of the leg
# that ships. corpus-wall.sh drives the MIR lowering, which no wasm artifact
# comes from since #2761; this twin drives the STRUCTURAL build — the
# product route `almide build --target wasm` takes (`almide::wasm_route`) —
# over every fixture golden/witness-fixtures.txt lists as fully certified
# (#2754: every frame of its shipped pass carries an ownership witness).
#
# Per fixture, the producer (crates/almide-wasm/examples/
# emit_structural_bundle.rs) writes one certificate bundle:
#   ownership        one witness per frame, recorded as the RC instructions
#                    were emitted (witness.rs)
#   call-modes       the program's call sites against their callees' frame
#                    conventions (witness_modes.rs)
#   names            per index space of the stock-WASI bytes the build ships,
#                    and per function's locals (cert_project.rs)
#   caps             per source-declared function: declared | transitive reach
#   caps-transitive  the whole call graph, the reach computed IN the proof
#
# ARTIFACT IDENTITY (#2760): each fixture is first built by the product path,
# `almide build --target wasm`, and the producer refuses unless that file is
# byte-for-byte the module its own route produced; the bundle then pins the
# file's SHA-256 (version-2 `artifact` record), and almide-verify recomputes
# the digest from the file and REJECTS a mismatch. The digests are written to
# proofs/structural-artifacts.sha256 (fixture -> SHA-256 of the shipped
# bytes; generated, not committed), cross-checked against `shasum -a 256` —
# the producer's sha2, almide-verify's own SHA-256 and shasum: three
# implementations of one number — and a drill flips one byte of a built
# artifact, which almide-verify must reject.
#
# Every witness is judged by THREE independent verdicts, and all three must
# agree: the checker extracted from the Coq proof (proofs/checker), the Rocq
# KERNEL itself (a generated file of vm_compute goals, coqc'd), and
# almide-verify (the portable re-checker a binary distribution runs). The
# report gives acceptance per property. A witness may REJECT only if
# proofs/structural-wall-exceptions.txt names it (a shrink-only ledger: a
# listed witness that now accepts is stale and fails the gate).
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(cd .. && pwd)"
source "$ROOT/proofs/lib/stamp.sh"
stamp_toolchain "$ROOT" || exit 1

FIXTURES="$ROOT/crates/almide-wasm/tests/golden/witness-fixtures.txt"
EXCEPTIONS="$ROOT/proofs/structural-wall-exceptions.txt"
COQC="${COQC:-$(command -v coqc || true)}"
[ -n "$COQC" ] || { echo "STRUCTURAL WALL FAIL: coqc is not on PATH (the kernel verdict needs it)" >&2; exit 1; }

echo "== build the compiler, the bundle producer, almide-verify and the kernel-proven checker =="
(cd "$ROOT" && cargo build -q --bin almide && cargo build -q -p almide-wasm --example emit_structural_bundle && cargo build -q -p almide-verify)
TD="${CARGO_TARGET_DIR:-$ROOT/target}/debug"
ALMIDE="$TD/almide"
PRODUCER="$TD/examples/emit_structural_bundle"
VERIFY="$TD/almide-verify"
./build-checker.sh >/dev/null
HASHES="$ROOT/proofs/structural-artifacts.sha256"

OUT="$(mktemp -d)"
trap 'rm -rf "$OUT"' EXIT

echo "== build each certified fixture (almide build --target wasm) and produce its bundle =="
N=0
{
  echo "# fixture -> SHA-256 of the bytes 'almide build --target wasm' ships for it (#2760)."
  echo "# Generated by proofs/structural-wall.sh; each certificate bundle pins its row."
} > "$HASHES.tmp"
while IFS= read -r f; do
  case "$f" in ''|'#'*) continue ;; esac
  N=$((N + 1))
  if ! (cd "$ROOT" && "$ALMIDE" build "$f" --target wasm -o "$OUT/$N.wasm") > "$OUT/$N.err" 2>&1; then
    echo "STRUCTURAL WALL FAIL: 'almide build --target wasm' refused a certified fixture: $f" >&2
    sed 's/^/  /' "$OUT/$N.err" >&2
    exit 1
  fi
  if ! (cd "$ROOT" && "$PRODUCER" "$f" --artifact "$OUT/$N.wasm") > "$OUT/$N.bundle" 2> "$OUT/$N.err"; then
    echo "STRUCTURAL WALL FAIL: the producer refused a certified fixture: $f" >&2
    sed 's/^/  /' "$OUT/$N.err" >&2
    exit 1
  fi
  printf '%s\t%s\n' "$N" "$f" >> "$OUT/index"
  # Verdict 3: almide-verify, one run per bundle (its per-witness lines are
  # read back in bundle order below); it also recomputes the artifact digest.
  rc=0
  "$VERIFY" bundle "$OUT/$N.bundle" > "$OUT/$N.verify" 2>&1 || rc=$?
  echo "$rc" > "$OUT/$N.verify.rc"
  # The third SHA-256 — shasum's — against the digest the bundle pins.
  sum="$(shasum -a 256 "$OUT/$N.wasm" | cut -d' ' -f1)"
  pinned="$(sed -n 's/^artifact sha256 \([0-9a-f]*\) .*/\1/p' "$OUT/$N.bundle")"
  if [ "$sum" != "$pinned" ]; then
    echo "STRUCTURAL WALL FAIL: $f: the bundle pins sha256 '$pinned', shasum reads $sum" >&2
    exit 1
  fi
  printf '%s  %s\n' "$sum" "$f" >> "$HASHES.tmp"
done < "$FIXTURES"
[ "$N" -gt 0 ] || { echo "STRUCTURAL WALL FAIL: no certified fixture listed in $FIXTURES" >&2; exit 1; }
mv "$HASHES.tmp" "$HASHES"
echo "  $N fixture bundle(s); artifact digests in proofs/structural-artifacts.sha256"

echo "== drill: one byte of a shipped artifact changed — the verifier must reject =="
mkdir -p "$OUT/tamper"
sed 's|^artifact sha256 \([0-9a-f]*\) .*|artifact sha256 \1 app.wasm|' "$OUT/1.bundle" > "$OUT/tamper/1.bundle"
python3 -c 'import sys; b = bytearray(open(sys.argv[1], "rb").read()); b[len(b) // 2] ^= 1; open(sys.argv[2], "wb").write(b)' \
  "$OUT/1.wasm" "$OUT/tamper/app.wasm"
rc=0
"$VERIFY" bundle "$OUT/tamper/1.bundle" > "$OUT/tamper/verify" 2>&1 || rc=$?
if [ "$rc" -ne 1 ] || ! grep -q MISMATCH "$OUT/tamper/verify"; then
  echo "STRUCTURAL WALL FAIL: almide-verify did not reject an artifact one byte off (exit $rc)" >&2
  sed 's/^/  /' "$OUT/tamper/verify" >&2
  exit 1
fi
cp "$OUT/1.wasm" "$OUT/tamper/app.wasm"
rc=0
"$VERIFY" bundle "$OUT/tamper/1.bundle" > /dev/null 2>&1 || rc=$?
if [ "$rc" -ne 0 ]; then
  echo "STRUCTURAL WALL FAIL: the drill's control (the untouched artifact) did not verify (exit $rc)" >&2
  exit 1
fi
echo "  ok: the flipped byte reads MISMATCH (exit 1); the untouched artifact verifies (exit 0)"

echo "== the extracted checker judges every witness; the kernel file is generated =="
KGEN="$(mktemp /tmp/KernelStructural_XXXXXX).v"
set +e
python3 - "$OUT" "$ROOT/proofs/checker" "$EXCEPTIONS" "$KGEN" <<'PYEOF'
import os, subprocess, sys
out, checker, exceptions_path, kgen = sys.argv[1:5]
FN = {"ownership": "check_xc", "names": "check_names_cert", "caps": "check_caps_cert",
      "caps-transitive": "check_prog_cert", "call-modes": "check_modes_cert"}

def parse(path):
    b = open(path, "rb").read()
    i, recs, uncert = b.index(b"\n") + 1, [], []
    while i < len(b):
        j = b.index(b"\n", i)
        line = b[i:j].decode()
        i = j + 1
        if line.startswith("witness "):
            _, prop, n, fn = line.split(" ", 3)
            n = int(n)
            recs.append((prop, fn, b[i:i + n].decode()))
            i += n + 1
        elif line.startswith("uncertified "):
            uncert.append(line)
    return recs, uncert

def verify_lines(path):
    got = []
    for line in open(path).read().splitlines():
        parts = line.split(None, 2)
        if len(parts) == 3 and parts[0] in ("ACCEPT", "REJECT"):
            got.append((parts[1], parts[2], parts[0] == "ACCEPT"))
    return got

exceptions = set()
if os.path.exists(exceptions_path):
    for line in open(exceptions_path):
        line = line.strip()
        if line and not line.startswith("#"):
            fx, prop, fn = line.split("\t")[:3]
            exceptions.add((fx, prop, fn))

fail = []
stats = {p: [0, 0] for p in FN}
fixtures_ok = 0
rejected_seen = set()
accepts = {p: [] for p in FN}   # kernel: forallb f [...] = true
rejects = []                     # kernel: f w = false
one = os.path.join(out, "one.w")
for row in open(os.path.join(out, "index")):
    k, fx = row.rstrip("\n").split("\t")
    recs, uncert = parse(os.path.join(out, k + ".bundle"))
    if uncert:
        fail.append(f"{fx}: the bundle declares {len(uncert)} uncertified frame(s) — the fixture is listed as certified ({uncert[0]})")
    portable = verify_lines(os.path.join(out, k + ".verify"))
    vtext = open(os.path.join(out, k + ".verify")).read()
    vrc = open(os.path.join(out, k + ".verify.rc")).read().strip()
    if not any(l.startswith("ARTIFACT") and l.endswith(": MATCH") for l in vtext.splitlines()):
        fail.append(f"{fx}: almide-verify did not confirm the artifact's SHA-256")
    if len(portable) != len(recs):
        fail.append(f"{fx}: almide-verify judged {len(portable)} of {len(recs)} witnesses")
        continue
    all_ok = True
    for (prop, fn, w), (vp, vf, vok) in zip(recs, portable):
        if (vp, vf) != (prop, fn):
            fail.append(f"{fx}: almide-verify's verdict order drifted at [{prop}] {fn}")
            break
        with open(one, "w") as f:
            f.write(w)
        rc = subprocess.run([checker, prop, one], capture_output=True).returncode
        if rc not in (0, 1):
            fail.append(f"{fx}: the extracted checker gave no verdict (exit {rc}) on [{prop}] {fn}")
            continue
        ok = rc == 0
        if ok != vok:
            fail.append(f"{fx}: [{prop}] {fn}: extracted checker {'ACCEPT' if ok else 'REJECT'}, almide-verify {'ACCEPT' if vok else 'REJECT'}")
        stats[prop][1] += 1
        key = (fx, prop, fn)
        if ok:
            stats[prop][0] += 1
            accepts[prop].append(w)
        else:
            all_ok = False
            rejects.append((prop, w))
            rejected_seen.add(key)
            if key not in exceptions:
                fail.append(f"{fx}: [{prop}] {fn} REJECTED and no exception names it: {w[:200]!r}")
    fixtures_ok += all_ok
    if all_ok and vrc != "0":
        fail.append(f"{fx}: every witness accepts, but almide-verify's bundle outcome is exit {vrc}")
for key in sorted(exceptions - rejected_seen):
    fail.append("STALE exception (no witness of that name rejects — remove the row): " + "\t".join(key))

def lit(s):
    return '"' + s.replace('"', '""') + '"'
with open(kgen, "w") as g:
    g.write("From AlmideTrust Require Import OwnershipChecker NameTotality CapabilityBound CapabilityReach CallModes.\n")
    g.write("From Stdlib Require Import String List.\nImport ListNotations.\nOpen Scope string_scope.\n")
    LIMIT = 60000  # literal bytes per goal: bounds the kernel's peak term
    for prop, ws in accepts.items():
        chunk, size = [], 0
        for w in ws + [None]:
            if w is None or (chunk and size + len(w) > LIMIT):
                if chunk:
                    g.write("Goal forallb %s [%s] = true.\nProof. vm_compute. reflexivity. Qed.\n" % (FN[prop], ";".join(lit(x) for x in chunk)))
                chunk, size = [], 0
            if w is not None:
                chunk.append(w)
                size += len(w)
    for prop, w in rejects:
        g.write("Goal %s %s = false.\nProof. vm_compute. reflexivity. Qed.\n" % (FN[prop], lit(w)))

for p, (a, t) in stats.items():
    print(f"  [{p}] {a}/{t} witness(es) accepted by the extracted checker and almide-verify")
n = sum(1 for _ in open(os.path.join(out, "index")))
print(f"  {fixtures_ok}/{n} fixture(s) accepted on every property; {len(rejects)} rejected witness(es), each named in the exception ledger")
for m in fail[:20]:
    print("  FAIL " + m)
sys.exit(1 if fail else 0)
PYEOF
PRC=$?
set -e
if [ "$PRC" -ne 0 ]; then
  rm -f "$KGEN"
  echo "STRUCTURAL WALL FAIL: a certified fixture's witness is rejected, or the verdicts disagree (above)." >&2
  exit 1
fi

echo "== KERNEL ORACLE: the Rocq kernel re-derives every verdict above =="
KSTART=$(date +%s)
if (cd "$ROOT/proofs" && "$COQC" -Q . AlmideTrust "$KGEN" >/dev/null 2>&1); then
  echo "  KERNEL OK: every structural witness verdict certified by the Rocq kernel in $(( $(date +%s) - KSTART ))s (vm_compute)"
  rm -f "$KGEN" "${KGEN%.v}.vo" "${KGEN%.v}.vos" "${KGEN%.v}.vok" "${KGEN%.v}.glob"
else
  echo "STRUCTURAL WALL FAIL: the KERNEL disagrees with the extracted checker on a structural witness (extraction divergence)." >&2
  rm -f "$KGEN"
  exit 1
fi

echo
echo "STRUCTURAL WALL OK: over the $N certified spec/wasm_cross fixtures, every ownership, call-mode,"
echo "name-totality, capability and call-graph witness of the structural build is accepted —"
echo "the extracted checker, the Rocq kernel and almide-verify agreeing on every verdict — and"
echo "every bundle names the SHA-256 of the file 'almide build --target wasm' shipped for it."
