//! MIR → native Rust renderer — the NATIVE leg of the trust spine (#764, rung 1).
//!
//! Renders the SAME Perceus-disciplined MIR the wasm leg consumes, mapping the
//! ownership ops onto Rust's own memory management instead of literal RC:
//!
//!   Dup        → `let dst = src.clone()` (a new owned handle; the clone IS the +1)
//!   Drop       → erased — Rust's scope-end drop realizes the free (never earlier
//!                than the MIR's Drop point observes, never leaks: `verify_ownership`
//!                certifies the balance on the SAME ops before rendering)
//!   CallFn     → a user fn call, or a CLOSED runtime-boundary shim (`print_str`,
//!                `int.to_string`, `__chk_div`, …) mapped to native Rust — mirroring
//!                v0's runtime/rs floor, never re-implemented inline
//!
//! HONEST WALL: anything outside the rung-1 subset returns `Err(LowerError::
//! Unsupported)` — the CLI falls back to v0. A rendered program is never wrong;
//! an unrenderable one declines loudly. Same discipline as the wasm ladder.
//!
//! Rung-1 subset: i64 scalars, String heap values (literal `Init::Str` allocs and
//! shim results), full scalar control flow (if-as-value, loops), scalar user fns.

use crate::lower::LowerError;
use crate::{CallArg, Init, IntOp, MirFunction, MirProgram, Op, Repr, ValueId};
use std::collections::BTreeMap;
use std::fmt::Write as _;

/// The native type a MIR value renders to in rung 1.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum NTy {
    I64,
    Str,
}

fn wall(msg: impl Into<String>) -> LowerError {
    LowerError::Unsupported(msg.into())
}

fn var(v: ValueId) -> String {
    format!("v{}", v.0)
}

/// The CLOSED runtime-boundary map: self-hosted runtime fn name → (arg NTys,
/// result NTy, native Rust shim body). Adding a name here is adding to the
/// trusted floor — keep it tiny; everything else walls.
fn shim(name: &str) -> Option<(&'static [NTy], Option<NTy>, &'static str)> {
    match name {
        "int.to_string" => Some((
            &[NTy::I64],
            Some(NTy::Str),
            "fn rt_int_to_string(n: i64) -> String { n.to_string() }",
        )),
        "print_str" => Some((
            &[NTy::Str],
            None,
            "fn rt_print_str(s: &str) { println!(\"{}\", s); }",
        )),
        "__chk_div" => Some((
            &[NTy::I64, NTy::I64],
            Some(NTy::I64),
            "fn rt_chk_div(a: i64, b: i64) -> i64 {\n    if b == 0 { eprintln!(\"Error: division by zero\"); std::process::exit(1); }\n    if a == i64::MIN && b == -1 { eprintln!(\"Error: integer overflow\"); std::process::exit(1); }\n    a / b\n}",
        )),
        "__chk_mod" => Some((
            &[NTy::I64, NTy::I64],
            Some(NTy::I64),
            "fn rt_chk_mod(a: i64, b: i64) -> i64 {\n    if b == 0 { eprintln!(\"Error: modulo by zero\"); std::process::exit(1); }\n    if a == i64::MIN && b == -1 { eprintln!(\"Error: integer overflow\"); std::process::exit(1); }\n    a % b\n}",
        )),
        _ => None,
    }
}

fn shim_rust_name(name: &str) -> String {
    format!("rt_{}", name.trim_start_matches("__").replace('.', "_"))
}

/// Render a whole MIR program to a self-contained Rust source, or WALL.
pub fn try_render_native_program(prog: &MirProgram) -> Result<String, LowerError> {
    let user_fns: BTreeMap<&str, &MirFunction> =
        prog.functions.iter().map(|f| (f.name.as_str(), f)).collect();
    if !user_fns.contains_key("main") {
        return Err(wall("native: no main in the MIR program"));
    }

    let mut used_shims: Vec<&'static str> = Vec::new();
    let mut bodies = String::new();
    for func in &prog.functions {
        // The Perceus balance is machine-checked on the SAME ops this render
        // erases Drops from — the certificate that scope-end drop realizes it.
        if let Err(violations) = crate::verify_ownership(func) {
            return Err(wall(format!(
                "native: ownership verification failed for `{}`: {violations:?}",
                func.name
            )));
        }
        let rendered = render_fn(func, &user_fns, &mut used_shims)?;
        bodies.push_str(&rendered);
        bodies.push('\n');
    }

    let mut out = String::from(
        "// Generated by the Almide v1 trust spine (native leg, rung 1).\n\
         #![allow(unused_variables, unused_mut, unreachable_code)]\n\n",
    );
    used_shims.sort();
    used_shims.dedup();
    for s in used_shims {
        out.push_str(s);
        out.push_str("\n\n");
    }
    out.push_str(&bodies);
    Ok(out)
}

fn render_fn(
    func: &MirFunction,
    user_fns: &BTreeMap<&str, &MirFunction>,
    used_shims: &mut Vec<&'static str>,
) -> Result<String, LowerError> {
    // Rung 1: user fns are SCALAR-only (i64 params/result); `main` takes nothing.
    let mut tys: BTreeMap<ValueId, NTy> = BTreeMap::new();
    for p in &func.params {
        match p.repr {
            Repr::Scalar { .. } => {
                tys.insert(p.value, NTy::I64);
            }
            _ => {
                return Err(wall(format!(
                    "native: fn `{}` has a heap param — outside rung 1",
                    func.name
                )))
            }
        }
    }

    let is_main = func.name == "main";
    let mut sig = if is_main {
        String::from("fn main()")
    } else {
        let params: Vec<String> =
            func.params.iter().map(|p| format!("{}: i64", var(p.value))).collect();
        let ret = if func.ret.is_some() { " -> i64" } else { "" };
        format!("fn {}({}){}", mangle(&func.name), params.join(", "), ret)
    };
    sig.push_str(" {\n");
    let mut out = sig;
    let mut indent = 1usize;
    // The value each open if-arm yields, so `Else`/`EndIf` markers can assign it.
    let mut if_stack: Vec<Option<ValueId>> = Vec::new();

    macro_rules! line {
        ($($arg:tt)*) => {{
            for _ in 0..indent { out.push_str("    "); }
            writeln!(out, $($arg)*).unwrap();
        }};
    }

    for op in &func.ops {
        match op {
            Op::ConstInt { dst, value } => {
                tys.insert(*dst, NTy::I64);
                line!("let mut {}: i64 = {}i64;", var(*dst), value);
            }
            Op::Alloc { dst, init, .. } => match init {
                Init::Str(s) => {
                    tys.insert(*dst, NTy::Str);
                    line!("let mut {}: String = String::from({s:?});", var(*dst));
                }
                other => return Err(wall(format!("native: Alloc {other:?} — outside rung 1"))),
            },
            Op::Dup { dst, src } => {
                let t = *tys.get(src).ok_or_else(|| wall("native: Dup of untyped value"))?;
                tys.insert(*dst, t);
                line!("let mut {} = {}.clone();", var(*dst), var(*src));
            }
            // Drop is ERASED: Rust frees at scope end. `verify_ownership` above
            // certified every heap object reaches balance on these same ops.
            Op::Drop { .. } => line!("// drop: scope-end"),
            // Pure ownership bookkeeping — no native code.
            Op::Consume { .. } | Op::Borrow { .. } | Op::MakeUnique { .. } => {}
            Op::SetLocal { local, src } => {
                let t = *tys.get(src).ok_or_else(|| wall("native: SetLocal of untyped value"))?;
                if let Some(prev) = tys.get(local) {
                    if *prev != t {
                        return Err(wall("native: SetLocal changes a value's type"));
                    }
                    if t == NTy::Str {
                        line!("{} = {}.clone();", var(*local), var(*src));
                    } else {
                        line!("{} = {};", var(*local), var(*src));
                    }
                } else {
                    tys.insert(*local, t);
                    if t == NTy::Str {
                        line!("let mut {} = {}.clone();", var(*local), var(*src));
                    } else {
                        line!("let mut {} = {};", var(*local), var(*src));
                    }
                }
            }
            Op::IntBinOp { dst, op, a, b } => {
                tys.insert(*dst, NTy::I64);
                let rendered = render_int_binop(op, *a, *b, used_shims)?;
                line!("let mut {}: i64 = {};", var(*dst), rendered);
            }
            Op::CallFn { dst, name, args, result } => {
                if let Some(callee) = user_fns.get(name.as_str()) {
                    if callee.params.iter().any(|p| !matches!(p.repr, Repr::Scalar { .. })) {
                        return Err(wall(format!(
                            "native: call to `{name}` with heap signature — outside rung 1"
                        )));
                    }
                    let mut rendered_args = Vec::new();
                    for a in args {
                        let (code, t) = call_arg(a, &tys)?;
                        if t != NTy::I64 {
                            return Err(wall(format!(
                                "native: heap arg to scalar fn `{name}` — outside rung 1"
                            )));
                        }
                        rendered_args.push(code);
                    }
                    if let Some(d) = dst {
                        tys.insert(*d, NTy::I64);
                        line!(
                            "let mut {}: i64 = {}({});",
                            var(*d),
                            mangle(name),
                            rendered_args.join(", ")
                        );
                    } else {
                        line!("{}({});", mangle(name), rendered_args.join(", "));
                    }
                } else if let Some((param_tys, ret_ty, shim_src)) = shim(name) {
                    if args.len() != param_tys.len() {
                        return Err(wall(format!("native: shim `{name}` arity mismatch")));
                    }
                    let mut rendered_args = Vec::new();
                    for (a, want) in args.iter().zip(param_tys) {
                        let (code, got) = call_arg(a, &tys)?;
                        if got != *want {
                            return Err(wall(format!("native: shim `{name}` arg type mismatch")));
                        }
                        // Heap args are BORROWED at the MIR level — pass by reference.
                        rendered_args.push(if *want == NTy::Str { format!("&{code}") } else { code });
                    }
                    used_shims.push(shim_src);
                    let call = format!("{}({})", shim_rust_name(name), rendered_args.join(", "));
                    match (dst, ret_ty) {
                        (Some(d), Some(t)) => {
                            tys.insert(*d, t);
                            let ty_name = if t == NTy::Str { "String" } else { "i64" };
                            line!("let mut {}: {} = {};", var(*d), ty_name, call);
                        }
                        (None, _) => line!("{call};"),
                        (Some(_), None) => {
                            return Err(wall(format!("native: shim `{name}` has no result")))
                        }
                    }
                    let _ = result;
                } else {
                    return Err(wall(format!(
                        "native: call to `{name}` — not a lowered user fn and not in the \
                         rung-1 runtime floor"
                    )));
                }
            }
            // Witness-level runtime calls (the lower emits `print_str`/`print_int`
            // through these for `println`).
            Op::Call { dst, func, args, .. } => {
                use crate::RtFn;
                match (func, args.as_slice()) {
                    (RtFn::PrintStr, [a]) => {
                        let (code, t) = call_arg(a, &tys)?;
                        if t != NTy::Str {
                            return Err(wall("native: print_str of a non-String"));
                        }
                        used_shims.push(shim("print_str").unwrap().2);
                        line!("rt_print_str(&{code});");
                    }
                    (RtFn::PrintInt, [a]) => {
                        let (code, t) = call_arg(a, &tys)?;
                        if t != NTy::I64 {
                            return Err(wall("native: print_int of a non-Int"));
                        }
                        line!("println!(\"{{}}\", {code});");
                    }
                    other => {
                        return Err(wall(format!(
                            "native: runtime call {other:?} — outside rung 1"
                        )))
                    }
                }
                if dst.is_some() {
                    return Err(wall("native: print with a result — outside rung 1"));
                }
            }
            Op::IfThen { cond, dst } => {
                if let Some(d) = dst {
                    // if-as-value: pre-declare the join; arms assign it. The join
                    // type is settled by the first arm's yield (see Else below).
                    if_stack.push(Some(*d));
                    line!("let mut {}: i64;", var(*d));
                    tys.insert(*d, NTy::I64);
                } else {
                    if_stack.push(None);
                }
                line!("if {} != 0 {{", var(*cond));
                indent += 1;
            }
            Op::Else { val } => {
                let join = if_stack.last().copied().flatten();
                if let (Some(d), Some(v)) = (join, val) {
                    if tys.get(v) != Some(&NTy::I64) {
                        return Err(wall("native: non-scalar if-value — outside rung 1"));
                    }
                    line!("{} = {};", var(d), var(*v));
                }
                indent -= 1;
                line!("}} else {{");
                indent += 1;
            }
            Op::EndIf { val } => {
                let join = if_stack.pop().flatten();
                if let (Some(d), Some(v)) = (join, val) {
                    if tys.get(v) != Some(&NTy::I64) {
                        return Err(wall("native: non-scalar if-value — outside rung 1"));
                    }
                    line!("{} = {};", var(d), var(*v));
                }
                indent -= 1;
                line!("}}");
            }
            Op::LoopStart => {
                line!("loop {{");
                indent += 1;
            }
            Op::LoopBreakUnless { cond } => {
                line!("if {} == 0 {{ break; }}", var(*cond));
            }
            Op::LoopEnd => {
                indent -= 1;
                line!("}}");
            }
            other => {
                return Err(wall(format!(
                    "native: op {:?} — outside rung 1",
                    op_name(other)
                )))
            }
        }
    }

    match (&func.ret, is_main) {
        (Some(v), false) => line!("{}", var(*v)),
        (Some(_), true) => return Err(wall("native: main with a return value")),
        (None, _) => {}
    }
    if !if_stack.is_empty() {
        return Err(wall("native: unbalanced IfThen/EndIf markers"));
    }
    out.push_str("}\n");
    Ok(out)
}

/// A rendered call argument with the NTy it carries (`Imm` is always i64).
fn call_arg(a: &CallArg, tys: &BTreeMap<ValueId, NTy>) -> Result<(String, NTy), LowerError> {
    match a {
        CallArg::Handle(v) | CallArg::Scalar(v) => {
            let t = *tys.get(v).ok_or_else(|| wall("native: call arg untyped"))?;
            Ok((var(*v), t))
        }
        CallArg::Imm(n) => Ok((format!("{n}i64"), NTy::I64)),
        other => Err(wall(format!("native: call arg {other:?} — outside rung 1"))),
    }
}

fn render_int_binop(
    op: &IntOp,
    a: ValueId,
    b: ValueId,
    used_shims: &mut Vec<&'static str>,
) -> Result<String, LowerError> {
    let (l, r) = (var(a), var(b));
    Ok(match op {
        IntOp::Add => format!("{l}.wrapping_add({r})"),
        IntOp::Sub => format!("{l}.wrapping_sub({r})"),
        IntOp::Mul => format!("{l}.wrapping_mul({r})"),
        // Div/Mod carry the C-001/C-002 abort discipline — route through the
        // same checked shims the CallFn path uses (one definition of the abort).
        IntOp::Div => {
            used_shims.push(shim("__chk_div").unwrap().2);
            format!("rt_chk_div({l}, {r})")
        }
        IntOp::Mod => {
            used_shims.push(shim("__chk_mod").unwrap().2);
            format!("rt_chk_mod({l}, {r})")
        }
        IntOp::Eq => format!("({l} == {r}) as i64"),
        IntOp::Ne => format!("({l} != {r}) as i64"),
        IntOp::Lt => format!("({l} < {r}) as i64"),
        IntOp::Le => format!("({l} <= {r}) as i64"),
        IntOp::Gt => format!("({l} > {r}) as i64"),
        IntOp::Ge => format!("({l} >= {r}) as i64"),
        other => return Err(wall(format!("native: int op {other:?} — outside rung 1"))),
    })
}

/// A user fn name that is a valid Rust identifier (dots from module paths).
fn mangle(name: &str) -> String {
    format!("almd_{}", name.replace(['.', '$'], "_"))
}

fn op_name(op: &Op) -> &'static str {
    match op {
        Op::Alloc { .. } => "Alloc",
        Op::Const { .. } => "Const",
        Op::ConstInt { .. } => "ConstInt",
        Op::Dup { .. } => "Dup",
        Op::Drop { .. } => "Drop",
        Op::Consume { .. } => "Consume",
        Op::Borrow { .. } => "Borrow",
        Op::MakeUnique { .. } => "MakeUnique",
        Op::Pure { .. } => "Pure",
        Op::Call { .. } => "Call",
        Op::CallFn { .. } => "CallFn",
        Op::CallImport { .. } => "CallImport",
        Op::CallIndirect { .. } => "CallIndirect",
        Op::FuncRef { .. } => "FuncRef",
        Op::IntBinOp { .. } => "IntBinOp",
        Op::Prim { .. } => "Prim",
        Op::IfThen { .. } => "IfThen",
        Op::Else { .. } => "Else",
        Op::EndIf { .. } => "EndIf",
        Op::LoopStart => "LoopStart",
        Op::LoopBreakUnless { .. } => "LoopBreakUnless",
        Op::LoopEnd => "LoopEnd",
        Op::SetLocal { .. } => "SetLocal",
        _ => "unknown",
    }
}
