#!/usr/bin/env bash
# Stdlib semantics manifest gate — §8 step 2 (#521).
#
# 1. COVERAGE: every Int-bearing fn in each covered module's bundled .almd
#    must have a manifest entry declaring its index_unit (signature-driven —
#    a new Int-bearing fn cannot land undeclared).
# 2. REGEN-AND-DIFF: the derived property test is regenerated from the
#    manifest probes and must match the committed file byte-for-byte (doc
#    and test cannot drift; the test failing at `almide test` means the
#    IMPLEMENTATION drifted from the declared semantics).
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - <<'PYEOF'
import os, re, subprocess, sys, tempfile, tomllib

# ratchet: append modules, never remove. Each module generates its OWN
# spec/stdlib/<module>_semantics_manifest_test.almd, so adding one leaves
# every already-covered module's committed file byte-identical.
COVERED_MODULES = ["string", "datetime", "bytes", "list", "math", "float", "io", "env", "random", "json", "value", "int", "process", "map", "set", "option", "result", "error", "regex", "bool", "testing", "args", "mem", "zlib", "path", "base64", "hex"]

with open("docs/stdlib/semantics-manifest.toml", "rb") as f:
    manifest = tomllib.load(f)

# The unit vocabularies are PINNED (#1244 burn-down: a landed forge set
# `default_index_unit = "bogus_unit"` and the gate stayed green — a typo'd
# unit spelling would silently declare nothing). Measured from the manifest
# on 2026-08-12; a NEW spelling is a deliberate taxonomy change made here
# and in the manifest in the same PR.
UNIT_VOCAB = {
    "address", "bit-pattern", "byte", "byte-count", "byte-offset",
    "byte-value", "civil-field", "codepoint", "count", "cursor", "day",
    "element-count", "element-index", "hour", "millisecond", "minute",
    "nanosecond", "ordering", "scalar", "second", "value",
}
DEFAULT_UNIT_VOCAB = {"byte-offset", "byte-value", "codepoint", "second", "value"}
REQUIRED_ENTRY_FIELDS = ("name", "index_unit", "probe", "expect")

failed = False
for module in COVERED_MODULES:
    d = manifest[module].get("default_index_unit")
    if d is not None and d not in DEFAULT_UNIT_VOCAB:
        print(f"BAD default_index_unit {d!r} on module {module} — vocabulary: "
              f"{sorted(DEFAULT_UNIT_VOCAB)}")
        failed = True
    for e in manifest[module]["fn"]:
        for k in REQUIRED_ENTRY_FIELDS:
            if not e.get(k):
                print(f"MISSING FIELD {k!r} on a {module} entry ({e.get('name', '?')})")
                failed = True
        u = e.get("index_unit")
        if u is not None and u not in UNIT_VOCAB:
            print(f"BAD index_unit {u!r} on {module}.{e.get('name', '?')} — "
                  f"vocabulary: {sorted(UNIT_VOCAB)}")
            failed = True
    entries = {e["name"]: e for e in manifest[module]["fn"]}
    src = open(f"stdlib/{module}.almd").read()
    int_fns = []
    for m in re.finditer(r'^(?:pub )?(?:effect )?fn (\w+)\(([^)]*)\)\s*->\s*([^=]+)=', src, re.M):
        name, params, ret = m.group(1), m.group(2), m.group(3)
        if re.search(r'\bInt\b', params) or re.search(r'\bInt\b', ret):
            int_fns.append(name)
    for name in int_fns:
        if name not in entries:
            print(f"MISSING: {module}.{name} bears Int in its signature but has no "
                  f"semantics-manifest entry (declare its index_unit + probe)")
            failed = True
    for name in entries:
        if name not in int_fns:
            print(f"STALE: manifest entry {module}.{name} matches no Int-bearing fn "
                  f"in stdlib/{module}.almd")
            failed = True

# The canonical form of a generated file is DEFINED as fmt(generator output):
# spec/ sits under the fmt --check CI gate (#919), so post-process through
# `almide fmt` — the two gates can then never disagree on these files, the
# generator never has to replicate the formatter's style choices, and the
# import line each module needs is the formatter's job, not the generator's.
def fmt_almd(text):
    almide = os.environ.get("ALMIDE_BIN", "almide")
    tf = tempfile.NamedTemporaryFile("w", suffix=".almd", delete=False)
    tf.write(text)
    tf.close()
    try:
        subprocess.run([almide, "fmt", tf.name], check=True, capture_output=True)
        return open(tf.name).read()
    finally:
        os.unlink(tf.name)

# Regenerate the derived property test — one file PER MODULE.
for module in COVERED_MODULES:
    lines = [
        "// GENERATED by scripts/check-semantics-manifest.sh from",
        "// docs/stdlib/semantics-manifest.toml — DO NOT EDIT (the gate",
        "// regenerates and diffs). Each case executes a manifest probe; a",
        "// failure here means the implementation drifted from the DECLARED",
        "// semantic dimension (#419 class).",
        "",
    ]
    for e in manifest[module]["fn"]:
        probe, unit = e["probe"], e["index_unit"]
        expect = e["expect"].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'test "{module}.{e["name"]} unit={unit}" {{')
        # Optional `setup` statements run before the probe. A probe is ONE
        # expression, and a block expression inside the interpolation walls the
        # wasm renderer — so a dimension needing two reads to compare (a clock's
        # monotonicity) has to bind them as statements first, not inline.
        for stmt in e.get("setup", []):
            lines.append(f"  {stmt}")
        lines.append(f'  assert_eq("${{{probe}}}", "{expect}")')
        lines.append("}")
        lines.append("")
    generated = fmt_almd("\n".join(lines))

    path = f"spec/stdlib/{module}_semantics_manifest_test.almd"
    try:
        committed = open(path).read()
    except FileNotFoundError:
        committed = ""
    if committed != generated:
        open(path + ".regen", "w").write(generated)
        print(f"DRIFT: {path} does not match the manifest — regenerate by copying "
              f"{path}.regen over it (or run this script's regen step)")
        failed = True

if failed:
    sys.exit(1)
n = sum(len(manifest[m]["fn"]) for m in COVERED_MODULES)
print(f"  semantics manifest: {len(COVERED_MODULES)} module(s), {n} entries, "
      f"coverage + regen-diff green")
PYEOF
