#!/usr/bin/env bash
# Every spec `*_test.almd` is seen by a runner, and builds (#3065).
#
# `spec/integration/extern_c/extern_c_test.almd` did not build for its whole
# life and no gate said so. It had no `test` block, so `almide test` never
# discovered it; it had `// wasm:skip` on its first line, so the output-parity
# gate (proofs/output-parity.sh, which runs every `fn main` program) skipped
# it; and `almide check` accepted its 3-argument `assert_eq`, which only rustc
# refused. A file in that state is invisible, not failing.
#
# For every git-tracked `spec/**/*_test.almd`:
#   A. a file whose first line declares `expected compile error` is a negative
#      fixture: `almide check` must REFUSE it (otherwise it tests nothing);
#   B. every other file must pass `almide check`;
#   C. and must be reachable by a runner: a `test "…"` block (`almide test`),
#      or a `fn main` without `// wasm:skip` on line 1 (output-parity), or be a
#      GENERATED semantics manifest (scripts/check-semantics-manifest.sh owns it).
#
#   ALMIDE_BIN=target/release/almide bash scripts/check-spec-test-files.sh
#   SPEC_FILES="a_test.almd b_test.almd" …   # the negative control's input
set -uo pipefail
export LC_ALL=C
cd "$(dirname "$0")/.." || exit 2
BIN="${ALMIDE_BIN:-target/release/almide}"
[ -x "$BIN" ] || { echo "::error::ALMIDE_BIN not executable: $BIN (cargo build --release)"; exit 2; }

if [ -n "${SPEC_FILES:-}" ]; then
  # shellcheck disable=SC2206
  files=($SPEC_FILES)
else
  files=()
  while IFS= read -r f; do files+=("$f"); done < <(git ls-files 'spec/*_test.almd')
fi
[ ${#files[@]} -gt 0 ] || { echo "::error::spec-test-files: no spec/*_test.almd files found — the gate lost its corpus"; exit 1; }

fail=0
negatives=0
for f in "${files[@]}"; do
  first="$(head -1 "$f")"
  if printf '%s' "$first" | grep -q 'expected compile error'; then
    negatives=$((negatives + 1))
    if "$BIN" check "$f" >/dev/null 2>&1; then
      echo "::error file=$f::spec-test-files: $f declares an expected compile error, and \`almide check\` accepts it"
      fail=1
    fi
    continue
  fi
  if ! out="$("$BIN" check "$f" 2>&1)"; then
    echo "::error file=$f::spec-test-files: $f does not pass \`almide check\`"
    printf '%s\n' "$out" | grep -E '^error' | head -3 | sed 's/^/    /'
    fail=1
  fi
  if grep -qE '^[[:space:]]*test[[:space:]]+"' "$f"; then continue; fi
  if grep -q 'fn main' "$f" && ! printf '%s' "$first" | grep -q 'wasm:skip'; then continue; fi
  if head -3 "$f" | grep -q 'GENERATED by scripts/check-semantics-manifest.sh'; then continue; fi
  echo "::error file=$f::spec-test-files: $f is run by nothing — no \`test\` block for \`almide test\`, and no \`fn main\` output-parity runs (it skips \`// wasm:skip\`). Write its checks as \`test\` blocks"
  fail=1
done

if [ "$fail" = 0 ]; then
  echo "spec-test-files OK: ${#files[@]} file(s) check and are run by a runner; $negatives expected-compile-error fixture(s) are refused"
fi
exit $fail
