#!/usr/bin/env bash
# Stdlib doc index freshness gate (#1469).
#
# Every docs/stdlib/*.md page carries a machine-owned block (signature index,
# and a type index where the module exports types) regenerated by
# tools/gen-stdlib-doc-index.py from the compiler's own module interface
# (`almide compile <module> --json`); the two clock-constructor pages derive
# theirs from crates/almide-types/src/time_units.rs. This wrapper runs the
# generator's --check (regenerate in memory, byte-compare, non-zero on drift)
# and is the enumerable script the gate-verification ledger rows — the .py is
# the generator, this is the gate.
#
# A page without a block is STALE, not exempt: the generator appends one, so
# the diff is non-empty and --check goes red. Coverage is therefore 45/45 by
# construction, never by a list.
#
# ALMIDE_BIN overrides the compiler binary (default: target/release/almide,
# falling back to `almide` on PATH — the generator's own rule).
set -euo pipefail
cd "$(dirname "$0")/.."

python3 tools/gen-stdlib-doc-index.py --check
pages=$(ls docs/stdlib/*.md | wc -l | tr -d ' ')
blocks=$(grep -l 'BEGIN GENERATED SIGNATURE INDEX' docs/stdlib/*.md | wc -l | tr -d ' ')
echo "  stdlib docs: ${blocks}/${pages} pages carry a generated block, all up to date"
