#!/usr/bin/env bash
# Stdlib semantics manifest gate — §8 step 2 (#521).
#
# 1. COVERAGE: every Int-bearing fn in each covered module's bundled .almd
#    must have a manifest entry declaring its index_unit (signature-driven —
#    a new Int-bearing fn cannot land undeclared).
# 2. REGEN-AND-DIFF: the derived property test is regenerated from the
#    manifest probes and must match the committed file byte-for-byte (doc
#    and test cannot drift; the test failing at `almide test` means the
#    IMPLEMENTATION drifted from the declared semantics).
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - <<'PYEOF'
import re, sys, tomllib

COVERED_MODULES = ["string"]  # ratchet: append modules, never remove

with open("docs/stdlib/semantics-manifest.toml", "rb") as f:
    manifest = tomllib.load(f)

failed = False
for module in COVERED_MODULES:
    entries = {e["name"]: e for e in manifest[module]["fn"]}
    src = open(f"stdlib/{module}.almd").read()
    int_fns = []
    for m in re.finditer(r'^(?:pub )?(?:effect )?fn (\w+)\(([^)]*)\)\s*->\s*([^=]+)=', src, re.M):
        name, params, ret = m.group(1), m.group(2), m.group(3)
        if re.search(r'\bInt\b', params) or re.search(r'\bInt\b', ret):
            int_fns.append(name)
    for name in int_fns:
        if name not in entries:
            print(f"MISSING: {module}.{name} bears Int in its signature but has no "
                  f"semantics-manifest entry (declare its index_unit + probe)")
            failed = True
    for name in entries:
        if name not in int_fns:
            print(f"STALE: manifest entry {module}.{name} matches no Int-bearing fn "
                  f"in stdlib/{module}.almd")
            failed = True

# Regenerate the derived property test.
lines = [
    "// GENERATED by scripts/check-semantics-manifest.sh from",
    "// docs/stdlib/semantics-manifest.toml — DO NOT EDIT (the gate",
    "// regenerates and diffs). Each case executes a manifest probe on",
    "// multibyte input; a failure here means the implementation drifted",
    "// from the DECLARED semantic dimension (#419 class, C-065).",
    "",
]
for module in COVERED_MODULES:
    for e in manifest[module]["fn"]:
        probe, unit = e["probe"], e["index_unit"]
        expect = e["expect"].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'test "{module}.{e["name"]} unit={unit}" {{')
        lines.append(f'  assert_eq("${{{probe}}}", "{expect}")')
        lines.append("}")
        lines.append("")
generated = "\n".join(lines)

path = "spec/stdlib/string_semantics_manifest_test.almd"
try:
    committed = open(path).read()
except FileNotFoundError:
    committed = ""
if committed != generated:
    open(path + ".regen", "w").write(generated)
    print(f"DRIFT: {path} does not match the manifest — regenerate by copying "
          f"{path}.regen over it (or run this script's regen step)")
    failed = True

if failed:
    sys.exit(1)
n = sum(len(manifest[m]["fn"]) for m in COVERED_MODULES)
print(f"  semantics manifest: {len(COVERED_MODULES)} module(s), {n} entries, "
      f"coverage + regen-diff green")
PYEOF
