#!/usr/bin/env python3
"""Downstream canary (#2839): roster -> matrix, leg results -> report.

  downstream-canary.py matrix [roster]                 JSON matrix for the workflow
  downstream-canary.py report <results-dir> [roster]   Markdown table on stdout;
                                                       exit 1 on any REGRESSION or
                                                       on any project without a verdict
  downstream-canary.py record <results-dir> [--baseline-tag vX.Y.Z]
                                                       advance the known-good ledger
                                                       from a run's baseline passes

<results-dir> holds one sub-directory per leg, named by the matrix `slug`,
each with the result.tsv written by scripts/downstream-canary.sh. A roster
project whose directory or result is missing is reported as infra (the leg
never delivered) — never as a pass, and never silently dropped: the report
counts every roster entry.

Known-good ledger (proofs/downstream-canary-known-good.toml): per project and
command, the newest release on which that command PASSED. A command that
fails on both the baseline and the candidate is a pre-existing failure
(fail/fail) — unless the ledger says it passed on an earlier release. Then
the break shipped in a release the canary did not gate (#2839 shipped in
v0.65.0 and read as fail/fail against it), and the command is a REGRESSION
(`good/FAIL`). The ledger only moves by `record`, which a person runs after
a clean canary (CLAUDE.md, Release Procedure) — never by the run itself, so
a run can never launder its own failure into the baseline.
"""
import json
import os
import sys
import tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_ROSTER = os.path.join(HERE, "downstream-canary.toml")
DEFAULT_LEDGER = os.path.join(os.path.dirname(HERE), "proofs", "downstream-canary-known-good.toml")
DEFAULT_TIMEOUT = 900


def load(roster):
    with open(roster, "rb") as f:
        projects = tomllib.load(f)["project"]
    seen = set()
    for p in projects:
        p["slug"] = p["repo"].replace("/", "__")
        if p["slug"] in seen:
            sys.exit(f"duplicate roster entry: {p['repo']}")
        seen.add(p["slug"])
        if not p.get("commands"):
            sys.exit(f"{p['repo']}: no commands")
    return projects


def matrix(roster):
    out = []
    for p in load(roster):
        out.append({
            "slug": p["slug"],
            "repo": p["repo"],
            "ref": p.get("ref", ""),
            "commands": "\n".join(p["commands"]),
            "timeout": p.get("timeout", DEFAULT_TIMEOUT),
        })
    print(json.dumps({"include": out}))


# Project verdict = the worst of its commands, in this order.
RANK = ["ok/FAIL", "good/FAIL", "infra", "ok/flaky", "FAIL/ok", "fail/fail", "ok/ok"]
REGRESSION = ("ok/FAIL", "good/FAIL")
LABEL = {
    "ok/FAIL": "**REGRESSION**",
    "good/FAIL": "**REGRESSION** (known good earlier)",
    "infra": "infra (no verdict)",
    "ok/flaky": "flaky",
    "FAIL/ok": "fixed",
    "fail/fail": "pre-existing failure",
    "ok/ok": "ok",
}


def tag_key(tag):
    """v0.65.0 -> (0, 65, 0); ledger entries are final releases only."""
    parts = tag.lstrip("v").split(".")
    if len(parts) != 3 or not all(x.isdigit() for x in parts):
        sys.exit(f"not a final release tag: {tag!r} (the ledger records finals only)")
    return tuple(int(x) for x in parts)


def load_ledger(path):
    """{(repo, command): {"tag":…, "project_sha":…}}"""
    if not os.path.exists(path):
        return {}
    with open(path, "rb") as f:
        entries = tomllib.load(f).get("known_good", [])
    ledger = {}
    for e in entries:
        tag_key(e["tag"])
        ledger[(e["repo"], e["command"])] = e
    return ledger


def write_ledger(path, ledger):
    q = lambda v: json.dumps(v, ensure_ascii=False)  # a TOML basic string
    out = [
        "# Downstream canary known-good ledger (#2839). GENERATED by",
        "# `scripts/downstream-canary-record.sh <run-id>` after a clean canary run —",
        "# do not hand-edit. One entry per (project, command): the newest FINAL",
        "# release on which the command passed, and the project commit it passed on.",
        "# The canary reads it to report a fail-on-both command as a REGRESSION when",
        "# an earlier release built it (see scripts/downstream-canary.py).",
    ]
    for (repo, cmd) in sorted(ledger):
        e = ledger[(repo, cmd)]
        out += ["", "[[known_good]]", f"repo = {q(repo)}", f"command = {q(cmd)}",
                f"tag = {q(e['tag'])}", f"project_sha = {q(e['project_sha'])}"]
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")


def read_leg(path):
    rows = []
    if not os.path.exists(path):
        return rows
    with open(path) as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            parts += [""] * (5 - len(parts))
            rows.append(parts[:5])
    return rows


def first_diagnostics(leg_dir, n, limit=40):
    log = os.path.join(leg_dir, f"cmd{n}.candidate.log")
    try:
        with open(log, errors="replace") as f:
            lines = f.read().splitlines()
    except OSError:
        return "(candidate log missing)"
    # Lead with the first error line when there is one.
    start = next((i for i, l in enumerate(lines) if "error" in l.lower()), 0)
    return "\n".join(lines[max(0, start - 2):start - 2 + limit])


def collect(results, projects):
    """Yield (project, leg_dir, sha, cmds, meta) for every roster entry."""
    for p in projects:
        leg_dir = os.path.join(results, p["slug"])
        leg = read_leg(os.path.join(leg_dir, "result.tsv"))
        sha, cmds, infra_reason, meta = "-", [], "", {}
        for kind, a, b, cls, detail in leg:
            if kind == "project":
                sha = b if b != "-" else sha
                if cls == "infra":
                    infra_reason = detail
            elif kind == "deps" and cls == "infra":
                infra_reason = detail
            elif kind == "meta":
                meta[a] = b
            elif kind == "cmd":
                cmds.append((a, b, cls, detail))
        ran = {c[0] for c in cmds}
        for c in p["commands"]:
            if c not in ran:
                cmds.append((c, "", "infra", infra_reason or "no result from the leg (job failed, timed out, or was cancelled)"))
        yield p, leg_dir, sha, cmds, meta


def report(results, roster, ledger_path=DEFAULT_LEDGER):
    projects = load(roster)
    ledger = load_ledger(ledger_path)
    rows, regressions = [], []
    tally = {k: 0 for k in RANK}
    for p, leg_dir, sha, cmds, _ in collect(results, projects):
        for i, (cmd, n, cls, detail) in enumerate(cmds):
            good = ledger.get((p["repo"], cmd))
            if cls == "fail/fail" and good:
                where = ("same project commit — the compiler is the only variable"
                         if good["project_sha"] == sha else
                         f"project moved {good['project_sha'][:9]}→{sha[:9]} since; "
                         f"rebuild HEAD with {good['tag']} to rule out downstream churn")
                cmds[i] = (cmd, n, "good/FAIL",
                           f"{detail}; passed on {good['tag']}, fails on baseline and candidate ({where})")
        verdict = min((c[2] for c in cmds), key=RANK.index)
        tally[verdict] += 1
        cells = ", ".join(f"`{c[0]}` {c[2]}" for c in cmds)
        notes = "; ".join(f"{c[0]}: {c[3]}" for c in cmds if c[2] not in ("ok/ok", "fail/fail") and c[3])
        if p.get("note"):
            notes = (notes + "; " if notes else "") + p["note"]
        short = sha[:9] if sha != "-" else "-"
        rows.append(f"| {p['repo']} | `{short}` | {LABEL[verdict]} | {cells} | {notes} |")
        for c in cmds:
            if c[2] in REGRESSION:
                regressions.append((p["repo"], short, c, first_diagnostics(leg_dir, c[1])))

    out = []
    head = ", ".join(f"{tally[k]} {LABEL[k].replace('**', '')}" for k in RANK if tally[k])
    out.append(f"**{len(projects)} projects:** {head}\n")
    out.append("| project | HEAD | verdict | commands (baseline/candidate) | notes |")
    out.append("|---|---|---|---|---|")
    out.extend(rows)
    if regressions:
        out.append("\n### Regressions — each blocks the tag until triaged\n")
        for repo, sha, (cmd, _, _, detail), diag in regressions:
            out.append(f"<details><summary>{repo}@{sha} — <code>almide {cmd}</code> ({detail})</summary>\n")
            out.append("```\n" + diag + "\n```\n</details>\n")
    if ledger:
        out.append(f"\nKnown-good ledger: {len(ledger)} (project, command) entries — a fail/fail "
                   "command that passed on an earlier release reads as `good/FAIL`.")
    if tally["infra"]:
        out.append(f"\n**{tally['infra']} project(s) produced no verdict (infra).** The run is "
                   "incomplete — re-run the failed legs before reading it as clean.")
    print("\n".join(out))
    return 1 if regressions or tally["infra"] else 0


def record(results, baseline_tag=None, roster=DEFAULT_ROSTER, ledger_path=DEFAULT_LEDGER):
    """Advance the ledger with every command that PASSED on the run's baseline.

    Only the baseline side is recorded: it is always a final release, while the
    candidate is an unreleased commit. An entry only moves forward (a newer
    release replaces an older one); a baseline failure never removes an entry —
    that is the whole point of the ledger.
    """
    projects = load(roster)
    ledger = load_ledger(ledger_path)
    seen_tags, advanced, added = set(), 0, 0
    for p, _, sha, cmds, meta in collect(results, projects):
        if "baseline" in meta:
            seen_tags.add(meta["baseline"])
        for cmd, _, cls, _ in cmds:
            if cls not in ("ok/ok", "ok/flaky", "ok/FAIL"):
                continue  # the baseline did not pass (or there is no verdict)
            tag = baseline_tag or meta.get("baseline")
            if not tag:
                sys.exit("the results carry no baseline tag; pass --baseline-tag")
            old = ledger.get((p["repo"], cmd))
            if old and tag_key(old["tag"]) >= tag_key(tag):
                continue
            ledger[(p["repo"], cmd)] = {"tag": tag, "project_sha": sha}
            if old:
                advanced += 1
            else:
                added += 1
    if baseline_tag and seen_tags - {baseline_tag}:
        sys.exit(f"--baseline-tag {baseline_tag} contradicts the results ({sorted(seen_tags)})")
    if len(seen_tags) > 1:
        sys.exit(f"results mix baselines: {sorted(seen_tags)}")
    write_ledger(ledger_path, ledger)
    print(f"ledger {os.path.relpath(ledger_path)}: {added} added, {advanced} advanced, {len(ledger)} entries")


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    if sys.argv[1] == "matrix":
        matrix(sys.argv[2] if len(sys.argv) > 2 else DEFAULT_ROSTER)
    elif sys.argv[1] == "report":
        sys.exit(report(sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else DEFAULT_ROSTER))
    elif sys.argv[1] == "record" and len(sys.argv) >= 3:
        tag = None
        if "--baseline-tag" in sys.argv:
            tag = sys.argv[sys.argv.index("--baseline-tag") + 1]
            tag_key(tag)
        record(sys.argv[2], tag)
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
