#!/usr/bin/env bash
# gen-mutation-score.sh — the mutation score, STAMPED (#2152 item 5).
#
# scripts/check-mutation-gate.sh judges each pre-authored mutant in
# ci/mutations/ (caught / SURVIVED / no longer applies) and exits red on any
# survivor; the full sweep runs in .github/workflows/mutation-sweep.yml on
# every develop push and nightly. Its verdict was a log line nobody could
# quote: no ledger held the score and the README said nothing about it.
#
# This script keeps the record, proofs/mutation-score.toml, in the stamped-
# ledger convention of proofs/ledger-counts.toml: dated, written from a
# MEASUREMENT (a sweep run's logs), rendered into README.md inside a dated
# `mutation-score:generated` block, and never regenerated by an ordinary PR.
# The sweep workflow's `score` job re-measures every run and goes red when
# the stamped counts drift from what the net just did (`--drift`); the README
# gate (ci.yml, lefthook) only demands that the block is the record rendered.
#
#   bash scripts/gen-mutation-score.sh --from-run <run-id>     # stamp from a mutation-sweep run (gh api, all shards)
#   bash scripts/gen-mutation-score.sh --from-log <file>...    # stamp from gate output(s) at hand
#   bash scripts/gen-mutation-score.sh --render                # rewrite the README block from the record
#   bash scripts/gen-mutation-score.sh --check                 # README block == record rendered, else exit 1
#   bash scripts/gen-mutation-score.sh --drift <file>...       # measured (gate output) vs stamped counts, exit 1 on drift
#
# Gate output lines read: `ok:   NAME caught (by KILLER)`, `FAIL: NAME SURVIVED`,
# `FAIL: NAME no longer applies`. Shards are merged by mutant name.
set -euo pipefail
export LC_ALL=C
cd "$(dirname "$0")/.." || exit 2

LEDGER="proofs/mutation-score.toml"
README="README.md"
REPO="almide/almide"

mode="${1:-}"
[ -n "$mode" ] || { sed -n '2,25p' "$0"; exit 2; }
shift

tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT

fetch_run() {
  # Every job's log of the run, concatenated. `gh run view --log` is refused
  # for a job that preempted; the per-job endpoint is always readable once
  # the job is complete.
  local run="$1" sha
  sha="$(gh run view "$run" -R "$REPO" --json headSha --jq .headSha)"
  : > "$tmp/merged.log"
  for j in $(gh run view "$run" -R "$REPO" --json jobs --jq '.jobs[].databaseId'); do
    gh api "repos/$REPO/actions/jobs/$j/logs" >> "$tmp/merged.log"
  done
  echo "$sha"
}

case "$mode" in
  --from-run)
    run="${1:?run id}"
    sha="$(fetch_run "$run")"
    source="https://github.com/$REPO/actions/runs/$run"
    logs=("$tmp/merged.log")
    ;;
  --from-log|--drift)
    [ $# -ge 1 ] || { echo "usage: $0 $mode <file>..." >&2; exit 2; }
    logs=("$@")
    sha="$(git rev-parse HEAD)"
    source="local:$(git rev-parse --short HEAD)"
    ;;
  --render|--check)
    logs=()
    ;;
  *) echo "unknown mode $mode" >&2; exit 2 ;;
esac

python3 - "$mode" "$LEDGER" "$README" "${sha:-}" "${source:-}" "${logs[@]}" <<'PY'
import datetime, os, re, subprocess, sys

mode, ledger, readme, sha, source = sys.argv[1:6]
logs = sys.argv[6:]

OK = re.compile(r"ok:\s+(\S+\.patch) caught \(by (\w+)\)")
SURV = re.compile(r"FAIL: (\S+\.patch) SURVIVED")
STALE = re.compile(r"FAIL: (\S+\.patch) no longer applies")

def measure(paths):
    verdict = {}
    for p in paths:
        for line in open(p, errors="replace"):
            line = line.rstrip("\r\n")
            m = OK.search(line)
            if m: verdict[m.group(1)] = ("caught", m.group(2)); continue
            m = SURV.search(line)
            if m: verdict[m.group(1)] = ("survived", ""); continue
            m = STALE.search(line)
            if m: verdict[m.group(1)] = ("stale", "")
    caught = sum(1 for v in verdict.values() if v[0] == "caught")
    survived = sum(1 for v in verdict.values() if v[0] == "survived")
    stale = sum(1 for v in verdict.values() if v[0] == "stale")
    in_tree = len([f for f in os.listdir("ci/mutations") if f.endswith(".patch")])
    killers = {}
    for v in verdict.values():
        if v[0] == "caught": killers[v[1]] = killers.get(v[1], 0) + 1
    return dict(mutants=len(verdict), caught=caught, survived=survived, stale=stale,
                mutants_in_tree=in_tree, killers=killers)

def pct(m):
    return 0.0 if m["mutants"] == 0 else round(100.0 * m["caught"] / m["mutants"], 1)

def read_ledger():
    d = {}
    for line in open(ledger):
        line = line.strip()
        if not line or line.startswith("#"): continue
        k, v = line.split("=", 1)
        d[k.strip()] = v.strip().strip('"')
    return d

def write_ledger(m, date):
    body = f'''# MUTATION SCORE — the verdict of the full net sweep, STAMPED (#2152 item 5).
#
# scripts/check-mutation-gate.sh applies each pre-authored mutant in
# ci/mutations/ to the wasm backend and demands that the release-shape net
# (crates/almide-wasm tests: --lib, backend_parity, fuzz_differential,
# alias_semantics, tail_calls) goes RED. The full sweep is
# .github/workflows/mutation-sweep.yml (every develop push, nightly); its
# `score` job re-measures this record on every run and fails on drift.
#
# Refresh:  bash scripts/gen-mutation-score.sh --from-run <sweep run id>
#           (stamps this file and re-renders the README block). An ordinary
#           PR never refreshes it; a mutant PR (ci/mutations/) does not
#           either — the next sweep judges the tree and names the drift.
# Rendered into README.md by scripts/gen-mutation-score.sh --render.
date            = "{date}"
source          = "{source}"
head_sha        = "{sha}"
mutants         = {m["mutants"]}
caught          = {m["caught"]}
survived        = {m["survived"]}
stale           = {m["stale"]}
score_pct       = {pct(m)}
mutants_in_tree = {m["mutants_in_tree"]}
killers         = "{', '.join(f'{k} {v}' for k, v in sorted(m["killers"].items(), key=lambda kv: -kv[1]))}"
'''
    open(ledger, "w").write(body)

def render(d):
    src = d["source"]
    if src.startswith("https://"):
        run_id = src.rstrip("/").split("/")[-1]
        src_md = f"mutation-sweep run [{run_id}]({src})"
    else:
        src_md = f"a local sweep ({src})"
    start = (f"<!-- mutation-score:generated:start (as of {d['date']}) — stamped from "
             f"proofs/mutation-score.toml by scripts/gen-mutation-score.sh; re-measured by every "
             f"mutation-sweep run, refreshed only by `--from-run`; DO NOT EDIT between the markers -->")
    line = (f"**Mutation score** — {d['caught']}/{d['mutants']} mutants caught ({d['score_pct']} %), "
            f"{d['survived']} survived, {d['stale']} stale: the full release-shape net sweep of "
            f"`ci/mutations/` ([`scripts/check-mutation-gate.sh`](./scripts/check-mutation-gate.sh)), "
            f"stamped {d['date']} from {src_md} at `{d['head_sha'][:9]}`.")
    end = "<!-- mutation-score:generated:end -->"
    return f"{start}\n{line}\n{end}"

BLOCK = re.compile(r"<!-- mutation-score:generated:start.*?<!-- mutation-score:generated:end -->", re.S)

def readme_block():
    m = BLOCK.search(open(readme).read())
    return m.group(0) if m else None

def rewrite_readme(block):
    text = open(readme).read()
    if BLOCK.search(text):
        text = BLOCK.sub(lambda _: block, text)
    else:
        anchor = "<!-- stats:generated:end -->\n"
        assert anchor in text, "README.md: no stats:generated:end anchor to place the block after"
        text = text.replace(anchor, anchor + "\n" + block + "\n", 1)
    open(readme, "w").write(text)

if mode in ("--from-run", "--from-log"):
    m = measure(logs)
    if m["mutants"] == 0:
        sys.exit("mutation-score: no verdict line found in the log(s) — nothing to stamp")
    date = datetime.date.today().isoformat()
    write_ledger(m, date)
    rewrite_readme(render(read_ledger()))
    print(f"mutation-score: stamped {date} — {m['caught']}/{m['mutants']} caught ({pct(m)} %), "
          f"{m['survived']} survived, {m['stale']} stale, from {source}; README block re-rendered.")
    if m["mutants"] != m["mutants_in_tree"]:
        print(f"mutation-score: NOTE the run reported {m['mutants']} mutants, the tree holds {m['mutants_in_tree']} — "
              f"stamp from a run of this tree, or expect the next sweep to name the drift.")
elif mode == "--drift":
    d = read_ledger(); m = measure(logs)
    drift = [(k, d[k], str(m[k])) for k in ("mutants", "caught", "survived", "stale") if d[k] != str(m[k])]
    if m["mutants"] == 0:
        sys.exit("::error::mutation-score: no verdict line found in the log(s) — the sweep output is not what the reader expects")
    if drift:
        for k, old, new in drift:
            print(f"  {k}: stamped {old}, measured {new}")
        sys.exit(f"::error::mutation-score: {len(drift)} stamped count(s) drifted from this sweep (stamped {d['date']} from {d['source']}) — refresh: bash scripts/gen-mutation-score.sh --from-run <this run id>")
    print(f"mutation-score: OK — {m['caught']}/{m['mutants']} caught matches the record stamped {d['date']}.")
elif mode == "--render":
    rewrite_readme(render(read_ledger()))
    print("mutation-score: README block rendered from the record.")
elif mode == "--check":
    want = render(read_ledger()); got = readme_block()
    if got is None:
        sys.exit("::error::README.md: mutation-score block missing — run: bash scripts/gen-mutation-score.sh --render")
    if got != want:
        sys.exit("::error::README.md: mutation-score block differs from proofs/mutation-score.toml rendered — run: bash scripts/gen-mutation-score.sh --render")
    print("mutation-score: README block is the record rendered.")
PY
