#!/usr/bin/env bash
# org-trust-status.sh — sweep the github.com/almide org's Almide-written repos through the v1
# trust-spine lowering wall and regenerate docs/org-trust-status.md.
#
# For each repo it runs the MIR `classify_corpus` example over the repo's entry module and records:
#   - lowers   : functions in the v1 lowering subset (the proven-checker re-verifies each)
#   - walls    : functions explicitly walled (Unsupported) — honest, never a silent miscompile
#   - status   : ✅ wall=0  /  N walls
#   - top wall : the most frequent wall reason (the lever — one brick clears a whole class)
#
# ⚠ A wall count of 0 means "every function is INSIDE the lowering subset", NOT "byte-verified".
# The real ② gate is a v0==v1 byte-match (run the repo's own vectors/tests on native AND wasm).
# `lowers but not byte-verified` is exactly the trap that produced a fake sha1=0 before the
# `var v=w` aliasing miscompile was found by byte-matching the RFC 3174 vectors. Keep that order:
# wall=0 first, byte-match SECOND and AUTHORITATIVE.
#
# Usage:
#   scripts/org-trust-status.sh                 # sweep + rewrite docs/org-trust-status.md
#   ALMIDE_ORG_DIR=/path/to/almide scripts/org-trust-status.sh
#
# Env:
#   ALMIDE_ORG_DIR  the dir holding the sibling org repos (default: parent of the main almide repo)
set -euo pipefail

# Build + binary + output live in THIS working tree (a git worktree may differ from the main repo).
work_root="$(git rev-parse --show-toplevel)"
# The org dir holds the sibling target repos (yaml, sha1, …) next to the MAIN almide repo.
main_repo="$(cd "$(git rev-parse --git-common-dir)/.." && pwd)"
ORG_DIR="${ALMIDE_ORG_DIR:-$(dirname "$main_repo")}"
OUT="$work_root/docs/org-trust-status.md"
BIN="$work_root/target/debug/examples/classify_corpus"

echo "building classify_corpus…" >&2
( cd "$work_root" && cargo build -q -p almide-mir --example classify_corpus )

# The repos verified by a real v0==v1 byte-match (not just wall=0). Update as new ones are checked.
BYTE_VERIFIED=" yaml sha1 "

# The Almide-LIBRARY entry, taken ONLY from `src/` (a real module root), never from embedded shims
# (`stdlib/`) or benchmark fixtures (`research/`, `benchmark/`) — those misfired into bogus repo-level
# numbers (e.g. almide-fable-llm, a Rust project, reported a random MSR benchmark file). `sort` makes
# the pick deterministic. Empty result ⇒ the repo is not a single-module Almide library.
find_entry() {
  local d="$1"
  for c in "src/mod.almd" "src/lib.almd" "src/$(basename "$d").almd"; do
    [ -f "$d/$c" ] && { echo "$d/$c"; return; }
  done
  find "$d/src" -maxdepth 2 -name '*.almd' 2>/dev/null | grep -vE '_test\.almd' | sort | head -1 || true
}

tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
mkdir -p "$tmp/o"                                          # classify_corpus --out needs an existing dir
rows=""; allwalls="$tmp/allwalls.txt"; : > "$allwalls"
total_lower=0; total_wall=0; clean=0; counted=0

for d in "$ORG_DIR"/*/; do
  repo="$(basename "$d")"
  [ "$repo" = "almide" ] && continue                       # the compiler itself is the v0 corpus, not a target
  entry="$(find_entry "${d%/}")"
  if [ -z "$entry" ]; then
    rows="${rows}| \`$repo\` | — | — | ▫ not an Almide \`src/\` library | — |\n"
    continue
  fi
  out="$(WALL_NAMES=1 "$BIN" --out "$tmp/o" "$entry" 2>&1 || true)"
  ip="$(printf '%s' "$out" | grep -oE 'in-profile \(lowers\)[ ]*: [0-9]+' | grep -oE '[0-9]+$' || true)"
  wl="$(printf '%s' "$out" | grep -oE 'walled \(Unsupported\)[ ]*: [0-9]+' | grep -oE '[0-9]+$' || true)"
  [ -z "$ip" ] && continue                                  # parse/entry failure — skip silently
  counted=$((counted + 1))
  total_lower=$((total_lower + ip)); total_wall=$((total_wall + wl))
  printf '%s' "$out" | grep 'WALLED' | sed -E 's#^WALLED [^:]*:: [a-z0-9_]+ :: ##' >> "$allwalls" || true
  top="$(printf '%s' "$out" | grep 'WALLED' | sed -E 's#^WALLED [^:]*:: [a-z0-9_]+ :: ##; s/`[^`]*`/X/g; s/[0-9]+/N/g' | sort | uniq -c | sort -rn | head -1 | sed -E 's/^ *[0-9]+ //' | cut -c1-60 || true)"
  if [ "${ip}" = "0" ] && [ "${wl}" = "0" ]; then
    status="▫ entry has no in-subset fns"   # a barrel / re-export entry — not a real wall=0
    top="—"
  elif [ "${wl:-1}" = "0" ]; then
    clean=$((clean + 1))
    case "$BYTE_VERIFIED" in *" $repo "*) status="✅ 0 — byte-verified";; *) status="🟡 0 — lowers, byte-match TODO";; esac
    top="—"
  else
    status="🔴 $wl"
  fi
  rows="${rows}| \`$repo\` | $ip | $wl | $status | $top |\n"
done

agg="$(sed -E 's/`[^`]*`/X/g; s/[0-9]+/N/g' "$allwalls" | sort | uniq -c | sort -rn | head -12 \
        | sed -E 's/^ *([0-9]+) (.*)$/| \1 | \2 |/' | cut -c1-100)"

{
  echo "# Almide org — v1 trust-spine status"
  echo
  echo "> Auto-generated by \`scripts/org-trust-status.sh\`. Re-run to refresh. Org dir: \`$ORG_DIR\`."
  echo
  echo "**${clean}/${counted} repos at wall=0**, ${total_lower} functions lowering / ${total_wall} walled across the swept entries."
  echo
  echo "⚠ **wall=0 ≠ correct.** It means every function is inside the v1 lowering subset, NOT that the"
  echo "output is byte-identical to v0. The authoritative ② gate is a **v0==v1 byte-match** (run the repo's"
  echo "own vectors/tests on native AND \`--target wasm\`). \`🟡 lowers, byte-match TODO\` flags repos that"
  echo "reached wall=0 but have not yet been byte-verified — exactly where a silent miscompile can hide"
  echo "(e.g. the \`var v=w\` scalar-aliasing bug that faked an early sha1=0 until the RFC vectors caught it)."
  echo
  echo "## Per-repo (sorted by walls)"
  echo
  echo "| repo | lowers | walls | status | top wall reason |"
  echo "|------|-------:|------:|--------|-----------------|"
  printf '%b' "$rows" | sort -t'|' -k4 -rn
  echo
  echo "## Cross-repo wall lever (most frequent reasons)"
  echo
  echo "One brick that clears a top reason advances multiple repos at once."
  echo
  echo "| count | wall reason (normalized) |"
  echo "|------:|--------------------------|"
  echo "$agg"
  echo
  echo "## Notes"
  echo
  echo "- Only each repo's **entry module** is swept; a multi-file repo's other \`src/*.almd\` are not yet counted."
  echo "- The \`almide\` repo itself is the v0 corpus (its own \`proofs/corpus-wall.sh\` gate), not a target here."
  echo "- To byte-verify a repo: render its functions to wasm and diff v0 (native) vs v1 (wasmtime) over the"
  echo "  repo's test vectors, then add it to \`BYTE_VERIFIED\` in the script."
} > "$OUT"

echo "wrote $OUT (${clean}/${counted} at wall=0)" >&2
