//! AST parity gate (unit 2): the ported lexer+parser must reproduce, byte for
//! byte, the `--emit-ast` output of the ORACLE almide binary built from the
//! clean port SHA (almide@a877d2138) over the entire ported `spec/` corpus.
//!
//! Goldens are sha256 hashes (`golden/spec-ast-manifest.txt`, generated by
//! `scripts/gen-ast-manifest.sh`); the hashed text is "pretty JSON + one \n",
//! which is exactly what the incumbent's `emit_ast_output` prints
//! (src/cli/emit.rs:98-103: `serde_json::to_string_pretty` + `out`).
//!
//! No silent gaps: every `spec/**/*.almd` must appear in exactly one of the
//! manifest or the exclusion list (files the oracle itself could not
//! `--emit-ast`, each with its recorded reason).

use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..").canonicalize().unwrap()
}

/// Parse `key<TAB>value` lines keyed by the SECOND column (the path) — two
/// identical source files legitimately share one AST hash, so the path is
/// the unique column, never the hash.
fn load_tsv_by_path(path: &Path, path_col_second: bool) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for l in std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("{}: {e} (run scripts/gen-ast-manifest.sh)", path.display()))
        .lines()
    {
        let (a, b) = l.split_once('\t').unwrap_or_else(|| panic!("malformed line: {l}"));
        let (key, val) = if path_col_second { (b, a) } else { (a, b) };
        assert!(out.insert(key.to_string(), val.to_string()).is_none(), "duplicate path {key}");
    }
    out
}

fn walk_almd(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in std::fs::read_dir(dir).unwrap() {
        let p = entry.unwrap().path();
        if p.is_dir() {
            walk_almd(&p, out);
        } else if p.extension().is_some_and(|e| e == "almd") {
            out.push(p);
        }
    }
}

#[test]
fn spec_corpus_ast_matches_oracle_hashes() {
    let root = workspace_root();
    let golden = root.join("crates/almide-syntax/tests/golden");
    let manifest = load_tsv_by_path(&golden.join("spec-ast-manifest.txt"), true);
    let exclusions = load_tsv_by_path(&golden.join("spec-ast-exclusions.txt"), false);

    // Coverage: every corpus file is gated or excluded-with-reason, never both.
    let mut files = Vec::new();
    walk_almd(&root.join("spec"), &mut files);
    files.sort();
    assert!(!files.is_empty());
    for f in &files {
        let rel = f.strip_prefix(&root).unwrap().to_string_lossy().to_string();
        let in_m = manifest.contains_key(&rel);
        let in_e = exclusions.contains_key(&rel);
        assert!(in_m ^ in_e, "{rel}: must be in exactly one of manifest/exclusions (manifest={in_m}, excluded={in_e})");
    }
    assert_eq!(files.len(), manifest.len() + exclusions.len(), "stale manifest entries for files no longer in spec/");

    // Parity: parse each manifest file with the ported syntax crate and match
    // the oracle hash. The file path handed to the parser is the same
    // RELATIVE path the oracle saw, so any path embedded in the AST agrees.
    let mut mismatches = Vec::new();
    for (rel, want) in &manifest {
        let input = std::fs::read_to_string(root.join(rel)).unwrap();
        let tokens = almide_syntax::lexer::Lexer::tokenize(&input);
        let mut parser = almide_syntax::parser::Parser::new(tokens).with_file(rel);
        let prog = parser
            .parse()
            .unwrap_or_else(|e| panic!("{rel}: oracle parsed this but greenfield failed: {e}"));
        assert!(parser.errors.is_empty(), "{rel}: oracle emitted AST but greenfield has parse errors: {:?}", parser.errors[0]);
        let json = serde_json::to_string_pretty(&prog).unwrap();
        let got = format!("{:x}", Sha256::digest(format!("{json}\n").as_bytes()));
        if got != *want {
            mismatches.push(rel.clone());
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} of {} files diverge from the oracle AST, first: {} (regenerate a diff locally: ORACLE=<a877d2138 build> almide {} --emit-ast)",
        mismatches.len(), manifest.len(), mismatches[0], mismatches[0]
    );
}
