// The CLI is never built without the embedded wasm host: `run`, `bench` and
// `build --target wasm` are its callers. The feature exists for LIBRARY
// consumers that compile to wasm32 themselves (almide/playground), where
// wasmtime cannot be built — see the `almide-wasm-run` note in Cargo.toml.
#[cfg(not(feature = "embedded-host"))]
compile_error!("the `almide` binary requires the `embedded-host` feature (default); only the library builds without it");

mod cli;
mod cli_args;
mod compile_driver;
mod dispatch;

// Bring library modules into binary crate scope so cli/ submodules can use `crate::*`.
pub use almide::{
    ast, canonicalize, check, codegen, diagnostic, diagnostic_render, fmt,
    import_table, intern, ir, lexer, lower, mono, optimize,
    parser, project, project_fetch, resolve, stdlib, types,
    out, out_no_nl, err, err_no_nl, WASM_WALL_MARKER,
};

// `cli/*.rs` call these via `crate::<name>` — re-exported here (private,
// visible to descendants of the crate root) so those call sites don't need
// to change after the `compile_driver` split.
use compile_driver::{parse_file, try_compile, register_versioned_module_names, lower_one_user_module, try_compile_with_ir};

use std::process::Command;

/// When true, suppress warning output during compilation (used by REPL).
pub(crate) static SUPPRESS_WARNINGS: std::sync::atomic::AtomicBool =
    std::sync::atomic::AtomicBool::new(false);

fn warnings_suppressed() -> bool {
    SUPPRESS_WARNINGS.load(std::sync::atomic::Ordering::Relaxed)
}
use clap::Parser;
use cli_args::Cli;
use dispatch::dispatch;


fn find_rustc() -> String {
    if Command::new("rustc").arg("--version").output().is_ok() {
        return "rustc".to_string();
    }
    if let Some(home) = std::env::var_os("HOME") {
        let cargo_rustc = std::path::PathBuf::from(home).join(".cargo/bin/rustc");
        if cargo_rustc.exists() {
            return cargo_rustc.to_string_lossy().to_string();
        }
    }
    "rustc".to_string()
}

fn collect_almd_files(dir: &std::path::Path, out: &mut Vec<String>) {
    if let Ok(entries) = std::fs::read_dir(dir) {
        let mut entries: Vec<_> = entries.filter_map(|e| e.ok()).collect();
        entries.sort_by_key(|e| e.path());
        for entry in entries {
            let path = entry.path();
            if path.is_dir() {
                collect_almd_files(&path, out);
            } else if path.extension().map_or(false, |ext| ext == "almd") {
                out.push(path.to_string_lossy().to_string());
            }
        }
    }
}


/// #782 retirement step 2: `--no-verified` (the legacy v0 escape hatch) is now a HARD
/// ERROR — v0.30.0 shipped one release of the deprecation notice, and the v0 emitters
/// are build-only CI parity oracles from here. `ALMIDE_NO_VERIFIED_OK=1` keeps the flag
/// working for the sanctioned oracle harnesses (org-byte-verify / frees-churn / the
/// differential tests), whose v0 invocations ARE the parity gate, not user escapes.
fn warn_no_verified_deprecated(no_verified: bool) {
    if no_verified && !almide_base::env::flag("ALMIDE_NO_VERIFIED_OK") {
        err(&format!(
            "error: --no-verified (the legacy v0 codegen path) has been removed; the \
             verified renderer is byte-identical where it lowers and falls back to v0 \
             automatically, so the flag should never be needed. If a program genuinely \
             needs it, file an issue: https://github.com/almide/almide/issues"
        ));
        std::process::exit(1);
    }
}

fn resolve_file(file: Option<String>) -> String {
    file.unwrap_or_else(|| {
        if std::path::Path::new("almide.toml").exists() {
            // Early-validate package name before looking for entry point
            match crate::project::parse_toml(std::path::Path::new("almide.toml")) {
                Err(e) if e.contains("hyphens") => {
                    err(&format!("error: {}", e));
                    std::process::exit(1);
                }
                _ => {}
            }
            // src/mod.almd = package entry point, src/main.almd = executable entry point
            for entry in &["src/mod.almd", "src/main.almd"] {
                if std::path::Path::new(entry).exists() {
                    return entry.to_string();
                }
            }
            err(&format!("almide.toml found but no entry point (src/mod.almd or src/main.almd)."));
            err(&format!("Create src/mod.almd (library) or src/main.almd (executable)."));
            std::process::exit(1);
        } else {
            err(&format!("No file specified and no almide.toml found."));
            err(&format!("Run 'almide init' to create a project, or specify a file."));
            std::process::exit(1);
        }
    })
}

// The `docs/diagnostics/<CODE>.md` reference texts, embedded at build time
// (generated by build.rs — see `embed_diagnostic_docs`). This used to be a disk
// probe (a 6-level parent walk from the executable, plus an env override of
// the directory) backed by a hardcoded E001–E010 fallback
// table: from a checkout every code explained, from an installed binary 21 of
// the documented codes answered "Unknown error code" — while
// docs/diagnostics/README.md told users to run exactly this command (#923). The
// embedded table is the binary-alone delivery, so both the walk and the
// fallback (a hand-maintained SECOND copy of ten docs, drifted from the real
// ones by construction) are gone.
include!(concat!(env!("OUT_DIR"), "/diagnostic_docs.rs"));

fn print_error_explanation(code: &str) {
    // `e005` means E005 — the old disk probe answered that only on
    // case-insensitive filesystems (macOS yes, Linux no), which is exactly the
    // kind of host-dependent behavior the embedded table exists to end.
    let code = code.to_ascii_uppercase();
    match DIAGNOSTIC_DOCS.iter().find(|(k, _)| *k == code) {
        Some((_, doc)) => out(&format!("{}", doc)),
        None => {
            err(&format!("Unknown error code: {}", code));
            std::process::exit(1);
        }
    }
}

/// The parse → check → lower → emit pipeline is deeply recursive: AST and IR
/// walks, and type-directed codegen (e.g. `emit_eq_typed` / `emit_ord_cmp3`,
/// container-literal emission) recurse with the shape of the input program. A
/// sufficiently deep or wide machine-generated expression can therefore exhaust
/// the OS's *default* main-thread stack — which is platform-dependent: ~8 MiB on
/// Linux/macOS but only ~1 MiB on Windows. That made compilation depth a silent
/// cross-platform divergence (a program that compiled on Unix overflowed the
/// stack mid-codegen on Windows). We follow the same strategy production
/// compilers use (rustc spawns its driver on an enlarged thread): run the whole
/// driver on a worker thread with a large, fixed stack, so the achievable
/// recursion depth is bounded by heap and identical on every host. The size is a
/// virtual reservation — pages are committed lazily as the stack grows — so it
/// costs no physical memory for shallow programs.
///
/// Overridable via `ALMIDE_COMPILER_STACK` (bytes), the analogue of rustc's
/// `RUST_MIN_STACK`: a non-numeric or empty value falls back to the default. The
/// override exists mainly so a regression test can pin a deliberately small
/// stack and prove that compilation stays within bounded native stack on wide /
/// deep input (see `tests/compiler_stack_test.rs`).
const COMPILER_STACK_SIZE: usize = 256 * 1024 * 1024; // 256 MiB

fn compiler_stack_size() -> usize {
    match almide_base::env::var("ALMIDE_COMPILER_STACK") {
        Some(v) => v.trim().parse::<usize>().ok().filter(|n| *n > 0).unwrap_or(COMPILER_STACK_SIZE),
        None => COMPILER_STACK_SIZE,
    }
}

fn main() {
    // #2205: which ALMIDE_* switches this run was started with — the ones a
    // forced route or a bypassed gate is announced for. Before any read.
    almide_base::env::inherit();
    let child = std::thread::Builder::new()
        .name("almide-main".to_string())
        .stack_size(compiler_stack_size())
        .spawn(run_main)
        .expect("failed to spawn the compiler driver thread");
    // A panic on the worker thread has already printed via the default hook;
    // mirror the main-thread panic exit code (101) so behavior is unchanged.
    if child.join().is_err() {
        std::process::exit(101);
    }
}

fn run_main() {
    crate::diagnostic_render::init_color();
    // Legacy mode: `almide file.almd [--target X]` → rewrite as `almide emit file.almd [--target X]`
    let raw_args: Vec<String> = std::env::args().collect();
    if raw_args.len() >= 2
        && !raw_args[1].starts_with('-')
        && (raw_args[1].ends_with(".almd") || raw_args[1].ends_with(".json"))
    {
        let mut new_args = vec![raw_args[0].clone(), "emit".to_string()];
        new_args.extend_from_slice(&raw_args[1..]);
        let cli = Cli::parse_from(new_args);
        dispatch(cli);
        return;
    }

    let cli = Cli::parse();
    dispatch(cli);
}
