/// Collection modules: list, map.

// ──────────────────────────────── list ────────────────────────────────

pub(super) const MOD_LIST_TS: &str = r#"const __almd_list = {
  len<T>(xs: T[]): number { return xs.length; },
  get<T>(xs: T[], i: number): T | null { return (i >= 0 && i < xs.length) ? xs[i] : null; },
  get_or<T>(xs: T[], i: number, d: T): T { return (i >= 0 && i < xs.length) ? xs[i] : d; },
  set<T>(xs: T[], i: number, v: T): T[] { const r = [...xs]; if (i >= 0 && i < r.length) r[i] = v; return r; },
  swap<T>(xs: T[], i: number, j: number): T[] { const r = [...xs]; if (i >= 0 && i < r.length && j >= 0 && j < r.length) { const t = r[i]; r[i] = r[j]; r[j] = t; } return r; },
  sort<T>(xs: T[]): T[] { return [...xs].sort(); },
  reverse<T>(xs: T[]): T[] { return [...xs].reverse(); },
  any<T>(xs: T[], f: (x: T) => boolean): boolean { return xs.some(f); },
  all<T>(xs: T[], f: (x: T) => boolean): boolean { return xs.every(f); },
  contains<T>(xs: T[], x: T): boolean { return xs.includes(x); },
  each<T>(xs: T[], f: (x: T) => void): void { xs.forEach(f); },
  map<T, U>(xs: T[], f: (x: T) => U): U[] { return xs.map(f); },
  filter<T>(xs: T[], f: (x: T) => boolean): T[] { return xs.filter(f); },
  find<T>(xs: T[], f: (x: T) => boolean): T | null { return xs.find(f) ?? null; },
  fold<T, U>(xs: T[], init: U, f: (acc: U, x: T) => U): U { return xs.reduce(f, init); },
  enumerate<T>(xs: T[]): [number, T][] { return xs.map((x, i) => [i, x]); },
  zip<T, U>(a: T[], b: U[]): [T, U][] { return a.slice(0, Math.min(a.length, b.length)).map((x, i) => [x, b[i]]); },
  flatten<T>(xss: T[][]): T[] { return xss.flat(); },
  take<T>(xs: T[], n: number): T[] { return xs.slice(0, n); },
  drop<T>(xs: T[], n: number): T[] { return xs.slice(n); },
  sort_by<T>(xs: T[], f: (x: T) => any): T[] { return [...xs].sort((a, b) => { const ka = f(a), kb = f(b); return ka < kb ? -1 : ka > kb ? 1 : 0; }); },
  unique<T>(xs: T[]): T[] { const seen: T[] = []; return xs.filter(x => { if (seen.includes(x)) return false; seen.push(x); return true; }); },
  index_of<T>(xs: T[], x: T): number | null { const i = xs.indexOf(x); return i >= 0 ? i : null; },
  chunk<T>(xs: T[], n: number): T[][] { const r: T[][] = []; for (let i = 0; i < xs.length; i += n) r.push(xs.slice(i, i + n)); return r; },
  filter_map<T, U>(xs: T[], f: (x: T) => U | null): U[] { const r: U[] = []; for (const x of xs) { const v = f(x); if (v !== null) r.push(v); } return r; },
  take_while<T>(xs: T[], f: (x: T) => boolean): T[] { const r: T[] = []; for (const x of xs) { if (!f(x)) break; r.push(x); } return r; },
  drop_while<T>(xs: T[], f: (x: T) => boolean): T[] { let dropping = true; const r: T[] = []; for (const x of xs) { if (dropping && f(x)) continue; dropping = false; r.push(x); } return r; },
  count<T>(xs: T[], f: (x: T) => boolean): number { return xs.filter(f).length; },
  partition<T>(xs: T[], f: (x: T) => boolean): [T[], T[]] { const a: T[] = [], b: T[] = []; for (const x of xs) { if (f(x)) a.push(x); else b.push(x); } return [a, b]; },
  reduce<T>(xs: T[], f: (a: T, b: T) => T): T | null { if (xs.length === 0) return null; return xs.reduce(f); },
  group_by<T, K>(xs: T[], f: (x: T) => K): Map<K, T[]> { const m = new Map<K, T[]>(); for (const x of xs) { const k = f(x); if (!m.has(k)) m.set(k, []); m.get(k)!.push(x); } return m; },
  last<T>(xs: T[]): T | null { return xs.length > 0 ? xs[xs.length - 1] : null; },
  first<T>(xs: T[]): T | null { return xs.length > 0 ? xs[0] : null; },
  sum(xs: number[]): number { return xs.reduce((a, b) => a + b, 0); },
  product(xs: number[]): number { return xs.reduce((a, b) => a * b, 1); },
  is_empty<T>(xs: T[]): boolean { return xs.length === 0; },
  flat_map<T, U>(xs: T[], f: (x: T) => U[]): U[] { return xs.flatMap(f); },
  min<T>(xs: T[]): T | null { return xs.length === 0 ? null : xs.reduce((a, b) => a < b ? a : b); },
  max<T>(xs: T[]): T | null { return xs.length === 0 ? null : xs.reduce((a, b) => a > b ? a : b); },
  join(xs: string[], sep: string): string { return xs.join(sep); },
  range(start: number, end: number): number[] { const r: number[] = []; for (let i = start; i < end; i++) r.push(i); return r; },
  slice<T>(xs: T[], start: number, end: number): T[] { return xs.slice(start, end); },
  insert<T>(xs: T[], i: number, v: T): T[] { const r = [...xs]; r.splice(i, 0, v); return r; },
  remove_at<T>(xs: T[], i: number): T[] { const r = [...xs]; if (i >= 0 && i < r.length) r.splice(i, 1); return r; },
  find_index<T>(xs: T[], f: (x: T) => boolean): number | null { const i = xs.findIndex(f); return i >= 0 ? i : null; },
  update<T>(xs: T[], i: number, f: (x: T) => T): T[] { const r = [...xs]; if (i >= 0 && i < r.length) r[i] = f(r[i]); return r; },
  repeat<T>(v: T, n: number): T[] { return Array(Math.max(0, n)).fill(v); },
  scan<T, U>(xs: T[], init: U, f: (acc: U, x: T) => U): U[] { let acc = init; return xs.map(x => { acc = f(acc, x); return acc; }); },
  intersperse<T>(xs: T[], sep: T): T[] { const r: T[] = []; xs.forEach((x, i) => { if (i > 0) r.push(sep); r.push(x); }); return r; },
  windows<T>(xs: T[], n: number): T[][] { if (n <= 0 || n > xs.length) return []; const r: T[][] = []; for (let i = 0; i <= xs.length - n; i++) r.push(xs.slice(i, i + n)); return r; },
  dedup<T>(xs: T[]): T[] { const r: T[] = []; for (const x of xs) { if (r.length === 0 || r[r.length - 1] !== x) r.push(x); } return r; },
  zip_with<A, B, C>(a: A[], b: B[], f: (x: A, y: B) => C): C[] { return a.slice(0, Math.min(a.length, b.length)).map((x, i) => f(x, b[i])); },
  sum_float(xs: number[]): number { return xs.reduce((a, b) => a + b, 0); },
  product_float(xs: number[]): number { return xs.reduce((a, b) => a * b, 1); },
};
"#;

pub(super) const MOD_LIST_JS: &str = r#"const __almd_list = {
  len(xs) { return xs.length; },
  get(xs, i) { return (i >= 0 && i < xs.length) ? xs[i] : null; },
  get_or(xs, i, d) { return (i >= 0 && i < xs.length) ? xs[i] : d; },
  set(xs, i, v) { const r = [...xs]; if (i >= 0 && i < r.length) r[i] = v; return r; },
  swap(xs, i, j) { const r = [...xs]; if (i >= 0 && i < r.length && j >= 0 && j < r.length) { const t = r[i]; r[i] = r[j]; r[j] = t; } return r; },
  sort(xs) { return [...xs].sort(); },
  reverse(xs) { return [...xs].reverse(); },
  any(xs, f) { return xs.some(f); },
  all(xs, f) { return xs.every(f); },
  contains(xs, x) { return xs.includes(x); },
  each(xs, f) { xs.forEach(f); },
  map(xs, f) { return xs.map(f); },
  filter(xs, f) { return xs.filter(f); },
  find(xs, f) { return xs.find(f) ?? null; },
  fold(xs, init, f) { return xs.reduce(f, init); },
  enumerate(xs) { return xs.map((x, i) => [i, x]); },
  zip(a, b) { return a.slice(0, Math.min(a.length, b.length)).map((x, i) => [x, b[i]]); },
  flatten(xss) { return xss.flat(); },
  take(xs, n) { return xs.slice(0, n); },
  drop(xs, n) { return xs.slice(n); },
  sort_by(xs, f) { return [...xs].sort((a, b) => { const ka = f(a), kb = f(b); return ka < kb ? -1 : ka > kb ? 1 : 0; }); },
  unique(xs) { const seen = []; return xs.filter(x => { if (seen.includes(x)) return false; seen.push(x); return true; }); },
  index_of(xs, x) { const i = xs.indexOf(x); return i >= 0 ? i : null; },
  chunk(xs, n) { const r = []; for (let i = 0; i < xs.length; i += n) r.push(xs.slice(i, i + n)); return r; },
  filter_map(xs, f) { const r = []; for (const x of xs) { const v = f(x); if (v !== null) r.push(v); } return r; },
  take_while(xs, f) { const r = []; for (const x of xs) { if (!f(x)) break; r.push(x); } return r; },
  drop_while(xs, f) { let dropping = true; const r = []; for (const x of xs) { if (dropping && f(x)) continue; dropping = false; r.push(x); } return r; },
  count(xs, f) { return xs.filter(f).length; },
  partition(xs, f) { const a = [], b = []; for (const x of xs) { if (f(x)) a.push(x); else b.push(x); } return [a, b]; },
  reduce(xs, f) { if (xs.length === 0) return null; return xs.reduce(f); },
  group_by(xs, f) { const m = new Map(); for (const x of xs) { const k = f(x); if (!m.has(k)) m.set(k, []); m.get(k).push(x); } return m; },
  last(xs) { return xs.length > 0 ? xs[xs.length - 1] : null; },
  first(xs) { return xs.length > 0 ? xs[0] : null; },
  sum(xs) { return xs.reduce((a, b) => a + b, 0); },
  product(xs) { return xs.reduce((a, b) => a * b, 1); },
  is_empty(xs) { return xs.length === 0; },
  flat_map(xs, f) { return xs.flatMap(f); },
  min(xs) { return xs.length === 0 ? null : xs.reduce((a, b) => a < b ? a : b); },
  max(xs) { return xs.length === 0 ? null : xs.reduce((a, b) => a > b ? a : b); },
  join(xs, sep) { return xs.join(sep); },
  range(start, end) { const r = []; for (let i = start; i < end; i++) r.push(i); return r; },
  slice(xs, start, end) { return xs.slice(start, end); },
  insert(xs, i, v) { const r = [...xs]; r.splice(i, 0, v); return r; },
  remove_at(xs, i) { const r = [...xs]; if (i >= 0 && i < r.length) r.splice(i, 1); return r; },
  find_index(xs, f) { const i = xs.findIndex(f); return i >= 0 ? i : null; },
  update(xs, i, f) { const r = [...xs]; if (i >= 0 && i < r.length) r[i] = f(r[i]); return r; },
  repeat(v, n) { return Array(Math.max(0, n)).fill(v); },
  scan(xs, init, f) { let acc = init; return xs.map(x => { acc = f(acc, x); return acc; }); },
  intersperse(xs, sep) { const r = []; xs.forEach((x, i) => { if (i > 0) r.push(sep); r.push(x); }); return r; },
  windows(xs, n) { if (n <= 0 || n > xs.length) return []; const r = []; for (let i = 0; i <= xs.length - n; i++) r.push(xs.slice(i, i + n)); return r; },
  dedup(xs) { const r = []; for (const x of xs) { if (r.length === 0 || r[r.length - 1] !== x) r.push(x); } return r; },
  zip_with(a, b, f) { return a.slice(0, Math.min(a.length, b.length)).map((x, i) => f(x, b[i])); },
  sum_float(xs) { return xs.reduce((a, b) => a + b, 0); },
  product_float(xs) { return xs.reduce((a, b) => a * b, 1); },
};
"#;

// ──────────────────────────────── map ────────────────────────────────

pub(super) const MOD_MAP_TS: &str = r#"const __almd_map = {
  new<K, V>(): Map<K, V> { return new Map(); },
  get<K, V>(m: Map<K, V>, k: K): V | null { return m.has(k) ? m.get(k)! : null; },
  get_or<K, V>(m: Map<K, V>, k: K, d: V): V { return m.has(k) ? m.get(k)! : d; },
  set<K, V>(m: Map<K, V>, k: K, v: V): Map<K, V> { const r = new Map(m); r.set(k, v); return r; },
  contains<K, V>(m: Map<K, V>, k: K): boolean { return m.has(k); },
  remove<K, V>(m: Map<K, V>, k: K): Map<K, V> { const r = new Map(m); r.delete(k); return r; },
  keys<K, V>(m: Map<K, V>): K[] { return [...m.keys()].sort() as any; },
  values<K, V>(m: Map<K, V>): V[] { return [...m.values()]; },
  len<K, V>(m: Map<K, V>): number { return m.size; },
  entries<K, V>(m: Map<K, V>): [K, V][] { return [...m.entries()]; },
  from_list<T, K, V>(xs: T[], f: (x: T) => [K, V]): Map<K, V> { const r = new Map<K, V>(); for (const x of xs) { const [k, v] = f(x); r.set(k, v); } return r; },
  map_values<K, V, V2>(m: Map<K, V>, f: (v: V) => V2): Map<K, V2> { const r = new Map<K, V2>(); m.forEach((v, k) => r.set(k, f(v))); return r; },
  filter<K, V>(m: Map<K, V>, f: (k: K, v: V) => boolean): Map<K, V> { const r = new Map<K, V>(); m.forEach((v, k) => { if (f(k, v)) r.set(k, v); }); return r; },
  from_entries<K, V>(entries: [K, V][]): Map<K, V> { const r = new Map<K, V>(); for (const [k, v] of entries) r.set(k, v); return r; },
  merge<K, V>(a: Map<K, V>, b: Map<K, V>): Map<K, V> { const r = new Map(a); b.forEach((v, k) => r.set(k, v)); return r; },
  is_empty<K, V>(m: Map<K, V>): boolean { return m.size === 0; },
};
"#;

pub(super) const MOD_MAP_JS: &str = r#"const __almd_map = {
  new() { return new Map(); },
  get(m, k) { return m.has(k) ? m.get(k) : null; },
  get_or(m, k, d) { return m.has(k) ? m.get(k) : d; },
  set(m, k, v) { const r = new Map(m); r.set(k, v); return r; },
  contains(m, k) { return m.has(k); },
  remove(m, k) { const r = new Map(m); r.delete(k); return r; },
  keys(m) { return [...m.keys()].sort(); },
  values(m) { return [...m.values()]; },
  len(m) { return m.size; },
  entries(m) { return [...m.entries()]; },
  from_list(xs, f) { const r = new Map(); for (const x of xs) { const [k, v] = f(x); r.set(k, v); } return r; },
  map_values(m, f) { const r = new Map(); m.forEach((v, k) => r.set(k, f(v))); return r; },
  filter(m, f) { const r = new Map(); m.forEach((v, k) => { if (f(k, v)) r.set(k, v); }); return r; },
  from_entries(entries) { const r = new Map(); for (const [k, v] of entries) r.set(k, v); return r; },
  merge(a, b) { const r = new Map(a); b.forEach((v, k) => r.set(k, v)); return r; },
  is_empty(m) { return m.size === 0; },
};
"#;
