/// Runtime modules for Almide TypeScript/JavaScript code generation.
///
/// All module sources are auto-generated by build.rs from runtime/{ts,js}/ files.
/// To add a new runtime module, just create runtime/ts/<name>.ts and runtime/js/<name>.js.
/// No manual registration needed — build.rs scans the directories automatically.

#[path = "../generated/ts_runtime.rs"]
mod generated;

pub use generated::*;
