/// Runtime modules for Almide TypeScript code generation.
///
/// All module sources are auto-generated by build.rs from runtime/ts/ files.
/// To add a new runtime module, just create runtime/ts/<name>.ts.
/// No manual registration needed — build.rs scans the directory automatically.

#[path = "../generated/ts_runtime.rs"]
mod generated;

pub use generated::*;
